
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  CollegeAdmin: 'CollegeAdmin',
  College: 'College',
  Club: 'Club',
  Student: 'Student',
  StudentInClub: 'StudentInClub',
  Faculty: 'Faculty',
  RoleInClub: 'RoleInClub',
  clubAdmin: 'clubAdmin',
  Event: 'Event',
  Registrations: 'Registrations'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const CollegeAdminScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  phone: 'phone',
  collegeId: 'collegeId'
} as const

export type CollegeAdminScalarFieldEnum = (typeof CollegeAdminScalarFieldEnum)[keyof typeof CollegeAdminScalarFieldEnum]


export const CollegeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  city: 'city',
  state: 'state',
  collegeType: 'collegeType',
  logoUrl: 'logoUrl',
  websiteUrl: 'websiteUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  country: 'country',
  accrediation: 'accrediation',
  address: 'address',
  affiliatedUniversity: 'affiliatedUniversity',
  deletedAt: 'deletedAt',
  establisedYear: 'establisedYear',
  latitude: 'latitude',
  longitude: 'longitude',
  officialEmail: 'officialEmail',
  phone: 'phone',
  pincode: 'pincode',
  regitrationNumber: 'regitrationNumber',
  verificationNote: 'verificationNote',
  verififedTime: 'verififedTime',
  verified: 'verified'
} as const

export type CollegeScalarFieldEnum = (typeof CollegeScalarFieldEnum)[keyof typeof CollegeScalarFieldEnum]


export const ClubScalarFieldEnum = {
  id: 'id',
  name: 'name',
  collegeId: 'collegeId',
  description: 'description',
  cordinatorId: 'cordinatorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  onHold: 'onHold',
  category: 'category',
  instagramUrl: 'instagramUrl',
  twitterUrl: 'twitterUrl',
  linkedinUrl: 'linkedinUrl',
  youtubeUrl: 'youtubeUrl',
  websiteUrl: 'websiteUrl'
} as const

export type ClubScalarFieldEnum = (typeof ClubScalarFieldEnum)[keyof typeof ClubScalarFieldEnum]


export const StudentScalarFieldEnum = {
  id: 'id',
  firstName: 'firstName',
  lastName: 'lastName',
  email: 'email',
  password: 'password',
  rollnumber: 'rollnumber',
  collegeId: 'collegeId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type StudentScalarFieldEnum = (typeof StudentScalarFieldEnum)[keyof typeof StudentScalarFieldEnum]


export const StudentInClubScalarFieldEnum = {
  id: 'id',
  clubId: 'clubId',
  studentId: 'studentId',
  roleId: 'roleId',
  status: 'status'
} as const

export type StudentInClubScalarFieldEnum = (typeof StudentInClubScalarFieldEnum)[keyof typeof StudentInClubScalarFieldEnum]


export const FacultyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  collegeId: 'collegeId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  email: 'email',
  password: 'password'
} as const

export type FacultyScalarFieldEnum = (typeof FacultyScalarFieldEnum)[keyof typeof FacultyScalarFieldEnum]


export const RoleInClubScalarFieldEnum = {
  id: 'id',
  name: 'name',
  clubId: 'clubId'
} as const

export type RoleInClubScalarFieldEnum = (typeof RoleInClubScalarFieldEnum)[keyof typeof RoleInClubScalarFieldEnum]


export const ClubAdminScalarFieldEnum = {
  id: 'id',
  firstName: 'firstName',
  lastName: 'lastName',
  email: 'email',
  password: 'password',
  clubId: 'clubId'
} as const

export type ClubAdminScalarFieldEnum = (typeof ClubAdminScalarFieldEnum)[keyof typeof ClubAdminScalarFieldEnum]


export const EventScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  clubId: 'clubId',
  date: 'date',
  time: 'time',
  mode: 'mode',
  registrationLink: 'registrationLink',
  registrationFee: 'registrationFee',
  registrationOpen: 'registrationOpen',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  venue: 'venue',
  city: 'city',
  banner: 'banner',
  capacity: 'capacity',
  registrationDeadline: 'registrationDeadline',
  status: 'status',
  isPublic: 'isPublic',
  category: 'category'
} as const

export type EventScalarFieldEnum = (typeof EventScalarFieldEnum)[keyof typeof EventScalarFieldEnum]


export const RegistrationsScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  eventId: 'eventId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type RegistrationsScalarFieldEnum = (typeof RegistrationsScalarFieldEnum)[keyof typeof RegistrationsScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

