
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model CollegeAdmin
 * 
 */
export type CollegeAdmin = Prisma.CollegeAdminModel
/**
 * Model College
 * 
 */
export type College = Prisma.CollegeModel
/**
 * Model Club
 * 
 */
export type Club = Prisma.ClubModel
/**
 * Model Student
 * 
 */
export type Student = Prisma.StudentModel
/**
 * Model StudentInClub
 * 
 */
export type StudentInClub = Prisma.StudentInClubModel
/**
 * Model Faculty
 * 
 */
export type Faculty = Prisma.FacultyModel
/**
 * Model RoleInClub
 * 
 */
export type RoleInClub = Prisma.RoleInClubModel
/**
 * Model clubAdmin
 * 
 */
export type clubAdmin = Prisma.clubAdminModel
/**
 * Model Event
 * 
 */
export type Event = Prisma.EventModel
/**
 * Model Registrations
 * 
 */
export type Registrations = Prisma.RegistrationsModel
