
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/CollegeAdmin'
export type * from './models/College'
export type * from './models/Club'
export type * from './models/Student'
export type * from './models/StudentInClub'
export type * from './models/Faculty'
export type * from './models/RoleInClub'
export type * from './models/clubAdmin'
export type * from './commonInputTypes'