import type { Prisma } from '../../prisma/client';
import * as z from 'zod';
import { RoleInClubOrderByWithRelationInputObjectSchema as RoleInClubOrderByWithRelationInputObjectSchema } from './objects/RoleInClubOrderByWithRelationInput.schema';
import { RoleInClubWhereInputObjectSchema as RoleInClubWhereInputObjectSchema } from './objects/RoleInClubWhereInput.schema';
import { RoleInClubWhereUniqueInputObjectSchema as RoleInClubWhereUniqueInputObjectSchema } from './objects/RoleInClubWhereUniqueInput.schema';
import { RoleInClubCountAggregateInputObjectSchema as RoleInClubCountAggregateInputObjectSchema } from './objects/RoleInClubCountAggregateInput.schema';
import { RoleInClubMinAggregateInputObjectSchema as RoleInClubMinAggregateInputObjectSchema } from './objects/RoleInClubMinAggregateInput.schema';
import { RoleInClubMaxAggregateInputObjectSchema as RoleInClubMaxAggregateInputObjectSchema } from './objects/RoleInClubMaxAggregateInput.schema';

export const RoleInClubAggregateSchema: z.ZodType<Prisma.RoleInClubAggregateArgs> = z.object({ orderBy: z.union([RoleInClubOrderByWithRelationInputObjectSchema, RoleInClubOrderByWithRelationInputObjectSchema.array()]).optional(), where: RoleInClubWhereInputObjectSchema.optional(), cursor: RoleInClubWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), RoleInClubCountAggregateInputObjectSchema ]).optional(), _min: RoleInClubMinAggregateInputObjectSchema.optional(), _max: RoleInClubMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.RoleInClubAggregateArgs>;

export const RoleInClubAggregateZodSchema = z.object({ orderBy: z.union([RoleInClubOrderByWithRelationInputObjectSchema, RoleInClubOrderByWithRelationInputObjectSchema.array()]).optional(), where: RoleInClubWhereInputObjectSchema.optional(), cursor: RoleInClubWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), RoleInClubCountAggregateInputObjectSchema ]).optional(), _min: RoleInClubMinAggregateInputObjectSchema.optional(), _max: RoleInClubMaxAggregateInputObjectSchema.optional() }).strict();