import type { Prisma } from '../../prisma/client';
import * as z from 'zod';
import { CollegeAdminOrderByWithRelationInputObjectSchema as CollegeAdminOrderByWithRelationInputObjectSchema } from './objects/CollegeAdminOrderByWithRelationInput.schema';
import { CollegeAdminWhereInputObjectSchema as CollegeAdminWhereInputObjectSchema } from './objects/CollegeAdminWhereInput.schema';
import { CollegeAdminWhereUniqueInputObjectSchema as CollegeAdminWhereUniqueInputObjectSchema } from './objects/CollegeAdminWhereUniqueInput.schema';
import { CollegeAdminCountAggregateInputObjectSchema as CollegeAdminCountAggregateInputObjectSchema } from './objects/CollegeAdminCountAggregateInput.schema';
import { CollegeAdminMinAggregateInputObjectSchema as CollegeAdminMinAggregateInputObjectSchema } from './objects/CollegeAdminMinAggregateInput.schema';
import { CollegeAdminMaxAggregateInputObjectSchema as CollegeAdminMaxAggregateInputObjectSchema } from './objects/CollegeAdminMaxAggregateInput.schema';

export const CollegeAdminAggregateSchema: z.ZodType<Prisma.CollegeAdminAggregateArgs> = z.object({ orderBy: z.union([CollegeAdminOrderByWithRelationInputObjectSchema, CollegeAdminOrderByWithRelationInputObjectSchema.array()]).optional(), where: CollegeAdminWhereInputObjectSchema.optional(), cursor: CollegeAdminWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), CollegeAdminCountAggregateInputObjectSchema ]).optional(), _min: CollegeAdminMinAggregateInputObjectSchema.optional(), _max: CollegeAdminMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.CollegeAdminAggregateArgs>;

export const CollegeAdminAggregateZodSchema = z.object({ orderBy: z.union([CollegeAdminOrderByWithRelationInputObjectSchema, CollegeAdminOrderByWithRelationInputObjectSchema.array()]).optional(), where: CollegeAdminWhereInputObjectSchema.optional(), cursor: CollegeAdminWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), CollegeAdminCountAggregateInputObjectSchema ]).optional(), _min: CollegeAdminMinAggregateInputObjectSchema.optional(), _max: CollegeAdminMaxAggregateInputObjectSchema.optional() }).strict();