import type { Prisma } from '../../prisma/client';
import * as z from 'zod';
import { RegistrationsWhereInputObjectSchema as RegistrationsWhereInputObjectSchema } from './objects/RegistrationsWhereInput.schema';
import { RegistrationsOrderByWithAggregationInputObjectSchema as RegistrationsOrderByWithAggregationInputObjectSchema } from './objects/RegistrationsOrderByWithAggregationInput.schema';
import { RegistrationsScalarWhereWithAggregatesInputObjectSchema as RegistrationsScalarWhereWithAggregatesInputObjectSchema } from './objects/RegistrationsScalarWhereWithAggregatesInput.schema';
import { RegistrationsScalarFieldEnumSchema } from './enums/RegistrationsScalarFieldEnum.schema';
import { RegistrationsCountAggregateInputObjectSchema as RegistrationsCountAggregateInputObjectSchema } from './objects/RegistrationsCountAggregateInput.schema';
import { RegistrationsMinAggregateInputObjectSchema as RegistrationsMinAggregateInputObjectSchema } from './objects/RegistrationsMinAggregateInput.schema';
import { RegistrationsMaxAggregateInputObjectSchema as RegistrationsMaxAggregateInputObjectSchema } from './objects/RegistrationsMaxAggregateInput.schema';

export const RegistrationsGroupBySchema: z.ZodType<Prisma.RegistrationsGroupByArgs> = z.object({ where: RegistrationsWhereInputObjectSchema.optional(), orderBy: z.union([RegistrationsOrderByWithAggregationInputObjectSchema, RegistrationsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: RegistrationsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(RegistrationsScalarFieldEnumSchema), _count: z.union([ z.literal(true), RegistrationsCountAggregateInputObjectSchema ]).optional(), _min: RegistrationsMinAggregateInputObjectSchema.optional(), _max: RegistrationsMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.RegistrationsGroupByArgs>;

export const RegistrationsGroupByZodSchema = z.object({ where: RegistrationsWhereInputObjectSchema.optional(), orderBy: z.union([RegistrationsOrderByWithAggregationInputObjectSchema, RegistrationsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: RegistrationsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(RegistrationsScalarFieldEnumSchema), _count: z.union([ z.literal(true), RegistrationsCountAggregateInputObjectSchema ]).optional(), _min: RegistrationsMinAggregateInputObjectSchema.optional(), _max: RegistrationsMaxAggregateInputObjectSchema.optional() }).strict();