import type { Prisma } from '../../prisma/client';
import * as z from 'zod';
import { clubAdminWhereInputObjectSchema as clubAdminWhereInputObjectSchema } from './objects/clubAdminWhereInput.schema';
import { clubAdminOrderByWithAggregationInputObjectSchema as clubAdminOrderByWithAggregationInputObjectSchema } from './objects/clubAdminOrderByWithAggregationInput.schema';
import { clubAdminScalarWhereWithAggregatesInputObjectSchema as clubAdminScalarWhereWithAggregatesInputObjectSchema } from './objects/clubAdminScalarWhereWithAggregatesInput.schema';
import { ClubAdminScalarFieldEnumSchema } from './enums/ClubAdminScalarFieldEnum.schema';
import { ClubAdminCountAggregateInputObjectSchema as ClubAdminCountAggregateInputObjectSchema } from './objects/ClubAdminCountAggregateInput.schema';
import { ClubAdminMinAggregateInputObjectSchema as ClubAdminMinAggregateInputObjectSchema } from './objects/ClubAdminMinAggregateInput.schema';
import { ClubAdminMaxAggregateInputObjectSchema as ClubAdminMaxAggregateInputObjectSchema } from './objects/ClubAdminMaxAggregateInput.schema';

export const clubAdminGroupBySchema: z.ZodType<Prisma.clubAdminGroupByArgs> = z.object({ where: clubAdminWhereInputObjectSchema.optional(), orderBy: z.union([clubAdminOrderByWithAggregationInputObjectSchema, clubAdminOrderByWithAggregationInputObjectSchema.array()]).optional(), having: clubAdminScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ClubAdminScalarFieldEnumSchema), _count: z.union([ z.literal(true), ClubAdminCountAggregateInputObjectSchema ]).optional(), _min: ClubAdminMinAggregateInputObjectSchema.optional(), _max: ClubAdminMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.clubAdminGroupByArgs>;

export const clubAdminGroupByZodSchema = z.object({ where: clubAdminWhereInputObjectSchema.optional(), orderBy: z.union([clubAdminOrderByWithAggregationInputObjectSchema, clubAdminOrderByWithAggregationInputObjectSchema.array()]).optional(), having: clubAdminScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ClubAdminScalarFieldEnumSchema), _count: z.union([ z.literal(true), ClubAdminCountAggregateInputObjectSchema ]).optional(), _min: ClubAdminMinAggregateInputObjectSchema.optional(), _max: ClubAdminMaxAggregateInputObjectSchema.optional() }).strict();