import type { Prisma } from '../../prisma/client';
import * as z from 'zod';
import { StudentInClubWhereInputObjectSchema as StudentInClubWhereInputObjectSchema } from './objects/StudentInClubWhereInput.schema';
import { StudentInClubOrderByWithAggregationInputObjectSchema as StudentInClubOrderByWithAggregationInputObjectSchema } from './objects/StudentInClubOrderByWithAggregationInput.schema';
import { StudentInClubScalarWhereWithAggregatesInputObjectSchema as StudentInClubScalarWhereWithAggregatesInputObjectSchema } from './objects/StudentInClubScalarWhereWithAggregatesInput.schema';
import { StudentInClubScalarFieldEnumSchema } from './enums/StudentInClubScalarFieldEnum.schema';
import { StudentInClubCountAggregateInputObjectSchema as StudentInClubCountAggregateInputObjectSchema } from './objects/StudentInClubCountAggregateInput.schema';
import { StudentInClubMinAggregateInputObjectSchema as StudentInClubMinAggregateInputObjectSchema } from './objects/StudentInClubMinAggregateInput.schema';
import { StudentInClubMaxAggregateInputObjectSchema as StudentInClubMaxAggregateInputObjectSchema } from './objects/StudentInClubMaxAggregateInput.schema';

export const StudentInClubGroupBySchema: z.ZodType<Prisma.StudentInClubGroupByArgs> = z.object({ where: StudentInClubWhereInputObjectSchema.optional(), orderBy: z.union([StudentInClubOrderByWithAggregationInputObjectSchema, StudentInClubOrderByWithAggregationInputObjectSchema.array()]).optional(), having: StudentInClubScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(StudentInClubScalarFieldEnumSchema), _count: z.union([ z.literal(true), StudentInClubCountAggregateInputObjectSchema ]).optional(), _min: StudentInClubMinAggregateInputObjectSchema.optional(), _max: StudentInClubMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.StudentInClubGroupByArgs>;

export const StudentInClubGroupByZodSchema = z.object({ where: StudentInClubWhereInputObjectSchema.optional(), orderBy: z.union([StudentInClubOrderByWithAggregationInputObjectSchema, StudentInClubOrderByWithAggregationInputObjectSchema.array()]).optional(), having: StudentInClubScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(StudentInClubScalarFieldEnumSchema), _count: z.union([ z.literal(true), StudentInClubCountAggregateInputObjectSchema ]).optional(), _min: StudentInClubMinAggregateInputObjectSchema.optional(), _max: StudentInClubMaxAggregateInputObjectSchema.optional() }).strict();