import type { Prisma } from '../../prisma/client';
import * as z from 'zod';
import { CollegeAdminWhereInputObjectSchema as CollegeAdminWhereInputObjectSchema } from './objects/CollegeAdminWhereInput.schema';
import { CollegeAdminOrderByWithAggregationInputObjectSchema as CollegeAdminOrderByWithAggregationInputObjectSchema } from './objects/CollegeAdminOrderByWithAggregationInput.schema';
import { CollegeAdminScalarWhereWithAggregatesInputObjectSchema as CollegeAdminScalarWhereWithAggregatesInputObjectSchema } from './objects/CollegeAdminScalarWhereWithAggregatesInput.schema';
import { CollegeAdminScalarFieldEnumSchema } from './enums/CollegeAdminScalarFieldEnum.schema';
import { CollegeAdminCountAggregateInputObjectSchema as CollegeAdminCountAggregateInputObjectSchema } from './objects/CollegeAdminCountAggregateInput.schema';
import { CollegeAdminMinAggregateInputObjectSchema as CollegeAdminMinAggregateInputObjectSchema } from './objects/CollegeAdminMinAggregateInput.schema';
import { CollegeAdminMaxAggregateInputObjectSchema as CollegeAdminMaxAggregateInputObjectSchema } from './objects/CollegeAdminMaxAggregateInput.schema';

export const CollegeAdminGroupBySchema: z.ZodType<Prisma.CollegeAdminGroupByArgs> = z.object({ where: CollegeAdminWhereInputObjectSchema.optional(), orderBy: z.union([CollegeAdminOrderByWithAggregationInputObjectSchema, CollegeAdminOrderByWithAggregationInputObjectSchema.array()]).optional(), having: CollegeAdminScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(CollegeAdminScalarFieldEnumSchema), _count: z.union([ z.literal(true), CollegeAdminCountAggregateInputObjectSchema ]).optional(), _min: CollegeAdminMinAggregateInputObjectSchema.optional(), _max: CollegeAdminMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.CollegeAdminGroupByArgs>;

export const CollegeAdminGroupByZodSchema = z.object({ where: CollegeAdminWhereInputObjectSchema.optional(), orderBy: z.union([CollegeAdminOrderByWithAggregationInputObjectSchema, CollegeAdminOrderByWithAggregationInputObjectSchema.array()]).optional(), having: CollegeAdminScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(CollegeAdminScalarFieldEnumSchema), _count: z.union([ z.literal(true), CollegeAdminCountAggregateInputObjectSchema ]).optional(), _min: CollegeAdminMinAggregateInputObjectSchema.optional(), _max: CollegeAdminMaxAggregateInputObjectSchema.optional() }).strict();