
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Club` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Club
 * 
 */
export type ClubModel = runtime.Types.Result.DefaultSelection<Prisma.$ClubPayload>

export type AggregateClub = {
  _count: ClubCountAggregateOutputType | null
  _min: ClubMinAggregateOutputType | null
  _max: ClubMaxAggregateOutputType | null
}

export type ClubMinAggregateOutputType = {
  id: string | null
  name: string | null
  collegeId: string | null
  description: string | null
  cordinatorId: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
  category: string | null
  onHold: boolean | null
}

export type ClubMaxAggregateOutputType = {
  id: string | null
  name: string | null
  collegeId: string | null
  description: string | null
  cordinatorId: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
  category: string | null
  onHold: boolean | null
}

export type ClubCountAggregateOutputType = {
  id: number
  name: number
  collegeId: number
  description: number
  cordinatorId: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  category: number
  onHold: number
  _all: number
}


export type ClubMinAggregateInputType = {
  id?: true
  name?: true
  collegeId?: true
  description?: true
  cordinatorId?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  category?: true
  onHold?: true
}

export type ClubMaxAggregateInputType = {
  id?: true
  name?: true
  collegeId?: true
  description?: true
  cordinatorId?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  category?: true
  onHold?: true
}

export type ClubCountAggregateInputType = {
  id?: true
  name?: true
  collegeId?: true
  description?: true
  cordinatorId?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  category?: true
  onHold?: true
  _all?: true
}

export type ClubAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Club to aggregate.
   */
  where?: Prisma.ClubWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clubs to fetch.
   */
  orderBy?: Prisma.ClubOrderByWithRelationInput | Prisma.ClubOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ClubWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clubs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clubs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Clubs
  **/
  _count?: true | ClubCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ClubMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ClubMaxAggregateInputType
}

export type GetClubAggregateType<T extends ClubAggregateArgs> = {
      [P in keyof T & keyof AggregateClub]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateClub[P]>
    : Prisma.GetScalarType<T[P], AggregateClub[P]>
}




export type ClubGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ClubWhereInput
  orderBy?: Prisma.ClubOrderByWithAggregationInput | Prisma.ClubOrderByWithAggregationInput[]
  by: Prisma.ClubScalarFieldEnum[] | Prisma.ClubScalarFieldEnum
  having?: Prisma.ClubScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ClubCountAggregateInputType | true
  _min?: ClubMinAggregateInputType
  _max?: ClubMaxAggregateInputType
}

export type ClubGroupByOutputType = {
  id: string
  name: string
  collegeId: string
  description: string | null
  cordinatorId: string | null
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  category: string
  onHold: boolean
  _count: ClubCountAggregateOutputType | null
  _min: ClubMinAggregateOutputType | null
  _max: ClubMaxAggregateOutputType | null
}

type GetClubGroupByPayload<T extends ClubGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ClubGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ClubGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ClubGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ClubGroupByOutputType[P]>
      }
    >
  >



export type ClubWhereInput = {
  AND?: Prisma.ClubWhereInput | Prisma.ClubWhereInput[]
  OR?: Prisma.ClubWhereInput[]
  NOT?: Prisma.ClubWhereInput | Prisma.ClubWhereInput[]
  id?: Prisma.StringFilter<"Club"> | string
  name?: Prisma.StringFilter<"Club"> | string
  collegeId?: Prisma.StringFilter<"Club"> | string
  description?: Prisma.StringNullableFilter<"Club"> | string | null
  cordinatorId?: Prisma.StringNullableFilter<"Club"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Club"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Club"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Club"> | Date | string | null
  category?: Prisma.StringFilter<"Club"> | string
  onHold?: Prisma.BoolFilter<"Club"> | boolean
  clubAdmin?: Prisma.XOR<Prisma.ClubAdminNullableScalarRelationFilter, Prisma.clubAdminWhereInput> | null
  college?: Prisma.XOR<Prisma.CollegeScalarRelationFilter, Prisma.CollegeWhereInput>
  students?: Prisma.StudentInClubListRelationFilter
  coordinator?: Prisma.XOR<Prisma.FacultyNullableScalarRelationFilter, Prisma.FacultyWhereInput> | null
  role?: Prisma.RoleInClubListRelationFilter
  events?: Prisma.EventListRelationFilter
}

export type ClubOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  collegeId?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  cordinatorId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.SortOrder
  onHold?: Prisma.SortOrder
  clubAdmin?: Prisma.clubAdminOrderByWithRelationInput
  college?: Prisma.CollegeOrderByWithRelationInput
  students?: Prisma.StudentInClubOrderByRelationAggregateInput
  coordinator?: Prisma.FacultyOrderByWithRelationInput
  role?: Prisma.RoleInClubOrderByRelationAggregateInput
  events?: Prisma.EventOrderByRelationAggregateInput
}

export type ClubWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  collegeId_name?: Prisma.ClubCollegeIdNameCompoundUniqueInput
  AND?: Prisma.ClubWhereInput | Prisma.ClubWhereInput[]
  OR?: Prisma.ClubWhereInput[]
  NOT?: Prisma.ClubWhereInput | Prisma.ClubWhereInput[]
  name?: Prisma.StringFilter<"Club"> | string
  collegeId?: Prisma.StringFilter<"Club"> | string
  description?: Prisma.StringNullableFilter<"Club"> | string | null
  cordinatorId?: Prisma.StringNullableFilter<"Club"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Club"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Club"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Club"> | Date | string | null
  category?: Prisma.StringFilter<"Club"> | string
  onHold?: Prisma.BoolFilter<"Club"> | boolean
  clubAdmin?: Prisma.XOR<Prisma.ClubAdminNullableScalarRelationFilter, Prisma.clubAdminWhereInput> | null
  college?: Prisma.XOR<Prisma.CollegeScalarRelationFilter, Prisma.CollegeWhereInput>
  students?: Prisma.StudentInClubListRelationFilter
  coordinator?: Prisma.XOR<Prisma.FacultyNullableScalarRelationFilter, Prisma.FacultyWhereInput> | null
  role?: Prisma.RoleInClubListRelationFilter
  events?: Prisma.EventListRelationFilter
}, "id" | "collegeId_name">

export type ClubOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  collegeId?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  cordinatorId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.SortOrder
  onHold?: Prisma.SortOrder
  _count?: Prisma.ClubCountOrderByAggregateInput
  _max?: Prisma.ClubMaxOrderByAggregateInput
  _min?: Prisma.ClubMinOrderByAggregateInput
}

export type ClubScalarWhereWithAggregatesInput = {
  AND?: Prisma.ClubScalarWhereWithAggregatesInput | Prisma.ClubScalarWhereWithAggregatesInput[]
  OR?: Prisma.ClubScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ClubScalarWhereWithAggregatesInput | Prisma.ClubScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Club"> | string
  name?: Prisma.StringWithAggregatesFilter<"Club"> | string
  collegeId?: Prisma.StringWithAggregatesFilter<"Club"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Club"> | string | null
  cordinatorId?: Prisma.StringNullableWithAggregatesFilter<"Club"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Club"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Club"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Club"> | Date | string | null
  category?: Prisma.StringWithAggregatesFilter<"Club"> | string
  onHold?: Prisma.BoolWithAggregatesFilter<"Club"> | boolean
}

export type ClubCreateInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  category: string
  onHold?: boolean
  clubAdmin?: Prisma.clubAdminCreateNestedOneWithoutClubInput
  college: Prisma.CollegeCreateNestedOneWithoutClubsInput
  students?: Prisma.StudentInClubCreateNestedManyWithoutClubInput
  coordinator?: Prisma.FacultyCreateNestedOneWithoutClubInput
  role?: Prisma.RoleInClubCreateNestedManyWithoutClubInput
  events?: Prisma.EventCreateNestedManyWithoutClubInput
}

export type ClubUncheckedCreateInput = {
  id?: string
  name: string
  collegeId: string
  description?: string | null
  cordinatorId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  category: string
  onHold?: boolean
  clubAdmin?: Prisma.clubAdminUncheckedCreateNestedOneWithoutClubInput
  students?: Prisma.StudentInClubUncheckedCreateNestedManyWithoutClubInput
  role?: Prisma.RoleInClubUncheckedCreateNestedManyWithoutClubInput
  events?: Prisma.EventUncheckedCreateNestedManyWithoutClubInput
}

export type ClubUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  onHold?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clubAdmin?: Prisma.clubAdminUpdateOneWithoutClubNestedInput
  college?: Prisma.CollegeUpdateOneRequiredWithoutClubsNestedInput
  students?: Prisma.StudentInClubUpdateManyWithoutClubNestedInput
  coordinator?: Prisma.FacultyUpdateOneWithoutClubNestedInput
  role?: Prisma.RoleInClubUpdateManyWithoutClubNestedInput
  events?: Prisma.EventUpdateManyWithoutClubNestedInput
}

export type ClubUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  collegeId?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cordinatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  onHold?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clubAdmin?: Prisma.clubAdminUncheckedUpdateOneWithoutClubNestedInput
  students?: Prisma.StudentInClubUncheckedUpdateManyWithoutClubNestedInput
  role?: Prisma.RoleInClubUncheckedUpdateManyWithoutClubNestedInput
  events?: Prisma.EventUncheckedUpdateManyWithoutClubNestedInput
}

export type ClubCreateManyInput = {
  id?: string
  name: string
  collegeId: string
  description?: string | null
  cordinatorId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  category: string
  onHold?: boolean
}

export type ClubUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  onHold?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ClubUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  collegeId?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cordinatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  onHold?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ClubListRelationFilter = {
  every?: Prisma.ClubWhereInput
  some?: Prisma.ClubWhereInput
  none?: Prisma.ClubWhereInput
}

export type ClubOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ClubCollegeIdNameCompoundUniqueInput = {
  collegeId: string
  name: string
}

export type ClubCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  collegeId?: Prisma.SortOrder
  description?: Prisma.SortOrder
  cordinatorId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  category?: Prisma.SortOrder
  onHold?: Prisma.SortOrder
}

export type ClubMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  collegeId?: Prisma.SortOrder
  description?: Prisma.SortOrder
  cordinatorId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  category?: Prisma.SortOrder
  onHold?: Prisma.SortOrder
}

export type ClubMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  collegeId?: Prisma.SortOrder
  description?: Prisma.SortOrder
  cordinatorId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  category?: Prisma.SortOrder
  onHold?: Prisma.SortOrder
}

export type ClubScalarRelationFilter = {
  is?: Prisma.ClubWhereInput
  isNot?: Prisma.ClubWhereInput
}

export type ClubCreateNestedManyWithoutCollegeInput = {
  create?: Prisma.XOR<Prisma.ClubCreateWithoutCollegeInput, Prisma.ClubUncheckedCreateWithoutCollegeInput> | Prisma.ClubCreateWithoutCollegeInput[] | Prisma.ClubUncheckedCreateWithoutCollegeInput[]
  connectOrCreate?: Prisma.ClubCreateOrConnectWithoutCollegeInput | Prisma.ClubCreateOrConnectWithoutCollegeInput[]
  createMany?: Prisma.ClubCreateManyCollegeInputEnvelope
  connect?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
}

export type ClubUncheckedCreateNestedManyWithoutCollegeInput = {
  create?: Prisma.XOR<Prisma.ClubCreateWithoutCollegeInput, Prisma.ClubUncheckedCreateWithoutCollegeInput> | Prisma.ClubCreateWithoutCollegeInput[] | Prisma.ClubUncheckedCreateWithoutCollegeInput[]
  connectOrCreate?: Prisma.ClubCreateOrConnectWithoutCollegeInput | Prisma.ClubCreateOrConnectWithoutCollegeInput[]
  createMany?: Prisma.ClubCreateManyCollegeInputEnvelope
  connect?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
}

export type ClubUpdateManyWithoutCollegeNestedInput = {
  create?: Prisma.XOR<Prisma.ClubCreateWithoutCollegeInput, Prisma.ClubUncheckedCreateWithoutCollegeInput> | Prisma.ClubCreateWithoutCollegeInput[] | Prisma.ClubUncheckedCreateWithoutCollegeInput[]
  connectOrCreate?: Prisma.ClubCreateOrConnectWithoutCollegeInput | Prisma.ClubCreateOrConnectWithoutCollegeInput[]
  upsert?: Prisma.ClubUpsertWithWhereUniqueWithoutCollegeInput | Prisma.ClubUpsertWithWhereUniqueWithoutCollegeInput[]
  createMany?: Prisma.ClubCreateManyCollegeInputEnvelope
  set?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
  disconnect?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
  delete?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
  connect?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
  update?: Prisma.ClubUpdateWithWhereUniqueWithoutCollegeInput | Prisma.ClubUpdateWithWhereUniqueWithoutCollegeInput[]
  updateMany?: Prisma.ClubUpdateManyWithWhereWithoutCollegeInput | Prisma.ClubUpdateManyWithWhereWithoutCollegeInput[]
  deleteMany?: Prisma.ClubScalarWhereInput | Prisma.ClubScalarWhereInput[]
}

export type ClubUncheckedUpdateManyWithoutCollegeNestedInput = {
  create?: Prisma.XOR<Prisma.ClubCreateWithoutCollegeInput, Prisma.ClubUncheckedCreateWithoutCollegeInput> | Prisma.ClubCreateWithoutCollegeInput[] | Prisma.ClubUncheckedCreateWithoutCollegeInput[]
  connectOrCreate?: Prisma.ClubCreateOrConnectWithoutCollegeInput | Prisma.ClubCreateOrConnectWithoutCollegeInput[]
  upsert?: Prisma.ClubUpsertWithWhereUniqueWithoutCollegeInput | Prisma.ClubUpsertWithWhereUniqueWithoutCollegeInput[]
  createMany?: Prisma.ClubCreateManyCollegeInputEnvelope
  set?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
  disconnect?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
  delete?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
  connect?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
  update?: Prisma.ClubUpdateWithWhereUniqueWithoutCollegeInput | Prisma.ClubUpdateWithWhereUniqueWithoutCollegeInput[]
  updateMany?: Prisma.ClubUpdateManyWithWhereWithoutCollegeInput | Prisma.ClubUpdateManyWithWhereWithoutCollegeInput[]
  deleteMany?: Prisma.ClubScalarWhereInput | Prisma.ClubScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type ClubCreateNestedOneWithoutStudentsInput = {
  create?: Prisma.XOR<Prisma.ClubCreateWithoutStudentsInput, Prisma.ClubUncheckedCreateWithoutStudentsInput>
  connectOrCreate?: Prisma.ClubCreateOrConnectWithoutStudentsInput
  connect?: Prisma.ClubWhereUniqueInput
}

export type ClubUpdateOneRequiredWithoutStudentsNestedInput = {
  create?: Prisma.XOR<Prisma.ClubCreateWithoutStudentsInput, Prisma.ClubUncheckedCreateWithoutStudentsInput>
  connectOrCreate?: Prisma.ClubCreateOrConnectWithoutStudentsInput
  upsert?: Prisma.ClubUpsertWithoutStudentsInput
  connect?: Prisma.ClubWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ClubUpdateToOneWithWhereWithoutStudentsInput, Prisma.ClubUpdateWithoutStudentsInput>, Prisma.ClubUncheckedUpdateWithoutStudentsInput>
}

export type ClubCreateNestedManyWithoutCoordinatorInput = {
  create?: Prisma.XOR<Prisma.ClubCreateWithoutCoordinatorInput, Prisma.ClubUncheckedCreateWithoutCoordinatorInput> | Prisma.ClubCreateWithoutCoordinatorInput[] | Prisma.ClubUncheckedCreateWithoutCoordinatorInput[]
  connectOrCreate?: Prisma.ClubCreateOrConnectWithoutCoordinatorInput | Prisma.ClubCreateOrConnectWithoutCoordinatorInput[]
  createMany?: Prisma.ClubCreateManyCoordinatorInputEnvelope
  connect?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
}

export type ClubUncheckedCreateNestedManyWithoutCoordinatorInput = {
  create?: Prisma.XOR<Prisma.ClubCreateWithoutCoordinatorInput, Prisma.ClubUncheckedCreateWithoutCoordinatorInput> | Prisma.ClubCreateWithoutCoordinatorInput[] | Prisma.ClubUncheckedCreateWithoutCoordinatorInput[]
  connectOrCreate?: Prisma.ClubCreateOrConnectWithoutCoordinatorInput | Prisma.ClubCreateOrConnectWithoutCoordinatorInput[]
  createMany?: Prisma.ClubCreateManyCoordinatorInputEnvelope
  connect?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
}

export type ClubUpdateManyWithoutCoordinatorNestedInput = {
  create?: Prisma.XOR<Prisma.ClubCreateWithoutCoordinatorInput, Prisma.ClubUncheckedCreateWithoutCoordinatorInput> | Prisma.ClubCreateWithoutCoordinatorInput[] | Prisma.ClubUncheckedCreateWithoutCoordinatorInput[]
  connectOrCreate?: Prisma.ClubCreateOrConnectWithoutCoordinatorInput | Prisma.ClubCreateOrConnectWithoutCoordinatorInput[]
  upsert?: Prisma.ClubUpsertWithWhereUniqueWithoutCoordinatorInput | Prisma.ClubUpsertWithWhereUniqueWithoutCoordinatorInput[]
  createMany?: Prisma.ClubCreateManyCoordinatorInputEnvelope
  set?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
  disconnect?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
  delete?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
  connect?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
  update?: Prisma.ClubUpdateWithWhereUniqueWithoutCoordinatorInput | Prisma.ClubUpdateWithWhereUniqueWithoutCoordinatorInput[]
  updateMany?: Prisma.ClubUpdateManyWithWhereWithoutCoordinatorInput | Prisma.ClubUpdateManyWithWhereWithoutCoordinatorInput[]
  deleteMany?: Prisma.ClubScalarWhereInput | Prisma.ClubScalarWhereInput[]
}

export type ClubUncheckedUpdateManyWithoutCoordinatorNestedInput = {
  create?: Prisma.XOR<Prisma.ClubCreateWithoutCoordinatorInput, Prisma.ClubUncheckedCreateWithoutCoordinatorInput> | Prisma.ClubCreateWithoutCoordinatorInput[] | Prisma.ClubUncheckedCreateWithoutCoordinatorInput[]
  connectOrCreate?: Prisma.ClubCreateOrConnectWithoutCoordinatorInput | Prisma.ClubCreateOrConnectWithoutCoordinatorInput[]
  upsert?: Prisma.ClubUpsertWithWhereUniqueWithoutCoordinatorInput | Prisma.ClubUpsertWithWhereUniqueWithoutCoordinatorInput[]
  createMany?: Prisma.ClubCreateManyCoordinatorInputEnvelope
  set?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
  disconnect?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
  delete?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
  connect?: Prisma.ClubWhereUniqueInput | Prisma.ClubWhereUniqueInput[]
  update?: Prisma.ClubUpdateWithWhereUniqueWithoutCoordinatorInput | Prisma.ClubUpdateWithWhereUniqueWithoutCoordinatorInput[]
  updateMany?: Prisma.ClubUpdateManyWithWhereWithoutCoordinatorInput | Prisma.ClubUpdateManyWithWhereWithoutCoordinatorInput[]
  deleteMany?: Prisma.ClubScalarWhereInput | Prisma.ClubScalarWhereInput[]
}

export type ClubCreateNestedOneWithoutRoleInput = {
  create?: Prisma.XOR<Prisma.ClubCreateWithoutRoleInput, Prisma.ClubUncheckedCreateWithoutRoleInput>
  connectOrCreate?: Prisma.ClubCreateOrConnectWithoutRoleInput
  connect?: Prisma.ClubWhereUniqueInput
}

export type ClubUpdateOneRequiredWithoutRoleNestedInput = {
  create?: Prisma.XOR<Prisma.ClubCreateWithoutRoleInput, Prisma.ClubUncheckedCreateWithoutRoleInput>
  connectOrCreate?: Prisma.ClubCreateOrConnectWithoutRoleInput
  upsert?: Prisma.ClubUpsertWithoutRoleInput
  connect?: Prisma.ClubWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ClubUpdateToOneWithWhereWithoutRoleInput, Prisma.ClubUpdateWithoutRoleInput>, Prisma.ClubUncheckedUpdateWithoutRoleInput>
}

export type ClubCreateNestedOneWithoutClubAdminInput = {
  create?: Prisma.XOR<Prisma.ClubCreateWithoutClubAdminInput, Prisma.ClubUncheckedCreateWithoutClubAdminInput>
  connectOrCreate?: Prisma.ClubCreateOrConnectWithoutClubAdminInput
  connect?: Prisma.ClubWhereUniqueInput
}

export type ClubUpdateOneRequiredWithoutClubAdminNestedInput = {
  create?: Prisma.XOR<Prisma.ClubCreateWithoutClubAdminInput, Prisma.ClubUncheckedCreateWithoutClubAdminInput>
  connectOrCreate?: Prisma.ClubCreateOrConnectWithoutClubAdminInput
  upsert?: Prisma.ClubUpsertWithoutClubAdminInput
  connect?: Prisma.ClubWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ClubUpdateToOneWithWhereWithoutClubAdminInput, Prisma.ClubUpdateWithoutClubAdminInput>, Prisma.ClubUncheckedUpdateWithoutClubAdminInput>
}

export type ClubCreateNestedOneWithoutEventsInput = {
  create?: Prisma.XOR<Prisma.ClubCreateWithoutEventsInput, Prisma.ClubUncheckedCreateWithoutEventsInput>
  connectOrCreate?: Prisma.ClubCreateOrConnectWithoutEventsInput
  connect?: Prisma.ClubWhereUniqueInput
}

export type ClubUpdateOneRequiredWithoutEventsNestedInput = {
  create?: Prisma.XOR<Prisma.ClubCreateWithoutEventsInput, Prisma.ClubUncheckedCreateWithoutEventsInput>
  connectOrCreate?: Prisma.ClubCreateOrConnectWithoutEventsInput
  upsert?: Prisma.ClubUpsertWithoutEventsInput
  connect?: Prisma.ClubWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ClubUpdateToOneWithWhereWithoutEventsInput, Prisma.ClubUpdateWithoutEventsInput>, Prisma.ClubUncheckedUpdateWithoutEventsInput>
}

export type ClubCreateWithoutCollegeInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  category: string
  onHold?: boolean
  clubAdmin?: Prisma.clubAdminCreateNestedOneWithoutClubInput
  students?: Prisma.StudentInClubCreateNestedManyWithoutClubInput
  coordinator?: Prisma.FacultyCreateNestedOneWithoutClubInput
  role?: Prisma.RoleInClubCreateNestedManyWithoutClubInput
  events?: Prisma.EventCreateNestedManyWithoutClubInput
}

export type ClubUncheckedCreateWithoutCollegeInput = {
  id?: string
  name: string
  description?: string | null
  cordinatorId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  category: string
  onHold?: boolean
  clubAdmin?: Prisma.clubAdminUncheckedCreateNestedOneWithoutClubInput
  students?: Prisma.StudentInClubUncheckedCreateNestedManyWithoutClubInput
  role?: Prisma.RoleInClubUncheckedCreateNestedManyWithoutClubInput
  events?: Prisma.EventUncheckedCreateNestedManyWithoutClubInput
}

export type ClubCreateOrConnectWithoutCollegeInput = {
  where: Prisma.ClubWhereUniqueInput
  create: Prisma.XOR<Prisma.ClubCreateWithoutCollegeInput, Prisma.ClubUncheckedCreateWithoutCollegeInput>
}

export type ClubCreateManyCollegeInputEnvelope = {
  data: Prisma.ClubCreateManyCollegeInput | Prisma.ClubCreateManyCollegeInput[]
  skipDuplicates?: boolean
}

export type ClubUpsertWithWhereUniqueWithoutCollegeInput = {
  where: Prisma.ClubWhereUniqueInput
  update: Prisma.XOR<Prisma.ClubUpdateWithoutCollegeInput, Prisma.ClubUncheckedUpdateWithoutCollegeInput>
  create: Prisma.XOR<Prisma.ClubCreateWithoutCollegeInput, Prisma.ClubUncheckedCreateWithoutCollegeInput>
}

export type ClubUpdateWithWhereUniqueWithoutCollegeInput = {
  where: Prisma.ClubWhereUniqueInput
  data: Prisma.XOR<Prisma.ClubUpdateWithoutCollegeInput, Prisma.ClubUncheckedUpdateWithoutCollegeInput>
}

export type ClubUpdateManyWithWhereWithoutCollegeInput = {
  where: Prisma.ClubScalarWhereInput
  data: Prisma.XOR<Prisma.ClubUpdateManyMutationInput, Prisma.ClubUncheckedUpdateManyWithoutCollegeInput>
}

export type ClubScalarWhereInput = {
  AND?: Prisma.ClubScalarWhereInput | Prisma.ClubScalarWhereInput[]
  OR?: Prisma.ClubScalarWhereInput[]
  NOT?: Prisma.ClubScalarWhereInput | Prisma.ClubScalarWhereInput[]
  id?: Prisma.StringFilter<"Club"> | string
  name?: Prisma.StringFilter<"Club"> | string
  collegeId?: Prisma.StringFilter<"Club"> | string
  description?: Prisma.StringNullableFilter<"Club"> | string | null
  cordinatorId?: Prisma.StringNullableFilter<"Club"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Club"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Club"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Club"> | Date | string | null
  category?: Prisma.StringFilter<"Club"> | string
  onHold?: Prisma.BoolFilter<"Club"> | boolean
}

export type ClubCreateWithoutStudentsInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  category: string
  onHold?: boolean
  clubAdmin?: Prisma.clubAdminCreateNestedOneWithoutClubInput
  college: Prisma.CollegeCreateNestedOneWithoutClubsInput
  coordinator?: Prisma.FacultyCreateNestedOneWithoutClubInput
  role?: Prisma.RoleInClubCreateNestedManyWithoutClubInput
  events?: Prisma.EventCreateNestedManyWithoutClubInput
}

export type ClubUncheckedCreateWithoutStudentsInput = {
  id?: string
  name: string
  collegeId: string
  description?: string | null
  cordinatorId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  category: string
  onHold?: boolean
  clubAdmin?: Prisma.clubAdminUncheckedCreateNestedOneWithoutClubInput
  role?: Prisma.RoleInClubUncheckedCreateNestedManyWithoutClubInput
  events?: Prisma.EventUncheckedCreateNestedManyWithoutClubInput
}

export type ClubCreateOrConnectWithoutStudentsInput = {
  where: Prisma.ClubWhereUniqueInput
  create: Prisma.XOR<Prisma.ClubCreateWithoutStudentsInput, Prisma.ClubUncheckedCreateWithoutStudentsInput>
}

export type ClubUpsertWithoutStudentsInput = {
  update: Prisma.XOR<Prisma.ClubUpdateWithoutStudentsInput, Prisma.ClubUncheckedUpdateWithoutStudentsInput>
  create: Prisma.XOR<Prisma.ClubCreateWithoutStudentsInput, Prisma.ClubUncheckedCreateWithoutStudentsInput>
  where?: Prisma.ClubWhereInput
}

export type ClubUpdateToOneWithWhereWithoutStudentsInput = {
  where?: Prisma.ClubWhereInput
  data: Prisma.XOR<Prisma.ClubUpdateWithoutStudentsInput, Prisma.ClubUncheckedUpdateWithoutStudentsInput>
}

export type ClubUpdateWithoutStudentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  onHold?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clubAdmin?: Prisma.clubAdminUpdateOneWithoutClubNestedInput
  college?: Prisma.CollegeUpdateOneRequiredWithoutClubsNestedInput
  coordinator?: Prisma.FacultyUpdateOneWithoutClubNestedInput
  role?: Prisma.RoleInClubUpdateManyWithoutClubNestedInput
  events?: Prisma.EventUpdateManyWithoutClubNestedInput
}

export type ClubUncheckedUpdateWithoutStudentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  collegeId?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cordinatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  onHold?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clubAdmin?: Prisma.clubAdminUncheckedUpdateOneWithoutClubNestedInput
  role?: Prisma.RoleInClubUncheckedUpdateManyWithoutClubNestedInput
  events?: Prisma.EventUncheckedUpdateManyWithoutClubNestedInput
}

export type ClubCreateWithoutCoordinatorInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  category: string
  onHold?: boolean
  clubAdmin?: Prisma.clubAdminCreateNestedOneWithoutClubInput
  college: Prisma.CollegeCreateNestedOneWithoutClubsInput
  students?: Prisma.StudentInClubCreateNestedManyWithoutClubInput
  role?: Prisma.RoleInClubCreateNestedManyWithoutClubInput
  events?: Prisma.EventCreateNestedManyWithoutClubInput
}

export type ClubUncheckedCreateWithoutCoordinatorInput = {
  id?: string
  name: string
  collegeId: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  category: string
  onHold?: boolean
  clubAdmin?: Prisma.clubAdminUncheckedCreateNestedOneWithoutClubInput
  students?: Prisma.StudentInClubUncheckedCreateNestedManyWithoutClubInput
  role?: Prisma.RoleInClubUncheckedCreateNestedManyWithoutClubInput
  events?: Prisma.EventUncheckedCreateNestedManyWithoutClubInput
}

export type ClubCreateOrConnectWithoutCoordinatorInput = {
  where: Prisma.ClubWhereUniqueInput
  create: Prisma.XOR<Prisma.ClubCreateWithoutCoordinatorInput, Prisma.ClubUncheckedCreateWithoutCoordinatorInput>
}

export type ClubCreateManyCoordinatorInputEnvelope = {
  data: Prisma.ClubCreateManyCoordinatorInput | Prisma.ClubCreateManyCoordinatorInput[]
  skipDuplicates?: boolean
}

export type ClubUpsertWithWhereUniqueWithoutCoordinatorInput = {
  where: Prisma.ClubWhereUniqueInput
  update: Prisma.XOR<Prisma.ClubUpdateWithoutCoordinatorInput, Prisma.ClubUncheckedUpdateWithoutCoordinatorInput>
  create: Prisma.XOR<Prisma.ClubCreateWithoutCoordinatorInput, Prisma.ClubUncheckedCreateWithoutCoordinatorInput>
}

export type ClubUpdateWithWhereUniqueWithoutCoordinatorInput = {
  where: Prisma.ClubWhereUniqueInput
  data: Prisma.XOR<Prisma.ClubUpdateWithoutCoordinatorInput, Prisma.ClubUncheckedUpdateWithoutCoordinatorInput>
}

export type ClubUpdateManyWithWhereWithoutCoordinatorInput = {
  where: Prisma.ClubScalarWhereInput
  data: Prisma.XOR<Prisma.ClubUpdateManyMutationInput, Prisma.ClubUncheckedUpdateManyWithoutCoordinatorInput>
}

export type ClubCreateWithoutRoleInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  category: string
  onHold?: boolean
  clubAdmin?: Prisma.clubAdminCreateNestedOneWithoutClubInput
  college: Prisma.CollegeCreateNestedOneWithoutClubsInput
  students?: Prisma.StudentInClubCreateNestedManyWithoutClubInput
  coordinator?: Prisma.FacultyCreateNestedOneWithoutClubInput
  events?: Prisma.EventCreateNestedManyWithoutClubInput
}

export type ClubUncheckedCreateWithoutRoleInput = {
  id?: string
  name: string
  collegeId: string
  description?: string | null
  cordinatorId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  category: string
  onHold?: boolean
  clubAdmin?: Prisma.clubAdminUncheckedCreateNestedOneWithoutClubInput
  students?: Prisma.StudentInClubUncheckedCreateNestedManyWithoutClubInput
  events?: Prisma.EventUncheckedCreateNestedManyWithoutClubInput
}

export type ClubCreateOrConnectWithoutRoleInput = {
  where: Prisma.ClubWhereUniqueInput
  create: Prisma.XOR<Prisma.ClubCreateWithoutRoleInput, Prisma.ClubUncheckedCreateWithoutRoleInput>
}

export type ClubUpsertWithoutRoleInput = {
  update: Prisma.XOR<Prisma.ClubUpdateWithoutRoleInput, Prisma.ClubUncheckedUpdateWithoutRoleInput>
  create: Prisma.XOR<Prisma.ClubCreateWithoutRoleInput, Prisma.ClubUncheckedCreateWithoutRoleInput>
  where?: Prisma.ClubWhereInput
}

export type ClubUpdateToOneWithWhereWithoutRoleInput = {
  where?: Prisma.ClubWhereInput
  data: Prisma.XOR<Prisma.ClubUpdateWithoutRoleInput, Prisma.ClubUncheckedUpdateWithoutRoleInput>
}

export type ClubUpdateWithoutRoleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  onHold?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clubAdmin?: Prisma.clubAdminUpdateOneWithoutClubNestedInput
  college?: Prisma.CollegeUpdateOneRequiredWithoutClubsNestedInput
  students?: Prisma.StudentInClubUpdateManyWithoutClubNestedInput
  coordinator?: Prisma.FacultyUpdateOneWithoutClubNestedInput
  events?: Prisma.EventUpdateManyWithoutClubNestedInput
}

export type ClubUncheckedUpdateWithoutRoleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  collegeId?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cordinatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  onHold?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clubAdmin?: Prisma.clubAdminUncheckedUpdateOneWithoutClubNestedInput
  students?: Prisma.StudentInClubUncheckedUpdateManyWithoutClubNestedInput
  events?: Prisma.EventUncheckedUpdateManyWithoutClubNestedInput
}

export type ClubCreateWithoutClubAdminInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  category: string
  onHold?: boolean
  college: Prisma.CollegeCreateNestedOneWithoutClubsInput
  students?: Prisma.StudentInClubCreateNestedManyWithoutClubInput
  coordinator?: Prisma.FacultyCreateNestedOneWithoutClubInput
  role?: Prisma.RoleInClubCreateNestedManyWithoutClubInput
  events?: Prisma.EventCreateNestedManyWithoutClubInput
}

export type ClubUncheckedCreateWithoutClubAdminInput = {
  id?: string
  name: string
  collegeId: string
  description?: string | null
  cordinatorId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  category: string
  onHold?: boolean
  students?: Prisma.StudentInClubUncheckedCreateNestedManyWithoutClubInput
  role?: Prisma.RoleInClubUncheckedCreateNestedManyWithoutClubInput
  events?: Prisma.EventUncheckedCreateNestedManyWithoutClubInput
}

export type ClubCreateOrConnectWithoutClubAdminInput = {
  where: Prisma.ClubWhereUniqueInput
  create: Prisma.XOR<Prisma.ClubCreateWithoutClubAdminInput, Prisma.ClubUncheckedCreateWithoutClubAdminInput>
}

export type ClubUpsertWithoutClubAdminInput = {
  update: Prisma.XOR<Prisma.ClubUpdateWithoutClubAdminInput, Prisma.ClubUncheckedUpdateWithoutClubAdminInput>
  create: Prisma.XOR<Prisma.ClubCreateWithoutClubAdminInput, Prisma.ClubUncheckedCreateWithoutClubAdminInput>
  where?: Prisma.ClubWhereInput
}

export type ClubUpdateToOneWithWhereWithoutClubAdminInput = {
  where?: Prisma.ClubWhereInput
  data: Prisma.XOR<Prisma.ClubUpdateWithoutClubAdminInput, Prisma.ClubUncheckedUpdateWithoutClubAdminInput>
}

export type ClubUpdateWithoutClubAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  onHold?: Prisma.BoolFieldUpdateOperationsInput | boolean
  college?: Prisma.CollegeUpdateOneRequiredWithoutClubsNestedInput
  students?: Prisma.StudentInClubUpdateManyWithoutClubNestedInput
  coordinator?: Prisma.FacultyUpdateOneWithoutClubNestedInput
  role?: Prisma.RoleInClubUpdateManyWithoutClubNestedInput
  events?: Prisma.EventUpdateManyWithoutClubNestedInput
}

export type ClubUncheckedUpdateWithoutClubAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  collegeId?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cordinatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  onHold?: Prisma.BoolFieldUpdateOperationsInput | boolean
  students?: Prisma.StudentInClubUncheckedUpdateManyWithoutClubNestedInput
  role?: Prisma.RoleInClubUncheckedUpdateManyWithoutClubNestedInput
  events?: Prisma.EventUncheckedUpdateManyWithoutClubNestedInput
}

export type ClubCreateWithoutEventsInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  category: string
  onHold?: boolean
  clubAdmin?: Prisma.clubAdminCreateNestedOneWithoutClubInput
  college: Prisma.CollegeCreateNestedOneWithoutClubsInput
  students?: Prisma.StudentInClubCreateNestedManyWithoutClubInput
  coordinator?: Prisma.FacultyCreateNestedOneWithoutClubInput
  role?: Prisma.RoleInClubCreateNestedManyWithoutClubInput
}

export type ClubUncheckedCreateWithoutEventsInput = {
  id?: string
  name: string
  collegeId: string
  description?: string | null
  cordinatorId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  category: string
  onHold?: boolean
  clubAdmin?: Prisma.clubAdminUncheckedCreateNestedOneWithoutClubInput
  students?: Prisma.StudentInClubUncheckedCreateNestedManyWithoutClubInput
  role?: Prisma.RoleInClubUncheckedCreateNestedManyWithoutClubInput
}

export type ClubCreateOrConnectWithoutEventsInput = {
  where: Prisma.ClubWhereUniqueInput
  create: Prisma.XOR<Prisma.ClubCreateWithoutEventsInput, Prisma.ClubUncheckedCreateWithoutEventsInput>
}

export type ClubUpsertWithoutEventsInput = {
  update: Prisma.XOR<Prisma.ClubUpdateWithoutEventsInput, Prisma.ClubUncheckedUpdateWithoutEventsInput>
  create: Prisma.XOR<Prisma.ClubCreateWithoutEventsInput, Prisma.ClubUncheckedCreateWithoutEventsInput>
  where?: Prisma.ClubWhereInput
}

export type ClubUpdateToOneWithWhereWithoutEventsInput = {
  where?: Prisma.ClubWhereInput
  data: Prisma.XOR<Prisma.ClubUpdateWithoutEventsInput, Prisma.ClubUncheckedUpdateWithoutEventsInput>
}

export type ClubUpdateWithoutEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  onHold?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clubAdmin?: Prisma.clubAdminUpdateOneWithoutClubNestedInput
  college?: Prisma.CollegeUpdateOneRequiredWithoutClubsNestedInput
  students?: Prisma.StudentInClubUpdateManyWithoutClubNestedInput
  coordinator?: Prisma.FacultyUpdateOneWithoutClubNestedInput
  role?: Prisma.RoleInClubUpdateManyWithoutClubNestedInput
}

export type ClubUncheckedUpdateWithoutEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  collegeId?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cordinatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  onHold?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clubAdmin?: Prisma.clubAdminUncheckedUpdateOneWithoutClubNestedInput
  students?: Prisma.StudentInClubUncheckedUpdateManyWithoutClubNestedInput
  role?: Prisma.RoleInClubUncheckedUpdateManyWithoutClubNestedInput
}

export type ClubCreateManyCollegeInput = {
  id?: string
  name: string
  description?: string | null
  cordinatorId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  category: string
  onHold?: boolean
}

export type ClubUpdateWithoutCollegeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  onHold?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clubAdmin?: Prisma.clubAdminUpdateOneWithoutClubNestedInput
  students?: Prisma.StudentInClubUpdateManyWithoutClubNestedInput
  coordinator?: Prisma.FacultyUpdateOneWithoutClubNestedInput
  role?: Prisma.RoleInClubUpdateManyWithoutClubNestedInput
  events?: Prisma.EventUpdateManyWithoutClubNestedInput
}

export type ClubUncheckedUpdateWithoutCollegeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cordinatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  onHold?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clubAdmin?: Prisma.clubAdminUncheckedUpdateOneWithoutClubNestedInput
  students?: Prisma.StudentInClubUncheckedUpdateManyWithoutClubNestedInput
  role?: Prisma.RoleInClubUncheckedUpdateManyWithoutClubNestedInput
  events?: Prisma.EventUncheckedUpdateManyWithoutClubNestedInput
}

export type ClubUncheckedUpdateManyWithoutCollegeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cordinatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  onHold?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ClubCreateManyCoordinatorInput = {
  id?: string
  name: string
  collegeId: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  category: string
  onHold?: boolean
}

export type ClubUpdateWithoutCoordinatorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  onHold?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clubAdmin?: Prisma.clubAdminUpdateOneWithoutClubNestedInput
  college?: Prisma.CollegeUpdateOneRequiredWithoutClubsNestedInput
  students?: Prisma.StudentInClubUpdateManyWithoutClubNestedInput
  role?: Prisma.RoleInClubUpdateManyWithoutClubNestedInput
  events?: Prisma.EventUpdateManyWithoutClubNestedInput
}

export type ClubUncheckedUpdateWithoutCoordinatorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  collegeId?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  onHold?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clubAdmin?: Prisma.clubAdminUncheckedUpdateOneWithoutClubNestedInput
  students?: Prisma.StudentInClubUncheckedUpdateManyWithoutClubNestedInput
  role?: Prisma.RoleInClubUncheckedUpdateManyWithoutClubNestedInput
  events?: Prisma.EventUncheckedUpdateManyWithoutClubNestedInput
}

export type ClubUncheckedUpdateManyWithoutCoordinatorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  collegeId?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  onHold?: Prisma.BoolFieldUpdateOperationsInput | boolean
}


/**
 * Count Type ClubCountOutputType
 */

export type ClubCountOutputType = {
  students: number
  role: number
  events: number
}

export type ClubCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  students?: boolean | ClubCountOutputTypeCountStudentsArgs
  role?: boolean | ClubCountOutputTypeCountRoleArgs
  events?: boolean | ClubCountOutputTypeCountEventsArgs
}

/**
 * ClubCountOutputType without action
 */
export type ClubCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClubCountOutputType
   */
  select?: Prisma.ClubCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ClubCountOutputType without action
 */
export type ClubCountOutputTypeCountStudentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StudentInClubWhereInput
}

/**
 * ClubCountOutputType without action
 */
export type ClubCountOutputTypeCountRoleArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RoleInClubWhereInput
}

/**
 * ClubCountOutputType without action
 */
export type ClubCountOutputTypeCountEventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventWhereInput
}


export type ClubSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  collegeId?: boolean
  description?: boolean
  cordinatorId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  category?: boolean
  onHold?: boolean
  clubAdmin?: boolean | Prisma.Club$clubAdminArgs<ExtArgs>
  college?: boolean | Prisma.CollegeDefaultArgs<ExtArgs>
  students?: boolean | Prisma.Club$studentsArgs<ExtArgs>
  coordinator?: boolean | Prisma.Club$coordinatorArgs<ExtArgs>
  role?: boolean | Prisma.Club$roleArgs<ExtArgs>
  events?: boolean | Prisma.Club$eventsArgs<ExtArgs>
  _count?: boolean | Prisma.ClubCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["club"]>

export type ClubSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  collegeId?: boolean
  description?: boolean
  cordinatorId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  category?: boolean
  onHold?: boolean
  college?: boolean | Prisma.CollegeDefaultArgs<ExtArgs>
  coordinator?: boolean | Prisma.Club$coordinatorArgs<ExtArgs>
}, ExtArgs["result"]["club"]>

export type ClubSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  collegeId?: boolean
  description?: boolean
  cordinatorId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  category?: boolean
  onHold?: boolean
  college?: boolean | Prisma.CollegeDefaultArgs<ExtArgs>
  coordinator?: boolean | Prisma.Club$coordinatorArgs<ExtArgs>
}, ExtArgs["result"]["club"]>

export type ClubSelectScalar = {
  id?: boolean
  name?: boolean
  collegeId?: boolean
  description?: boolean
  cordinatorId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  category?: boolean
  onHold?: boolean
}

export type ClubOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "collegeId" | "description" | "cordinatorId" | "createdAt" | "updatedAt" | "deletedAt" | "category" | "onHold", ExtArgs["result"]["club"]>
export type ClubInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  clubAdmin?: boolean | Prisma.Club$clubAdminArgs<ExtArgs>
  college?: boolean | Prisma.CollegeDefaultArgs<ExtArgs>
  students?: boolean | Prisma.Club$studentsArgs<ExtArgs>
  coordinator?: boolean | Prisma.Club$coordinatorArgs<ExtArgs>
  role?: boolean | Prisma.Club$roleArgs<ExtArgs>
  events?: boolean | Prisma.Club$eventsArgs<ExtArgs>
  _count?: boolean | Prisma.ClubCountOutputTypeDefaultArgs<ExtArgs>
}
export type ClubIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  college?: boolean | Prisma.CollegeDefaultArgs<ExtArgs>
  coordinator?: boolean | Prisma.Club$coordinatorArgs<ExtArgs>
}
export type ClubIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  college?: boolean | Prisma.CollegeDefaultArgs<ExtArgs>
  coordinator?: boolean | Prisma.Club$coordinatorArgs<ExtArgs>
}

export type $ClubPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Club"
  objects: {
    clubAdmin: Prisma.$clubAdminPayload<ExtArgs> | null
    college: Prisma.$CollegePayload<ExtArgs>
    students: Prisma.$StudentInClubPayload<ExtArgs>[]
    coordinator: Prisma.$FacultyPayload<ExtArgs> | null
    role: Prisma.$RoleInClubPayload<ExtArgs>[]
    events: Prisma.$EventPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    collegeId: string
    description: string | null
    cordinatorId: string | null
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
    category: string
    onHold: boolean
  }, ExtArgs["result"]["club"]>
  composites: {}
}

export type ClubGetPayload<S extends boolean | null | undefined | ClubDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ClubPayload, S>

export type ClubCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ClubFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ClubCountAggregateInputType | true
  }

export interface ClubDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Club'], meta: { name: 'Club' } }
  /**
   * Find zero or one Club that matches the filter.
   * @param {ClubFindUniqueArgs} args - Arguments to find a Club
   * @example
   * // Get one Club
   * const club = await prisma.club.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ClubFindUniqueArgs>(args: Prisma.SelectSubset<T, ClubFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ClubClient<runtime.Types.Result.GetResult<Prisma.$ClubPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Club that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ClubFindUniqueOrThrowArgs} args - Arguments to find a Club
   * @example
   * // Get one Club
   * const club = await prisma.club.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ClubFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ClubFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClubClient<runtime.Types.Result.GetResult<Prisma.$ClubPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Club that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubFindFirstArgs} args - Arguments to find a Club
   * @example
   * // Get one Club
   * const club = await prisma.club.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ClubFindFirstArgs>(args?: Prisma.SelectSubset<T, ClubFindFirstArgs<ExtArgs>>): Prisma.Prisma__ClubClient<runtime.Types.Result.GetResult<Prisma.$ClubPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Club that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubFindFirstOrThrowArgs} args - Arguments to find a Club
   * @example
   * // Get one Club
   * const club = await prisma.club.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ClubFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ClubFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClubClient<runtime.Types.Result.GetResult<Prisma.$ClubPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Clubs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Clubs
   * const clubs = await prisma.club.findMany()
   * 
   * // Get first 10 Clubs
   * const clubs = await prisma.club.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const clubWithIdOnly = await prisma.club.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ClubFindManyArgs>(args?: Prisma.SelectSubset<T, ClubFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClubPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Club.
   * @param {ClubCreateArgs} args - Arguments to create a Club.
   * @example
   * // Create one Club
   * const Club = await prisma.club.create({
   *   data: {
   *     // ... data to create a Club
   *   }
   * })
   * 
   */
  create<T extends ClubCreateArgs>(args: Prisma.SelectSubset<T, ClubCreateArgs<ExtArgs>>): Prisma.Prisma__ClubClient<runtime.Types.Result.GetResult<Prisma.$ClubPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Clubs.
   * @param {ClubCreateManyArgs} args - Arguments to create many Clubs.
   * @example
   * // Create many Clubs
   * const club = await prisma.club.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ClubCreateManyArgs>(args?: Prisma.SelectSubset<T, ClubCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Clubs and returns the data saved in the database.
   * @param {ClubCreateManyAndReturnArgs} args - Arguments to create many Clubs.
   * @example
   * // Create many Clubs
   * const club = await prisma.club.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Clubs and only return the `id`
   * const clubWithIdOnly = await prisma.club.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ClubCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ClubCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClubPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Club.
   * @param {ClubDeleteArgs} args - Arguments to delete one Club.
   * @example
   * // Delete one Club
   * const Club = await prisma.club.delete({
   *   where: {
   *     // ... filter to delete one Club
   *   }
   * })
   * 
   */
  delete<T extends ClubDeleteArgs>(args: Prisma.SelectSubset<T, ClubDeleteArgs<ExtArgs>>): Prisma.Prisma__ClubClient<runtime.Types.Result.GetResult<Prisma.$ClubPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Club.
   * @param {ClubUpdateArgs} args - Arguments to update one Club.
   * @example
   * // Update one Club
   * const club = await prisma.club.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ClubUpdateArgs>(args: Prisma.SelectSubset<T, ClubUpdateArgs<ExtArgs>>): Prisma.Prisma__ClubClient<runtime.Types.Result.GetResult<Prisma.$ClubPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Clubs.
   * @param {ClubDeleteManyArgs} args - Arguments to filter Clubs to delete.
   * @example
   * // Delete a few Clubs
   * const { count } = await prisma.club.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ClubDeleteManyArgs>(args?: Prisma.SelectSubset<T, ClubDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Clubs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Clubs
   * const club = await prisma.club.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ClubUpdateManyArgs>(args: Prisma.SelectSubset<T, ClubUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Clubs and returns the data updated in the database.
   * @param {ClubUpdateManyAndReturnArgs} args - Arguments to update many Clubs.
   * @example
   * // Update many Clubs
   * const club = await prisma.club.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Clubs and only return the `id`
   * const clubWithIdOnly = await prisma.club.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ClubUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ClubUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClubPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Club.
   * @param {ClubUpsertArgs} args - Arguments to update or create a Club.
   * @example
   * // Update or create a Club
   * const club = await prisma.club.upsert({
   *   create: {
   *     // ... data to create a Club
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Club we want to update
   *   }
   * })
   */
  upsert<T extends ClubUpsertArgs>(args: Prisma.SelectSubset<T, ClubUpsertArgs<ExtArgs>>): Prisma.Prisma__ClubClient<runtime.Types.Result.GetResult<Prisma.$ClubPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Clubs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubCountArgs} args - Arguments to filter Clubs to count.
   * @example
   * // Count the number of Clubs
   * const count = await prisma.club.count({
   *   where: {
   *     // ... the filter for the Clubs we want to count
   *   }
   * })
  **/
  count<T extends ClubCountArgs>(
    args?: Prisma.Subset<T, ClubCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ClubCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Club.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ClubAggregateArgs>(args: Prisma.Subset<T, ClubAggregateArgs>): Prisma.PrismaPromise<GetClubAggregateType<T>>

  /**
   * Group by Club.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ClubGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ClubGroupByArgs['orderBy'] }
      : { orderBy?: ClubGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ClubGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetClubGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Club model
 */
readonly fields: ClubFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Club.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ClubClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  clubAdmin<T extends Prisma.Club$clubAdminArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Club$clubAdminArgs<ExtArgs>>): Prisma.Prisma__clubAdminClient<runtime.Types.Result.GetResult<Prisma.$clubAdminPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  college<T extends Prisma.CollegeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CollegeDefaultArgs<ExtArgs>>): Prisma.Prisma__CollegeClient<runtime.Types.Result.GetResult<Prisma.$CollegePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  students<T extends Prisma.Club$studentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Club$studentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudentInClubPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  coordinator<T extends Prisma.Club$coordinatorArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Club$coordinatorArgs<ExtArgs>>): Prisma.Prisma__FacultyClient<runtime.Types.Result.GetResult<Prisma.$FacultyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  role<T extends Prisma.Club$roleArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Club$roleArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RoleInClubPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  events<T extends Prisma.Club$eventsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Club$eventsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Club model
 */
export interface ClubFieldRefs {
  readonly id: Prisma.FieldRef<"Club", 'String'>
  readonly name: Prisma.FieldRef<"Club", 'String'>
  readonly collegeId: Prisma.FieldRef<"Club", 'String'>
  readonly description: Prisma.FieldRef<"Club", 'String'>
  readonly cordinatorId: Prisma.FieldRef<"Club", 'String'>
  readonly createdAt: Prisma.FieldRef<"Club", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Club", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"Club", 'DateTime'>
  readonly category: Prisma.FieldRef<"Club", 'String'>
  readonly onHold: Prisma.FieldRef<"Club", 'Boolean'>
}
    

// Custom InputTypes
/**
 * Club findUnique
 */
export type ClubFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Club
   */
  select?: Prisma.ClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Club
   */
  omit?: Prisma.ClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubInclude<ExtArgs> | null
  /**
   * Filter, which Club to fetch.
   */
  where: Prisma.ClubWhereUniqueInput
}

/**
 * Club findUniqueOrThrow
 */
export type ClubFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Club
   */
  select?: Prisma.ClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Club
   */
  omit?: Prisma.ClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubInclude<ExtArgs> | null
  /**
   * Filter, which Club to fetch.
   */
  where: Prisma.ClubWhereUniqueInput
}

/**
 * Club findFirst
 */
export type ClubFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Club
   */
  select?: Prisma.ClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Club
   */
  omit?: Prisma.ClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubInclude<ExtArgs> | null
  /**
   * Filter, which Club to fetch.
   */
  where?: Prisma.ClubWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clubs to fetch.
   */
  orderBy?: Prisma.ClubOrderByWithRelationInput | Prisma.ClubOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Clubs.
   */
  cursor?: Prisma.ClubWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clubs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clubs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Clubs.
   */
  distinct?: Prisma.ClubScalarFieldEnum | Prisma.ClubScalarFieldEnum[]
}

/**
 * Club findFirstOrThrow
 */
export type ClubFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Club
   */
  select?: Prisma.ClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Club
   */
  omit?: Prisma.ClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubInclude<ExtArgs> | null
  /**
   * Filter, which Club to fetch.
   */
  where?: Prisma.ClubWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clubs to fetch.
   */
  orderBy?: Prisma.ClubOrderByWithRelationInput | Prisma.ClubOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Clubs.
   */
  cursor?: Prisma.ClubWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clubs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clubs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Clubs.
   */
  distinct?: Prisma.ClubScalarFieldEnum | Prisma.ClubScalarFieldEnum[]
}

/**
 * Club findMany
 */
export type ClubFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Club
   */
  select?: Prisma.ClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Club
   */
  omit?: Prisma.ClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubInclude<ExtArgs> | null
  /**
   * Filter, which Clubs to fetch.
   */
  where?: Prisma.ClubWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clubs to fetch.
   */
  orderBy?: Prisma.ClubOrderByWithRelationInput | Prisma.ClubOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Clubs.
   */
  cursor?: Prisma.ClubWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clubs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clubs.
   */
  skip?: number
  distinct?: Prisma.ClubScalarFieldEnum | Prisma.ClubScalarFieldEnum[]
}

/**
 * Club create
 */
export type ClubCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Club
   */
  select?: Prisma.ClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Club
   */
  omit?: Prisma.ClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubInclude<ExtArgs> | null
  /**
   * The data needed to create a Club.
   */
  data: Prisma.XOR<Prisma.ClubCreateInput, Prisma.ClubUncheckedCreateInput>
}

/**
 * Club createMany
 */
export type ClubCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Clubs.
   */
  data: Prisma.ClubCreateManyInput | Prisma.ClubCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Club createManyAndReturn
 */
export type ClubCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Club
   */
  select?: Prisma.ClubSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Club
   */
  omit?: Prisma.ClubOmit<ExtArgs> | null
  /**
   * The data used to create many Clubs.
   */
  data: Prisma.ClubCreateManyInput | Prisma.ClubCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Club update
 */
export type ClubUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Club
   */
  select?: Prisma.ClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Club
   */
  omit?: Prisma.ClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubInclude<ExtArgs> | null
  /**
   * The data needed to update a Club.
   */
  data: Prisma.XOR<Prisma.ClubUpdateInput, Prisma.ClubUncheckedUpdateInput>
  /**
   * Choose, which Club to update.
   */
  where: Prisma.ClubWhereUniqueInput
}

/**
 * Club updateMany
 */
export type ClubUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Clubs.
   */
  data: Prisma.XOR<Prisma.ClubUpdateManyMutationInput, Prisma.ClubUncheckedUpdateManyInput>
  /**
   * Filter which Clubs to update
   */
  where?: Prisma.ClubWhereInput
  /**
   * Limit how many Clubs to update.
   */
  limit?: number
}

/**
 * Club updateManyAndReturn
 */
export type ClubUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Club
   */
  select?: Prisma.ClubSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Club
   */
  omit?: Prisma.ClubOmit<ExtArgs> | null
  /**
   * The data used to update Clubs.
   */
  data: Prisma.XOR<Prisma.ClubUpdateManyMutationInput, Prisma.ClubUncheckedUpdateManyInput>
  /**
   * Filter which Clubs to update
   */
  where?: Prisma.ClubWhereInput
  /**
   * Limit how many Clubs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Club upsert
 */
export type ClubUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Club
   */
  select?: Prisma.ClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Club
   */
  omit?: Prisma.ClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubInclude<ExtArgs> | null
  /**
   * The filter to search for the Club to update in case it exists.
   */
  where: Prisma.ClubWhereUniqueInput
  /**
   * In case the Club found by the `where` argument doesn't exist, create a new Club with this data.
   */
  create: Prisma.XOR<Prisma.ClubCreateInput, Prisma.ClubUncheckedCreateInput>
  /**
   * In case the Club was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ClubUpdateInput, Prisma.ClubUncheckedUpdateInput>
}

/**
 * Club delete
 */
export type ClubDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Club
   */
  select?: Prisma.ClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Club
   */
  omit?: Prisma.ClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubInclude<ExtArgs> | null
  /**
   * Filter which Club to delete.
   */
  where: Prisma.ClubWhereUniqueInput
}

/**
 * Club deleteMany
 */
export type ClubDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Clubs to delete
   */
  where?: Prisma.ClubWhereInput
  /**
   * Limit how many Clubs to delete.
   */
  limit?: number
}

/**
 * Club.clubAdmin
 */
export type Club$clubAdminArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the clubAdmin
   */
  select?: Prisma.clubAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the clubAdmin
   */
  omit?: Prisma.clubAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.clubAdminInclude<ExtArgs> | null
  where?: Prisma.clubAdminWhereInput
}

/**
 * Club.students
 */
export type Club$studentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentInClub
   */
  select?: Prisma.StudentInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentInClub
   */
  omit?: Prisma.StudentInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInClubInclude<ExtArgs> | null
  where?: Prisma.StudentInClubWhereInput
  orderBy?: Prisma.StudentInClubOrderByWithRelationInput | Prisma.StudentInClubOrderByWithRelationInput[]
  cursor?: Prisma.StudentInClubWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.StudentInClubScalarFieldEnum | Prisma.StudentInClubScalarFieldEnum[]
}

/**
 * Club.coordinator
 */
export type Club$coordinatorArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Faculty
   */
  select?: Prisma.FacultySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Faculty
   */
  omit?: Prisma.FacultyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FacultyInclude<ExtArgs> | null
  where?: Prisma.FacultyWhereInput
}

/**
 * Club.role
 */
export type Club$roleArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleInClub
   */
  select?: Prisma.RoleInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleInClub
   */
  omit?: Prisma.RoleInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoleInClubInclude<ExtArgs> | null
  where?: Prisma.RoleInClubWhereInput
  orderBy?: Prisma.RoleInClubOrderByWithRelationInput | Prisma.RoleInClubOrderByWithRelationInput[]
  cursor?: Prisma.RoleInClubWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RoleInClubScalarFieldEnum | Prisma.RoleInClubScalarFieldEnum[]
}

/**
 * Club.events
 */
export type Club$eventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Event
   */
  select?: Prisma.EventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Event
   */
  omit?: Prisma.EventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventInclude<ExtArgs> | null
  where?: Prisma.EventWhereInput
  orderBy?: Prisma.EventOrderByWithRelationInput | Prisma.EventOrderByWithRelationInput[]
  cursor?: Prisma.EventWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EventScalarFieldEnum | Prisma.EventScalarFieldEnum[]
}

/**
 * Club without action
 */
export type ClubDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Club
   */
  select?: Prisma.ClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Club
   */
  omit?: Prisma.ClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubInclude<ExtArgs> | null
}
