
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Registrations` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Registrations
 * 
 */
export type RegistrationsModel = runtime.Types.Result.DefaultSelection<Prisma.$RegistrationsPayload>

export type AggregateRegistrations = {
  _count: RegistrationsCountAggregateOutputType | null
  _min: RegistrationsMinAggregateOutputType | null
  _max: RegistrationsMaxAggregateOutputType | null
}

export type RegistrationsMinAggregateOutputType = {
  id: string | null
  studentId: string | null
  eventId: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type RegistrationsMaxAggregateOutputType = {
  id: string | null
  studentId: string | null
  eventId: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type RegistrationsCountAggregateOutputType = {
  id: number
  studentId: number
  eventId: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type RegistrationsMinAggregateInputType = {
  id?: true
  studentId?: true
  eventId?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type RegistrationsMaxAggregateInputType = {
  id?: true
  studentId?: true
  eventId?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type RegistrationsCountAggregateInputType = {
  id?: true
  studentId?: true
  eventId?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type RegistrationsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Registrations to aggregate.
   */
  where?: Prisma.RegistrationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Registrations to fetch.
   */
  orderBy?: Prisma.RegistrationsOrderByWithRelationInput | Prisma.RegistrationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RegistrationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Registrations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Registrations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Registrations
  **/
  _count?: true | RegistrationsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RegistrationsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RegistrationsMaxAggregateInputType
}

export type GetRegistrationsAggregateType<T extends RegistrationsAggregateArgs> = {
      [P in keyof T & keyof AggregateRegistrations]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRegistrations[P]>
    : Prisma.GetScalarType<T[P], AggregateRegistrations[P]>
}




export type RegistrationsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RegistrationsWhereInput
  orderBy?: Prisma.RegistrationsOrderByWithAggregationInput | Prisma.RegistrationsOrderByWithAggregationInput[]
  by: Prisma.RegistrationsScalarFieldEnum[] | Prisma.RegistrationsScalarFieldEnum
  having?: Prisma.RegistrationsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RegistrationsCountAggregateInputType | true
  _min?: RegistrationsMinAggregateInputType
  _max?: RegistrationsMaxAggregateInputType
}

export type RegistrationsGroupByOutputType = {
  id: string
  studentId: string
  eventId: string
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: RegistrationsCountAggregateOutputType | null
  _min: RegistrationsMinAggregateOutputType | null
  _max: RegistrationsMaxAggregateOutputType | null
}

type GetRegistrationsGroupByPayload<T extends RegistrationsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RegistrationsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RegistrationsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RegistrationsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RegistrationsGroupByOutputType[P]>
      }
    >
  >



export type RegistrationsWhereInput = {
  AND?: Prisma.RegistrationsWhereInput | Prisma.RegistrationsWhereInput[]
  OR?: Prisma.RegistrationsWhereInput[]
  NOT?: Prisma.RegistrationsWhereInput | Prisma.RegistrationsWhereInput[]
  id?: Prisma.StringFilter<"Registrations"> | string
  studentId?: Prisma.StringFilter<"Registrations"> | string
  eventId?: Prisma.StringFilter<"Registrations"> | string
  createdAt?: Prisma.DateTimeFilter<"Registrations"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Registrations"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Registrations"> | Date | string | null
  student?: Prisma.XOR<Prisma.StudentScalarRelationFilter, Prisma.StudentWhereInput>
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
}

export type RegistrationsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  student?: Prisma.StudentOrderByWithRelationInput
  event?: Prisma.EventOrderByWithRelationInput
}

export type RegistrationsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.RegistrationsWhereInput | Prisma.RegistrationsWhereInput[]
  OR?: Prisma.RegistrationsWhereInput[]
  NOT?: Prisma.RegistrationsWhereInput | Prisma.RegistrationsWhereInput[]
  studentId?: Prisma.StringFilter<"Registrations"> | string
  eventId?: Prisma.StringFilter<"Registrations"> | string
  createdAt?: Prisma.DateTimeFilter<"Registrations"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Registrations"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Registrations"> | Date | string | null
  student?: Prisma.XOR<Prisma.StudentScalarRelationFilter, Prisma.StudentWhereInput>
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
}, "id">

export type RegistrationsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.RegistrationsCountOrderByAggregateInput
  _max?: Prisma.RegistrationsMaxOrderByAggregateInput
  _min?: Prisma.RegistrationsMinOrderByAggregateInput
}

export type RegistrationsScalarWhereWithAggregatesInput = {
  AND?: Prisma.RegistrationsScalarWhereWithAggregatesInput | Prisma.RegistrationsScalarWhereWithAggregatesInput[]
  OR?: Prisma.RegistrationsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RegistrationsScalarWhereWithAggregatesInput | Prisma.RegistrationsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Registrations"> | string
  studentId?: Prisma.StringWithAggregatesFilter<"Registrations"> | string
  eventId?: Prisma.StringWithAggregatesFilter<"Registrations"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Registrations"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Registrations"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Registrations"> | Date | string | null
}

export type RegistrationsCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  student: Prisma.StudentCreateNestedOneWithoutRegistrationsInput
  event: Prisma.EventCreateNestedOneWithoutRegistrationsInput
}

export type RegistrationsUncheckedCreateInput = {
  id?: string
  studentId: string
  eventId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type RegistrationsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  student?: Prisma.StudentUpdateOneRequiredWithoutRegistrationsNestedInput
  event?: Prisma.EventUpdateOneRequiredWithoutRegistrationsNestedInput
}

export type RegistrationsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type RegistrationsCreateManyInput = {
  id?: string
  studentId: string
  eventId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type RegistrationsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type RegistrationsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type RegistrationsListRelationFilter = {
  every?: Prisma.RegistrationsWhereInput
  some?: Prisma.RegistrationsWhereInput
  none?: Prisma.RegistrationsWhereInput
}

export type RegistrationsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RegistrationsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type RegistrationsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type RegistrationsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type RegistrationsCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.RegistrationsCreateWithoutStudentInput, Prisma.RegistrationsUncheckedCreateWithoutStudentInput> | Prisma.RegistrationsCreateWithoutStudentInput[] | Prisma.RegistrationsUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.RegistrationsCreateOrConnectWithoutStudentInput | Prisma.RegistrationsCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.RegistrationsCreateManyStudentInputEnvelope
  connect?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
}

export type RegistrationsUncheckedCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.RegistrationsCreateWithoutStudentInput, Prisma.RegistrationsUncheckedCreateWithoutStudentInput> | Prisma.RegistrationsCreateWithoutStudentInput[] | Prisma.RegistrationsUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.RegistrationsCreateOrConnectWithoutStudentInput | Prisma.RegistrationsCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.RegistrationsCreateManyStudentInputEnvelope
  connect?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
}

export type RegistrationsUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.RegistrationsCreateWithoutStudentInput, Prisma.RegistrationsUncheckedCreateWithoutStudentInput> | Prisma.RegistrationsCreateWithoutStudentInput[] | Prisma.RegistrationsUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.RegistrationsCreateOrConnectWithoutStudentInput | Prisma.RegistrationsCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.RegistrationsUpsertWithWhereUniqueWithoutStudentInput | Prisma.RegistrationsUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.RegistrationsCreateManyStudentInputEnvelope
  set?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
  disconnect?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
  delete?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
  connect?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
  update?: Prisma.RegistrationsUpdateWithWhereUniqueWithoutStudentInput | Prisma.RegistrationsUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.RegistrationsUpdateManyWithWhereWithoutStudentInput | Prisma.RegistrationsUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.RegistrationsScalarWhereInput | Prisma.RegistrationsScalarWhereInput[]
}

export type RegistrationsUncheckedUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.RegistrationsCreateWithoutStudentInput, Prisma.RegistrationsUncheckedCreateWithoutStudentInput> | Prisma.RegistrationsCreateWithoutStudentInput[] | Prisma.RegistrationsUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.RegistrationsCreateOrConnectWithoutStudentInput | Prisma.RegistrationsCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.RegistrationsUpsertWithWhereUniqueWithoutStudentInput | Prisma.RegistrationsUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.RegistrationsCreateManyStudentInputEnvelope
  set?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
  disconnect?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
  delete?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
  connect?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
  update?: Prisma.RegistrationsUpdateWithWhereUniqueWithoutStudentInput | Prisma.RegistrationsUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.RegistrationsUpdateManyWithWhereWithoutStudentInput | Prisma.RegistrationsUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.RegistrationsScalarWhereInput | Prisma.RegistrationsScalarWhereInput[]
}

export type RegistrationsCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.RegistrationsCreateWithoutEventInput, Prisma.RegistrationsUncheckedCreateWithoutEventInput> | Prisma.RegistrationsCreateWithoutEventInput[] | Prisma.RegistrationsUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.RegistrationsCreateOrConnectWithoutEventInput | Prisma.RegistrationsCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.RegistrationsCreateManyEventInputEnvelope
  connect?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
}

export type RegistrationsUncheckedCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.RegistrationsCreateWithoutEventInput, Prisma.RegistrationsUncheckedCreateWithoutEventInput> | Prisma.RegistrationsCreateWithoutEventInput[] | Prisma.RegistrationsUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.RegistrationsCreateOrConnectWithoutEventInput | Prisma.RegistrationsCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.RegistrationsCreateManyEventInputEnvelope
  connect?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
}

export type RegistrationsUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.RegistrationsCreateWithoutEventInput, Prisma.RegistrationsUncheckedCreateWithoutEventInput> | Prisma.RegistrationsCreateWithoutEventInput[] | Prisma.RegistrationsUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.RegistrationsCreateOrConnectWithoutEventInput | Prisma.RegistrationsCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.RegistrationsUpsertWithWhereUniqueWithoutEventInput | Prisma.RegistrationsUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.RegistrationsCreateManyEventInputEnvelope
  set?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
  disconnect?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
  delete?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
  connect?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
  update?: Prisma.RegistrationsUpdateWithWhereUniqueWithoutEventInput | Prisma.RegistrationsUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.RegistrationsUpdateManyWithWhereWithoutEventInput | Prisma.RegistrationsUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.RegistrationsScalarWhereInput | Prisma.RegistrationsScalarWhereInput[]
}

export type RegistrationsUncheckedUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.RegistrationsCreateWithoutEventInput, Prisma.RegistrationsUncheckedCreateWithoutEventInput> | Prisma.RegistrationsCreateWithoutEventInput[] | Prisma.RegistrationsUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.RegistrationsCreateOrConnectWithoutEventInput | Prisma.RegistrationsCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.RegistrationsUpsertWithWhereUniqueWithoutEventInput | Prisma.RegistrationsUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.RegistrationsCreateManyEventInputEnvelope
  set?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
  disconnect?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
  delete?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
  connect?: Prisma.RegistrationsWhereUniqueInput | Prisma.RegistrationsWhereUniqueInput[]
  update?: Prisma.RegistrationsUpdateWithWhereUniqueWithoutEventInput | Prisma.RegistrationsUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.RegistrationsUpdateManyWithWhereWithoutEventInput | Prisma.RegistrationsUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.RegistrationsScalarWhereInput | Prisma.RegistrationsScalarWhereInput[]
}

export type RegistrationsCreateWithoutStudentInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  event: Prisma.EventCreateNestedOneWithoutRegistrationsInput
}

export type RegistrationsUncheckedCreateWithoutStudentInput = {
  id?: string
  eventId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type RegistrationsCreateOrConnectWithoutStudentInput = {
  where: Prisma.RegistrationsWhereUniqueInput
  create: Prisma.XOR<Prisma.RegistrationsCreateWithoutStudentInput, Prisma.RegistrationsUncheckedCreateWithoutStudentInput>
}

export type RegistrationsCreateManyStudentInputEnvelope = {
  data: Prisma.RegistrationsCreateManyStudentInput | Prisma.RegistrationsCreateManyStudentInput[]
  skipDuplicates?: boolean
}

export type RegistrationsUpsertWithWhereUniqueWithoutStudentInput = {
  where: Prisma.RegistrationsWhereUniqueInput
  update: Prisma.XOR<Prisma.RegistrationsUpdateWithoutStudentInput, Prisma.RegistrationsUncheckedUpdateWithoutStudentInput>
  create: Prisma.XOR<Prisma.RegistrationsCreateWithoutStudentInput, Prisma.RegistrationsUncheckedCreateWithoutStudentInput>
}

export type RegistrationsUpdateWithWhereUniqueWithoutStudentInput = {
  where: Prisma.RegistrationsWhereUniqueInput
  data: Prisma.XOR<Prisma.RegistrationsUpdateWithoutStudentInput, Prisma.RegistrationsUncheckedUpdateWithoutStudentInput>
}

export type RegistrationsUpdateManyWithWhereWithoutStudentInput = {
  where: Prisma.RegistrationsScalarWhereInput
  data: Prisma.XOR<Prisma.RegistrationsUpdateManyMutationInput, Prisma.RegistrationsUncheckedUpdateManyWithoutStudentInput>
}

export type RegistrationsScalarWhereInput = {
  AND?: Prisma.RegistrationsScalarWhereInput | Prisma.RegistrationsScalarWhereInput[]
  OR?: Prisma.RegistrationsScalarWhereInput[]
  NOT?: Prisma.RegistrationsScalarWhereInput | Prisma.RegistrationsScalarWhereInput[]
  id?: Prisma.StringFilter<"Registrations"> | string
  studentId?: Prisma.StringFilter<"Registrations"> | string
  eventId?: Prisma.StringFilter<"Registrations"> | string
  createdAt?: Prisma.DateTimeFilter<"Registrations"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Registrations"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Registrations"> | Date | string | null
}

export type RegistrationsCreateWithoutEventInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  student: Prisma.StudentCreateNestedOneWithoutRegistrationsInput
}

export type RegistrationsUncheckedCreateWithoutEventInput = {
  id?: string
  studentId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type RegistrationsCreateOrConnectWithoutEventInput = {
  where: Prisma.RegistrationsWhereUniqueInput
  create: Prisma.XOR<Prisma.RegistrationsCreateWithoutEventInput, Prisma.RegistrationsUncheckedCreateWithoutEventInput>
}

export type RegistrationsCreateManyEventInputEnvelope = {
  data: Prisma.RegistrationsCreateManyEventInput | Prisma.RegistrationsCreateManyEventInput[]
  skipDuplicates?: boolean
}

export type RegistrationsUpsertWithWhereUniqueWithoutEventInput = {
  where: Prisma.RegistrationsWhereUniqueInput
  update: Prisma.XOR<Prisma.RegistrationsUpdateWithoutEventInput, Prisma.RegistrationsUncheckedUpdateWithoutEventInput>
  create: Prisma.XOR<Prisma.RegistrationsCreateWithoutEventInput, Prisma.RegistrationsUncheckedCreateWithoutEventInput>
}

export type RegistrationsUpdateWithWhereUniqueWithoutEventInput = {
  where: Prisma.RegistrationsWhereUniqueInput
  data: Prisma.XOR<Prisma.RegistrationsUpdateWithoutEventInput, Prisma.RegistrationsUncheckedUpdateWithoutEventInput>
}

export type RegistrationsUpdateManyWithWhereWithoutEventInput = {
  where: Prisma.RegistrationsScalarWhereInput
  data: Prisma.XOR<Prisma.RegistrationsUpdateManyMutationInput, Prisma.RegistrationsUncheckedUpdateManyWithoutEventInput>
}

export type RegistrationsCreateManyStudentInput = {
  id?: string
  eventId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type RegistrationsUpdateWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  event?: Prisma.EventUpdateOneRequiredWithoutRegistrationsNestedInput
}

export type RegistrationsUncheckedUpdateWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type RegistrationsUncheckedUpdateManyWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type RegistrationsCreateManyEventInput = {
  id?: string
  studentId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type RegistrationsUpdateWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  student?: Prisma.StudentUpdateOneRequiredWithoutRegistrationsNestedInput
}

export type RegistrationsUncheckedUpdateWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type RegistrationsUncheckedUpdateManyWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type RegistrationsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  studentId?: boolean
  eventId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}, ExtArgs["result"]["registrations"]>

export type RegistrationsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  studentId?: boolean
  eventId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}, ExtArgs["result"]["registrations"]>

export type RegistrationsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  studentId?: boolean
  eventId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}, ExtArgs["result"]["registrations"]>

export type RegistrationsSelectScalar = {
  id?: boolean
  studentId?: boolean
  eventId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type RegistrationsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "studentId" | "eventId" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["registrations"]>
export type RegistrationsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}
export type RegistrationsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}
export type RegistrationsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}

export type $RegistrationsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Registrations"
  objects: {
    student: Prisma.$StudentPayload<ExtArgs>
    event: Prisma.$EventPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    studentId: string
    eventId: string
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["registrations"]>
  composites: {}
}

export type RegistrationsGetPayload<S extends boolean | null | undefined | RegistrationsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RegistrationsPayload, S>

export type RegistrationsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RegistrationsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RegistrationsCountAggregateInputType | true
  }

export interface RegistrationsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Registrations'], meta: { name: 'Registrations' } }
  /**
   * Find zero or one Registrations that matches the filter.
   * @param {RegistrationsFindUniqueArgs} args - Arguments to find a Registrations
   * @example
   * // Get one Registrations
   * const registrations = await prisma.registrations.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RegistrationsFindUniqueArgs>(args: Prisma.SelectSubset<T, RegistrationsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RegistrationsClient<runtime.Types.Result.GetResult<Prisma.$RegistrationsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Registrations that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RegistrationsFindUniqueOrThrowArgs} args - Arguments to find a Registrations
   * @example
   * // Get one Registrations
   * const registrations = await prisma.registrations.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RegistrationsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RegistrationsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RegistrationsClient<runtime.Types.Result.GetResult<Prisma.$RegistrationsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Registrations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationsFindFirstArgs} args - Arguments to find a Registrations
   * @example
   * // Get one Registrations
   * const registrations = await prisma.registrations.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RegistrationsFindFirstArgs>(args?: Prisma.SelectSubset<T, RegistrationsFindFirstArgs<ExtArgs>>): Prisma.Prisma__RegistrationsClient<runtime.Types.Result.GetResult<Prisma.$RegistrationsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Registrations that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationsFindFirstOrThrowArgs} args - Arguments to find a Registrations
   * @example
   * // Get one Registrations
   * const registrations = await prisma.registrations.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RegistrationsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RegistrationsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RegistrationsClient<runtime.Types.Result.GetResult<Prisma.$RegistrationsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Registrations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Registrations
   * const registrations = await prisma.registrations.findMany()
   * 
   * // Get first 10 Registrations
   * const registrations = await prisma.registrations.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const registrationsWithIdOnly = await prisma.registrations.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RegistrationsFindManyArgs>(args?: Prisma.SelectSubset<T, RegistrationsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RegistrationsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Registrations.
   * @param {RegistrationsCreateArgs} args - Arguments to create a Registrations.
   * @example
   * // Create one Registrations
   * const Registrations = await prisma.registrations.create({
   *   data: {
   *     // ... data to create a Registrations
   *   }
   * })
   * 
   */
  create<T extends RegistrationsCreateArgs>(args: Prisma.SelectSubset<T, RegistrationsCreateArgs<ExtArgs>>): Prisma.Prisma__RegistrationsClient<runtime.Types.Result.GetResult<Prisma.$RegistrationsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Registrations.
   * @param {RegistrationsCreateManyArgs} args - Arguments to create many Registrations.
   * @example
   * // Create many Registrations
   * const registrations = await prisma.registrations.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RegistrationsCreateManyArgs>(args?: Prisma.SelectSubset<T, RegistrationsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Registrations and returns the data saved in the database.
   * @param {RegistrationsCreateManyAndReturnArgs} args - Arguments to create many Registrations.
   * @example
   * // Create many Registrations
   * const registrations = await prisma.registrations.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Registrations and only return the `id`
   * const registrationsWithIdOnly = await prisma.registrations.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RegistrationsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RegistrationsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RegistrationsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Registrations.
   * @param {RegistrationsDeleteArgs} args - Arguments to delete one Registrations.
   * @example
   * // Delete one Registrations
   * const Registrations = await prisma.registrations.delete({
   *   where: {
   *     // ... filter to delete one Registrations
   *   }
   * })
   * 
   */
  delete<T extends RegistrationsDeleteArgs>(args: Prisma.SelectSubset<T, RegistrationsDeleteArgs<ExtArgs>>): Prisma.Prisma__RegistrationsClient<runtime.Types.Result.GetResult<Prisma.$RegistrationsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Registrations.
   * @param {RegistrationsUpdateArgs} args - Arguments to update one Registrations.
   * @example
   * // Update one Registrations
   * const registrations = await prisma.registrations.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RegistrationsUpdateArgs>(args: Prisma.SelectSubset<T, RegistrationsUpdateArgs<ExtArgs>>): Prisma.Prisma__RegistrationsClient<runtime.Types.Result.GetResult<Prisma.$RegistrationsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Registrations.
   * @param {RegistrationsDeleteManyArgs} args - Arguments to filter Registrations to delete.
   * @example
   * // Delete a few Registrations
   * const { count } = await prisma.registrations.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RegistrationsDeleteManyArgs>(args?: Prisma.SelectSubset<T, RegistrationsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Registrations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Registrations
   * const registrations = await prisma.registrations.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RegistrationsUpdateManyArgs>(args: Prisma.SelectSubset<T, RegistrationsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Registrations and returns the data updated in the database.
   * @param {RegistrationsUpdateManyAndReturnArgs} args - Arguments to update many Registrations.
   * @example
   * // Update many Registrations
   * const registrations = await prisma.registrations.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Registrations and only return the `id`
   * const registrationsWithIdOnly = await prisma.registrations.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RegistrationsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RegistrationsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RegistrationsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Registrations.
   * @param {RegistrationsUpsertArgs} args - Arguments to update or create a Registrations.
   * @example
   * // Update or create a Registrations
   * const registrations = await prisma.registrations.upsert({
   *   create: {
   *     // ... data to create a Registrations
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Registrations we want to update
   *   }
   * })
   */
  upsert<T extends RegistrationsUpsertArgs>(args: Prisma.SelectSubset<T, RegistrationsUpsertArgs<ExtArgs>>): Prisma.Prisma__RegistrationsClient<runtime.Types.Result.GetResult<Prisma.$RegistrationsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Registrations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationsCountArgs} args - Arguments to filter Registrations to count.
   * @example
   * // Count the number of Registrations
   * const count = await prisma.registrations.count({
   *   where: {
   *     // ... the filter for the Registrations we want to count
   *   }
   * })
  **/
  count<T extends RegistrationsCountArgs>(
    args?: Prisma.Subset<T, RegistrationsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RegistrationsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Registrations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RegistrationsAggregateArgs>(args: Prisma.Subset<T, RegistrationsAggregateArgs>): Prisma.PrismaPromise<GetRegistrationsAggregateType<T>>

  /**
   * Group by Registrations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RegistrationsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RegistrationsGroupByArgs['orderBy'] }
      : { orderBy?: RegistrationsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RegistrationsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRegistrationsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Registrations model
 */
readonly fields: RegistrationsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Registrations.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RegistrationsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  student<T extends Prisma.StudentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StudentDefaultArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  event<T extends Prisma.EventDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventDefaultArgs<ExtArgs>>): Prisma.Prisma__EventClient<runtime.Types.Result.GetResult<Prisma.$EventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Registrations model
 */
export interface RegistrationsFieldRefs {
  readonly id: Prisma.FieldRef<"Registrations", 'String'>
  readonly studentId: Prisma.FieldRef<"Registrations", 'String'>
  readonly eventId: Prisma.FieldRef<"Registrations", 'String'>
  readonly createdAt: Prisma.FieldRef<"Registrations", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Registrations", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"Registrations", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Registrations findUnique
 */
export type RegistrationsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Registrations
   */
  select?: Prisma.RegistrationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Registrations
   */
  omit?: Prisma.RegistrationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationsInclude<ExtArgs> | null
  /**
   * Filter, which Registrations to fetch.
   */
  where: Prisma.RegistrationsWhereUniqueInput
}

/**
 * Registrations findUniqueOrThrow
 */
export type RegistrationsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Registrations
   */
  select?: Prisma.RegistrationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Registrations
   */
  omit?: Prisma.RegistrationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationsInclude<ExtArgs> | null
  /**
   * Filter, which Registrations to fetch.
   */
  where: Prisma.RegistrationsWhereUniqueInput
}

/**
 * Registrations findFirst
 */
export type RegistrationsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Registrations
   */
  select?: Prisma.RegistrationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Registrations
   */
  omit?: Prisma.RegistrationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationsInclude<ExtArgs> | null
  /**
   * Filter, which Registrations to fetch.
   */
  where?: Prisma.RegistrationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Registrations to fetch.
   */
  orderBy?: Prisma.RegistrationsOrderByWithRelationInput | Prisma.RegistrationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Registrations.
   */
  cursor?: Prisma.RegistrationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Registrations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Registrations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Registrations.
   */
  distinct?: Prisma.RegistrationsScalarFieldEnum | Prisma.RegistrationsScalarFieldEnum[]
}

/**
 * Registrations findFirstOrThrow
 */
export type RegistrationsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Registrations
   */
  select?: Prisma.RegistrationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Registrations
   */
  omit?: Prisma.RegistrationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationsInclude<ExtArgs> | null
  /**
   * Filter, which Registrations to fetch.
   */
  where?: Prisma.RegistrationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Registrations to fetch.
   */
  orderBy?: Prisma.RegistrationsOrderByWithRelationInput | Prisma.RegistrationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Registrations.
   */
  cursor?: Prisma.RegistrationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Registrations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Registrations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Registrations.
   */
  distinct?: Prisma.RegistrationsScalarFieldEnum | Prisma.RegistrationsScalarFieldEnum[]
}

/**
 * Registrations findMany
 */
export type RegistrationsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Registrations
   */
  select?: Prisma.RegistrationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Registrations
   */
  omit?: Prisma.RegistrationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationsInclude<ExtArgs> | null
  /**
   * Filter, which Registrations to fetch.
   */
  where?: Prisma.RegistrationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Registrations to fetch.
   */
  orderBy?: Prisma.RegistrationsOrderByWithRelationInput | Prisma.RegistrationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Registrations.
   */
  cursor?: Prisma.RegistrationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Registrations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Registrations.
   */
  skip?: number
  distinct?: Prisma.RegistrationsScalarFieldEnum | Prisma.RegistrationsScalarFieldEnum[]
}

/**
 * Registrations create
 */
export type RegistrationsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Registrations
   */
  select?: Prisma.RegistrationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Registrations
   */
  omit?: Prisma.RegistrationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationsInclude<ExtArgs> | null
  /**
   * The data needed to create a Registrations.
   */
  data: Prisma.XOR<Prisma.RegistrationsCreateInput, Prisma.RegistrationsUncheckedCreateInput>
}

/**
 * Registrations createMany
 */
export type RegistrationsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Registrations.
   */
  data: Prisma.RegistrationsCreateManyInput | Prisma.RegistrationsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Registrations createManyAndReturn
 */
export type RegistrationsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Registrations
   */
  select?: Prisma.RegistrationsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Registrations
   */
  omit?: Prisma.RegistrationsOmit<ExtArgs> | null
  /**
   * The data used to create many Registrations.
   */
  data: Prisma.RegistrationsCreateManyInput | Prisma.RegistrationsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Registrations update
 */
export type RegistrationsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Registrations
   */
  select?: Prisma.RegistrationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Registrations
   */
  omit?: Prisma.RegistrationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationsInclude<ExtArgs> | null
  /**
   * The data needed to update a Registrations.
   */
  data: Prisma.XOR<Prisma.RegistrationsUpdateInput, Prisma.RegistrationsUncheckedUpdateInput>
  /**
   * Choose, which Registrations to update.
   */
  where: Prisma.RegistrationsWhereUniqueInput
}

/**
 * Registrations updateMany
 */
export type RegistrationsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Registrations.
   */
  data: Prisma.XOR<Prisma.RegistrationsUpdateManyMutationInput, Prisma.RegistrationsUncheckedUpdateManyInput>
  /**
   * Filter which Registrations to update
   */
  where?: Prisma.RegistrationsWhereInput
  /**
   * Limit how many Registrations to update.
   */
  limit?: number
}

/**
 * Registrations updateManyAndReturn
 */
export type RegistrationsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Registrations
   */
  select?: Prisma.RegistrationsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Registrations
   */
  omit?: Prisma.RegistrationsOmit<ExtArgs> | null
  /**
   * The data used to update Registrations.
   */
  data: Prisma.XOR<Prisma.RegistrationsUpdateManyMutationInput, Prisma.RegistrationsUncheckedUpdateManyInput>
  /**
   * Filter which Registrations to update
   */
  where?: Prisma.RegistrationsWhereInput
  /**
   * Limit how many Registrations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Registrations upsert
 */
export type RegistrationsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Registrations
   */
  select?: Prisma.RegistrationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Registrations
   */
  omit?: Prisma.RegistrationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationsInclude<ExtArgs> | null
  /**
   * The filter to search for the Registrations to update in case it exists.
   */
  where: Prisma.RegistrationsWhereUniqueInput
  /**
   * In case the Registrations found by the `where` argument doesn't exist, create a new Registrations with this data.
   */
  create: Prisma.XOR<Prisma.RegistrationsCreateInput, Prisma.RegistrationsUncheckedCreateInput>
  /**
   * In case the Registrations was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RegistrationsUpdateInput, Prisma.RegistrationsUncheckedUpdateInput>
}

/**
 * Registrations delete
 */
export type RegistrationsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Registrations
   */
  select?: Prisma.RegistrationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Registrations
   */
  omit?: Prisma.RegistrationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationsInclude<ExtArgs> | null
  /**
   * Filter which Registrations to delete.
   */
  where: Prisma.RegistrationsWhereUniqueInput
}

/**
 * Registrations deleteMany
 */
export type RegistrationsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Registrations to delete
   */
  where?: Prisma.RegistrationsWhereInput
  /**
   * Limit how many Registrations to delete.
   */
  limit?: number
}

/**
 * Registrations without action
 */
export type RegistrationsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Registrations
   */
  select?: Prisma.RegistrationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Registrations
   */
  omit?: Prisma.RegistrationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationsInclude<ExtArgs> | null
}
