
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RoleInClub` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RoleInClub
 * 
 */
export type RoleInClubModel = runtime.Types.Result.DefaultSelection<Prisma.$RoleInClubPayload>

export type AggregateRoleInClub = {
  _count: RoleInClubCountAggregateOutputType | null
  _min: RoleInClubMinAggregateOutputType | null
  _max: RoleInClubMaxAggregateOutputType | null
}

export type RoleInClubMinAggregateOutputType = {
  id: string | null
  name: string | null
  clubId: string | null
}

export type RoleInClubMaxAggregateOutputType = {
  id: string | null
  name: string | null
  clubId: string | null
}

export type RoleInClubCountAggregateOutputType = {
  id: number
  name: number
  clubId: number
  _all: number
}


export type RoleInClubMinAggregateInputType = {
  id?: true
  name?: true
  clubId?: true
}

export type RoleInClubMaxAggregateInputType = {
  id?: true
  name?: true
  clubId?: true
}

export type RoleInClubCountAggregateInputType = {
  id?: true
  name?: true
  clubId?: true
  _all?: true
}

export type RoleInClubAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RoleInClub to aggregate.
   */
  where?: Prisma.RoleInClubWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RoleInClubs to fetch.
   */
  orderBy?: Prisma.RoleInClubOrderByWithRelationInput | Prisma.RoleInClubOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RoleInClubWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RoleInClubs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RoleInClubs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RoleInClubs
  **/
  _count?: true | RoleInClubCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RoleInClubMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RoleInClubMaxAggregateInputType
}

export type GetRoleInClubAggregateType<T extends RoleInClubAggregateArgs> = {
      [P in keyof T & keyof AggregateRoleInClub]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRoleInClub[P]>
    : Prisma.GetScalarType<T[P], AggregateRoleInClub[P]>
}




export type RoleInClubGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RoleInClubWhereInput
  orderBy?: Prisma.RoleInClubOrderByWithAggregationInput | Prisma.RoleInClubOrderByWithAggregationInput[]
  by: Prisma.RoleInClubScalarFieldEnum[] | Prisma.RoleInClubScalarFieldEnum
  having?: Prisma.RoleInClubScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RoleInClubCountAggregateInputType | true
  _min?: RoleInClubMinAggregateInputType
  _max?: RoleInClubMaxAggregateInputType
}

export type RoleInClubGroupByOutputType = {
  id: string
  name: string
  clubId: string
  _count: RoleInClubCountAggregateOutputType | null
  _min: RoleInClubMinAggregateOutputType | null
  _max: RoleInClubMaxAggregateOutputType | null
}

type GetRoleInClubGroupByPayload<T extends RoleInClubGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RoleInClubGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RoleInClubGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RoleInClubGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RoleInClubGroupByOutputType[P]>
      }
    >
  >



export type RoleInClubWhereInput = {
  AND?: Prisma.RoleInClubWhereInput | Prisma.RoleInClubWhereInput[]
  OR?: Prisma.RoleInClubWhereInput[]
  NOT?: Prisma.RoleInClubWhereInput | Prisma.RoleInClubWhereInput[]
  id?: Prisma.StringFilter<"RoleInClub"> | string
  name?: Prisma.StringFilter<"RoleInClub"> | string
  clubId?: Prisma.StringFilter<"RoleInClub"> | string
  club?: Prisma.XOR<Prisma.ClubScalarRelationFilter, Prisma.ClubWhereInput>
  members?: Prisma.StudentInClubListRelationFilter
}

export type RoleInClubOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  clubId?: Prisma.SortOrder
  club?: Prisma.ClubOrderByWithRelationInput
  members?: Prisma.StudentInClubOrderByRelationAggregateInput
}

export type RoleInClubWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name_clubId?: Prisma.RoleInClubNameClubIdCompoundUniqueInput
  AND?: Prisma.RoleInClubWhereInput | Prisma.RoleInClubWhereInput[]
  OR?: Prisma.RoleInClubWhereInput[]
  NOT?: Prisma.RoleInClubWhereInput | Prisma.RoleInClubWhereInput[]
  name?: Prisma.StringFilter<"RoleInClub"> | string
  clubId?: Prisma.StringFilter<"RoleInClub"> | string
  club?: Prisma.XOR<Prisma.ClubScalarRelationFilter, Prisma.ClubWhereInput>
  members?: Prisma.StudentInClubListRelationFilter
}, "id" | "name_clubId">

export type RoleInClubOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  clubId?: Prisma.SortOrder
  _count?: Prisma.RoleInClubCountOrderByAggregateInput
  _max?: Prisma.RoleInClubMaxOrderByAggregateInput
  _min?: Prisma.RoleInClubMinOrderByAggregateInput
}

export type RoleInClubScalarWhereWithAggregatesInput = {
  AND?: Prisma.RoleInClubScalarWhereWithAggregatesInput | Prisma.RoleInClubScalarWhereWithAggregatesInput[]
  OR?: Prisma.RoleInClubScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RoleInClubScalarWhereWithAggregatesInput | Prisma.RoleInClubScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RoleInClub"> | string
  name?: Prisma.StringWithAggregatesFilter<"RoleInClub"> | string
  clubId?: Prisma.StringWithAggregatesFilter<"RoleInClub"> | string
}

export type RoleInClubCreateInput = {
  id?: string
  name: string
  club: Prisma.ClubCreateNestedOneWithoutRoleInput
  members?: Prisma.StudentInClubCreateNestedManyWithoutRoleInput
}

export type RoleInClubUncheckedCreateInput = {
  id?: string
  name: string
  clubId: string
  members?: Prisma.StudentInClubUncheckedCreateNestedManyWithoutRoleInput
}

export type RoleInClubUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  club?: Prisma.ClubUpdateOneRequiredWithoutRoleNestedInput
  members?: Prisma.StudentInClubUpdateManyWithoutRoleNestedInput
}

export type RoleInClubUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  clubId?: Prisma.StringFieldUpdateOperationsInput | string
  members?: Prisma.StudentInClubUncheckedUpdateManyWithoutRoleNestedInput
}

export type RoleInClubCreateManyInput = {
  id?: string
  name: string
  clubId: string
}

export type RoleInClubUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RoleInClubUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  clubId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RoleInClubListRelationFilter = {
  every?: Prisma.RoleInClubWhereInput
  some?: Prisma.RoleInClubWhereInput
  none?: Prisma.RoleInClubWhereInput
}

export type RoleInClubOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RoleInClubScalarRelationFilter = {
  is?: Prisma.RoleInClubWhereInput
  isNot?: Prisma.RoleInClubWhereInput
}

export type RoleInClubNameClubIdCompoundUniqueInput = {
  name: string
  clubId: string
}

export type RoleInClubCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  clubId?: Prisma.SortOrder
}

export type RoleInClubMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  clubId?: Prisma.SortOrder
}

export type RoleInClubMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  clubId?: Prisma.SortOrder
}

export type RoleInClubCreateNestedManyWithoutClubInput = {
  create?: Prisma.XOR<Prisma.RoleInClubCreateWithoutClubInput, Prisma.RoleInClubUncheckedCreateWithoutClubInput> | Prisma.RoleInClubCreateWithoutClubInput[] | Prisma.RoleInClubUncheckedCreateWithoutClubInput[]
  connectOrCreate?: Prisma.RoleInClubCreateOrConnectWithoutClubInput | Prisma.RoleInClubCreateOrConnectWithoutClubInput[]
  createMany?: Prisma.RoleInClubCreateManyClubInputEnvelope
  connect?: Prisma.RoleInClubWhereUniqueInput | Prisma.RoleInClubWhereUniqueInput[]
}

export type RoleInClubUncheckedCreateNestedManyWithoutClubInput = {
  create?: Prisma.XOR<Prisma.RoleInClubCreateWithoutClubInput, Prisma.RoleInClubUncheckedCreateWithoutClubInput> | Prisma.RoleInClubCreateWithoutClubInput[] | Prisma.RoleInClubUncheckedCreateWithoutClubInput[]
  connectOrCreate?: Prisma.RoleInClubCreateOrConnectWithoutClubInput | Prisma.RoleInClubCreateOrConnectWithoutClubInput[]
  createMany?: Prisma.RoleInClubCreateManyClubInputEnvelope
  connect?: Prisma.RoleInClubWhereUniqueInput | Prisma.RoleInClubWhereUniqueInput[]
}

export type RoleInClubUpdateManyWithoutClubNestedInput = {
  create?: Prisma.XOR<Prisma.RoleInClubCreateWithoutClubInput, Prisma.RoleInClubUncheckedCreateWithoutClubInput> | Prisma.RoleInClubCreateWithoutClubInput[] | Prisma.RoleInClubUncheckedCreateWithoutClubInput[]
  connectOrCreate?: Prisma.RoleInClubCreateOrConnectWithoutClubInput | Prisma.RoleInClubCreateOrConnectWithoutClubInput[]
  upsert?: Prisma.RoleInClubUpsertWithWhereUniqueWithoutClubInput | Prisma.RoleInClubUpsertWithWhereUniqueWithoutClubInput[]
  createMany?: Prisma.RoleInClubCreateManyClubInputEnvelope
  set?: Prisma.RoleInClubWhereUniqueInput | Prisma.RoleInClubWhereUniqueInput[]
  disconnect?: Prisma.RoleInClubWhereUniqueInput | Prisma.RoleInClubWhereUniqueInput[]
  delete?: Prisma.RoleInClubWhereUniqueInput | Prisma.RoleInClubWhereUniqueInput[]
  connect?: Prisma.RoleInClubWhereUniqueInput | Prisma.RoleInClubWhereUniqueInput[]
  update?: Prisma.RoleInClubUpdateWithWhereUniqueWithoutClubInput | Prisma.RoleInClubUpdateWithWhereUniqueWithoutClubInput[]
  updateMany?: Prisma.RoleInClubUpdateManyWithWhereWithoutClubInput | Prisma.RoleInClubUpdateManyWithWhereWithoutClubInput[]
  deleteMany?: Prisma.RoleInClubScalarWhereInput | Prisma.RoleInClubScalarWhereInput[]
}

export type RoleInClubUncheckedUpdateManyWithoutClubNestedInput = {
  create?: Prisma.XOR<Prisma.RoleInClubCreateWithoutClubInput, Prisma.RoleInClubUncheckedCreateWithoutClubInput> | Prisma.RoleInClubCreateWithoutClubInput[] | Prisma.RoleInClubUncheckedCreateWithoutClubInput[]
  connectOrCreate?: Prisma.RoleInClubCreateOrConnectWithoutClubInput | Prisma.RoleInClubCreateOrConnectWithoutClubInput[]
  upsert?: Prisma.RoleInClubUpsertWithWhereUniqueWithoutClubInput | Prisma.RoleInClubUpsertWithWhereUniqueWithoutClubInput[]
  createMany?: Prisma.RoleInClubCreateManyClubInputEnvelope
  set?: Prisma.RoleInClubWhereUniqueInput | Prisma.RoleInClubWhereUniqueInput[]
  disconnect?: Prisma.RoleInClubWhereUniqueInput | Prisma.RoleInClubWhereUniqueInput[]
  delete?: Prisma.RoleInClubWhereUniqueInput | Prisma.RoleInClubWhereUniqueInput[]
  connect?: Prisma.RoleInClubWhereUniqueInput | Prisma.RoleInClubWhereUniqueInput[]
  update?: Prisma.RoleInClubUpdateWithWhereUniqueWithoutClubInput | Prisma.RoleInClubUpdateWithWhereUniqueWithoutClubInput[]
  updateMany?: Prisma.RoleInClubUpdateManyWithWhereWithoutClubInput | Prisma.RoleInClubUpdateManyWithWhereWithoutClubInput[]
  deleteMany?: Prisma.RoleInClubScalarWhereInput | Prisma.RoleInClubScalarWhereInput[]
}

export type RoleInClubCreateNestedOneWithoutMembersInput = {
  create?: Prisma.XOR<Prisma.RoleInClubCreateWithoutMembersInput, Prisma.RoleInClubUncheckedCreateWithoutMembersInput>
  connectOrCreate?: Prisma.RoleInClubCreateOrConnectWithoutMembersInput
  connect?: Prisma.RoleInClubWhereUniqueInput
}

export type RoleInClubUpdateOneRequiredWithoutMembersNestedInput = {
  create?: Prisma.XOR<Prisma.RoleInClubCreateWithoutMembersInput, Prisma.RoleInClubUncheckedCreateWithoutMembersInput>
  connectOrCreate?: Prisma.RoleInClubCreateOrConnectWithoutMembersInput
  upsert?: Prisma.RoleInClubUpsertWithoutMembersInput
  connect?: Prisma.RoleInClubWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RoleInClubUpdateToOneWithWhereWithoutMembersInput, Prisma.RoleInClubUpdateWithoutMembersInput>, Prisma.RoleInClubUncheckedUpdateWithoutMembersInput>
}

export type RoleInClubCreateWithoutClubInput = {
  id?: string
  name: string
  members?: Prisma.StudentInClubCreateNestedManyWithoutRoleInput
}

export type RoleInClubUncheckedCreateWithoutClubInput = {
  id?: string
  name: string
  members?: Prisma.StudentInClubUncheckedCreateNestedManyWithoutRoleInput
}

export type RoleInClubCreateOrConnectWithoutClubInput = {
  where: Prisma.RoleInClubWhereUniqueInput
  create: Prisma.XOR<Prisma.RoleInClubCreateWithoutClubInput, Prisma.RoleInClubUncheckedCreateWithoutClubInput>
}

export type RoleInClubCreateManyClubInputEnvelope = {
  data: Prisma.RoleInClubCreateManyClubInput | Prisma.RoleInClubCreateManyClubInput[]
  skipDuplicates?: boolean
}

export type RoleInClubUpsertWithWhereUniqueWithoutClubInput = {
  where: Prisma.RoleInClubWhereUniqueInput
  update: Prisma.XOR<Prisma.RoleInClubUpdateWithoutClubInput, Prisma.RoleInClubUncheckedUpdateWithoutClubInput>
  create: Prisma.XOR<Prisma.RoleInClubCreateWithoutClubInput, Prisma.RoleInClubUncheckedCreateWithoutClubInput>
}

export type RoleInClubUpdateWithWhereUniqueWithoutClubInput = {
  where: Prisma.RoleInClubWhereUniqueInput
  data: Prisma.XOR<Prisma.RoleInClubUpdateWithoutClubInput, Prisma.RoleInClubUncheckedUpdateWithoutClubInput>
}

export type RoleInClubUpdateManyWithWhereWithoutClubInput = {
  where: Prisma.RoleInClubScalarWhereInput
  data: Prisma.XOR<Prisma.RoleInClubUpdateManyMutationInput, Prisma.RoleInClubUncheckedUpdateManyWithoutClubInput>
}

export type RoleInClubScalarWhereInput = {
  AND?: Prisma.RoleInClubScalarWhereInput | Prisma.RoleInClubScalarWhereInput[]
  OR?: Prisma.RoleInClubScalarWhereInput[]
  NOT?: Prisma.RoleInClubScalarWhereInput | Prisma.RoleInClubScalarWhereInput[]
  id?: Prisma.StringFilter<"RoleInClub"> | string
  name?: Prisma.StringFilter<"RoleInClub"> | string
  clubId?: Prisma.StringFilter<"RoleInClub"> | string
}

export type RoleInClubCreateWithoutMembersInput = {
  id?: string
  name: string
  club: Prisma.ClubCreateNestedOneWithoutRoleInput
}

export type RoleInClubUncheckedCreateWithoutMembersInput = {
  id?: string
  name: string
  clubId: string
}

export type RoleInClubCreateOrConnectWithoutMembersInput = {
  where: Prisma.RoleInClubWhereUniqueInput
  create: Prisma.XOR<Prisma.RoleInClubCreateWithoutMembersInput, Prisma.RoleInClubUncheckedCreateWithoutMembersInput>
}

export type RoleInClubUpsertWithoutMembersInput = {
  update: Prisma.XOR<Prisma.RoleInClubUpdateWithoutMembersInput, Prisma.RoleInClubUncheckedUpdateWithoutMembersInput>
  create: Prisma.XOR<Prisma.RoleInClubCreateWithoutMembersInput, Prisma.RoleInClubUncheckedCreateWithoutMembersInput>
  where?: Prisma.RoleInClubWhereInput
}

export type RoleInClubUpdateToOneWithWhereWithoutMembersInput = {
  where?: Prisma.RoleInClubWhereInput
  data: Prisma.XOR<Prisma.RoleInClubUpdateWithoutMembersInput, Prisma.RoleInClubUncheckedUpdateWithoutMembersInput>
}

export type RoleInClubUpdateWithoutMembersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  club?: Prisma.ClubUpdateOneRequiredWithoutRoleNestedInput
}

export type RoleInClubUncheckedUpdateWithoutMembersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  clubId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RoleInClubCreateManyClubInput = {
  id?: string
  name: string
}

export type RoleInClubUpdateWithoutClubInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  members?: Prisma.StudentInClubUpdateManyWithoutRoleNestedInput
}

export type RoleInClubUncheckedUpdateWithoutClubInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  members?: Prisma.StudentInClubUncheckedUpdateManyWithoutRoleNestedInput
}

export type RoleInClubUncheckedUpdateManyWithoutClubInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type RoleInClubCountOutputType
 */

export type RoleInClubCountOutputType = {
  members: number
}

export type RoleInClubCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  members?: boolean | RoleInClubCountOutputTypeCountMembersArgs
}

/**
 * RoleInClubCountOutputType without action
 */
export type RoleInClubCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleInClubCountOutputType
   */
  select?: Prisma.RoleInClubCountOutputTypeSelect<ExtArgs> | null
}

/**
 * RoleInClubCountOutputType without action
 */
export type RoleInClubCountOutputTypeCountMembersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StudentInClubWhereInput
}


export type RoleInClubSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  clubId?: boolean
  club?: boolean | Prisma.ClubDefaultArgs<ExtArgs>
  members?: boolean | Prisma.RoleInClub$membersArgs<ExtArgs>
  _count?: boolean | Prisma.RoleInClubCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["roleInClub"]>

export type RoleInClubSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  clubId?: boolean
  club?: boolean | Prisma.ClubDefaultArgs<ExtArgs>
}, ExtArgs["result"]["roleInClub"]>

export type RoleInClubSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  clubId?: boolean
  club?: boolean | Prisma.ClubDefaultArgs<ExtArgs>
}, ExtArgs["result"]["roleInClub"]>

export type RoleInClubSelectScalar = {
  id?: boolean
  name?: boolean
  clubId?: boolean
}

export type RoleInClubOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "clubId", ExtArgs["result"]["roleInClub"]>
export type RoleInClubInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  club?: boolean | Prisma.ClubDefaultArgs<ExtArgs>
  members?: boolean | Prisma.RoleInClub$membersArgs<ExtArgs>
  _count?: boolean | Prisma.RoleInClubCountOutputTypeDefaultArgs<ExtArgs>
}
export type RoleInClubIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  club?: boolean | Prisma.ClubDefaultArgs<ExtArgs>
}
export type RoleInClubIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  club?: boolean | Prisma.ClubDefaultArgs<ExtArgs>
}

export type $RoleInClubPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RoleInClub"
  objects: {
    club: Prisma.$ClubPayload<ExtArgs>
    members: Prisma.$StudentInClubPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    clubId: string
  }, ExtArgs["result"]["roleInClub"]>
  composites: {}
}

export type RoleInClubGetPayload<S extends boolean | null | undefined | RoleInClubDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RoleInClubPayload, S>

export type RoleInClubCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RoleInClubFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RoleInClubCountAggregateInputType | true
  }

export interface RoleInClubDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RoleInClub'], meta: { name: 'RoleInClub' } }
  /**
   * Find zero or one RoleInClub that matches the filter.
   * @param {RoleInClubFindUniqueArgs} args - Arguments to find a RoleInClub
   * @example
   * // Get one RoleInClub
   * const roleInClub = await prisma.roleInClub.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RoleInClubFindUniqueArgs>(args: Prisma.SelectSubset<T, RoleInClubFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RoleInClubClient<runtime.Types.Result.GetResult<Prisma.$RoleInClubPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RoleInClub that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RoleInClubFindUniqueOrThrowArgs} args - Arguments to find a RoleInClub
   * @example
   * // Get one RoleInClub
   * const roleInClub = await prisma.roleInClub.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RoleInClubFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RoleInClubFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RoleInClubClient<runtime.Types.Result.GetResult<Prisma.$RoleInClubPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RoleInClub that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoleInClubFindFirstArgs} args - Arguments to find a RoleInClub
   * @example
   * // Get one RoleInClub
   * const roleInClub = await prisma.roleInClub.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RoleInClubFindFirstArgs>(args?: Prisma.SelectSubset<T, RoleInClubFindFirstArgs<ExtArgs>>): Prisma.Prisma__RoleInClubClient<runtime.Types.Result.GetResult<Prisma.$RoleInClubPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RoleInClub that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoleInClubFindFirstOrThrowArgs} args - Arguments to find a RoleInClub
   * @example
   * // Get one RoleInClub
   * const roleInClub = await prisma.roleInClub.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RoleInClubFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RoleInClubFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RoleInClubClient<runtime.Types.Result.GetResult<Prisma.$RoleInClubPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RoleInClubs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoleInClubFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RoleInClubs
   * const roleInClubs = await prisma.roleInClub.findMany()
   * 
   * // Get first 10 RoleInClubs
   * const roleInClubs = await prisma.roleInClub.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const roleInClubWithIdOnly = await prisma.roleInClub.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RoleInClubFindManyArgs>(args?: Prisma.SelectSubset<T, RoleInClubFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RoleInClubPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RoleInClub.
   * @param {RoleInClubCreateArgs} args - Arguments to create a RoleInClub.
   * @example
   * // Create one RoleInClub
   * const RoleInClub = await prisma.roleInClub.create({
   *   data: {
   *     // ... data to create a RoleInClub
   *   }
   * })
   * 
   */
  create<T extends RoleInClubCreateArgs>(args: Prisma.SelectSubset<T, RoleInClubCreateArgs<ExtArgs>>): Prisma.Prisma__RoleInClubClient<runtime.Types.Result.GetResult<Prisma.$RoleInClubPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RoleInClubs.
   * @param {RoleInClubCreateManyArgs} args - Arguments to create many RoleInClubs.
   * @example
   * // Create many RoleInClubs
   * const roleInClub = await prisma.roleInClub.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RoleInClubCreateManyArgs>(args?: Prisma.SelectSubset<T, RoleInClubCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RoleInClubs and returns the data saved in the database.
   * @param {RoleInClubCreateManyAndReturnArgs} args - Arguments to create many RoleInClubs.
   * @example
   * // Create many RoleInClubs
   * const roleInClub = await prisma.roleInClub.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RoleInClubs and only return the `id`
   * const roleInClubWithIdOnly = await prisma.roleInClub.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RoleInClubCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RoleInClubCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RoleInClubPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RoleInClub.
   * @param {RoleInClubDeleteArgs} args - Arguments to delete one RoleInClub.
   * @example
   * // Delete one RoleInClub
   * const RoleInClub = await prisma.roleInClub.delete({
   *   where: {
   *     // ... filter to delete one RoleInClub
   *   }
   * })
   * 
   */
  delete<T extends RoleInClubDeleteArgs>(args: Prisma.SelectSubset<T, RoleInClubDeleteArgs<ExtArgs>>): Prisma.Prisma__RoleInClubClient<runtime.Types.Result.GetResult<Prisma.$RoleInClubPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RoleInClub.
   * @param {RoleInClubUpdateArgs} args - Arguments to update one RoleInClub.
   * @example
   * // Update one RoleInClub
   * const roleInClub = await prisma.roleInClub.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RoleInClubUpdateArgs>(args: Prisma.SelectSubset<T, RoleInClubUpdateArgs<ExtArgs>>): Prisma.Prisma__RoleInClubClient<runtime.Types.Result.GetResult<Prisma.$RoleInClubPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RoleInClubs.
   * @param {RoleInClubDeleteManyArgs} args - Arguments to filter RoleInClubs to delete.
   * @example
   * // Delete a few RoleInClubs
   * const { count } = await prisma.roleInClub.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RoleInClubDeleteManyArgs>(args?: Prisma.SelectSubset<T, RoleInClubDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RoleInClubs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoleInClubUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RoleInClubs
   * const roleInClub = await prisma.roleInClub.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RoleInClubUpdateManyArgs>(args: Prisma.SelectSubset<T, RoleInClubUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RoleInClubs and returns the data updated in the database.
   * @param {RoleInClubUpdateManyAndReturnArgs} args - Arguments to update many RoleInClubs.
   * @example
   * // Update many RoleInClubs
   * const roleInClub = await prisma.roleInClub.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RoleInClubs and only return the `id`
   * const roleInClubWithIdOnly = await prisma.roleInClub.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RoleInClubUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RoleInClubUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RoleInClubPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RoleInClub.
   * @param {RoleInClubUpsertArgs} args - Arguments to update or create a RoleInClub.
   * @example
   * // Update or create a RoleInClub
   * const roleInClub = await prisma.roleInClub.upsert({
   *   create: {
   *     // ... data to create a RoleInClub
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RoleInClub we want to update
   *   }
   * })
   */
  upsert<T extends RoleInClubUpsertArgs>(args: Prisma.SelectSubset<T, RoleInClubUpsertArgs<ExtArgs>>): Prisma.Prisma__RoleInClubClient<runtime.Types.Result.GetResult<Prisma.$RoleInClubPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RoleInClubs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoleInClubCountArgs} args - Arguments to filter RoleInClubs to count.
   * @example
   * // Count the number of RoleInClubs
   * const count = await prisma.roleInClub.count({
   *   where: {
   *     // ... the filter for the RoleInClubs we want to count
   *   }
   * })
  **/
  count<T extends RoleInClubCountArgs>(
    args?: Prisma.Subset<T, RoleInClubCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RoleInClubCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RoleInClub.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoleInClubAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RoleInClubAggregateArgs>(args: Prisma.Subset<T, RoleInClubAggregateArgs>): Prisma.PrismaPromise<GetRoleInClubAggregateType<T>>

  /**
   * Group by RoleInClub.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoleInClubGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RoleInClubGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RoleInClubGroupByArgs['orderBy'] }
      : { orderBy?: RoleInClubGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RoleInClubGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRoleInClubGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RoleInClub model
 */
readonly fields: RoleInClubFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RoleInClub.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RoleInClubClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  club<T extends Prisma.ClubDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ClubDefaultArgs<ExtArgs>>): Prisma.Prisma__ClubClient<runtime.Types.Result.GetResult<Prisma.$ClubPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  members<T extends Prisma.RoleInClub$membersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RoleInClub$membersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudentInClubPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RoleInClub model
 */
export interface RoleInClubFieldRefs {
  readonly id: Prisma.FieldRef<"RoleInClub", 'String'>
  readonly name: Prisma.FieldRef<"RoleInClub", 'String'>
  readonly clubId: Prisma.FieldRef<"RoleInClub", 'String'>
}
    

// Custom InputTypes
/**
 * RoleInClub findUnique
 */
export type RoleInClubFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleInClub
   */
  select?: Prisma.RoleInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleInClub
   */
  omit?: Prisma.RoleInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoleInClubInclude<ExtArgs> | null
  /**
   * Filter, which RoleInClub to fetch.
   */
  where: Prisma.RoleInClubWhereUniqueInput
}

/**
 * RoleInClub findUniqueOrThrow
 */
export type RoleInClubFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleInClub
   */
  select?: Prisma.RoleInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleInClub
   */
  omit?: Prisma.RoleInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoleInClubInclude<ExtArgs> | null
  /**
   * Filter, which RoleInClub to fetch.
   */
  where: Prisma.RoleInClubWhereUniqueInput
}

/**
 * RoleInClub findFirst
 */
export type RoleInClubFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleInClub
   */
  select?: Prisma.RoleInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleInClub
   */
  omit?: Prisma.RoleInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoleInClubInclude<ExtArgs> | null
  /**
   * Filter, which RoleInClub to fetch.
   */
  where?: Prisma.RoleInClubWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RoleInClubs to fetch.
   */
  orderBy?: Prisma.RoleInClubOrderByWithRelationInput | Prisma.RoleInClubOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RoleInClubs.
   */
  cursor?: Prisma.RoleInClubWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RoleInClubs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RoleInClubs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RoleInClubs.
   */
  distinct?: Prisma.RoleInClubScalarFieldEnum | Prisma.RoleInClubScalarFieldEnum[]
}

/**
 * RoleInClub findFirstOrThrow
 */
export type RoleInClubFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleInClub
   */
  select?: Prisma.RoleInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleInClub
   */
  omit?: Prisma.RoleInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoleInClubInclude<ExtArgs> | null
  /**
   * Filter, which RoleInClub to fetch.
   */
  where?: Prisma.RoleInClubWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RoleInClubs to fetch.
   */
  orderBy?: Prisma.RoleInClubOrderByWithRelationInput | Prisma.RoleInClubOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RoleInClubs.
   */
  cursor?: Prisma.RoleInClubWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RoleInClubs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RoleInClubs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RoleInClubs.
   */
  distinct?: Prisma.RoleInClubScalarFieldEnum | Prisma.RoleInClubScalarFieldEnum[]
}

/**
 * RoleInClub findMany
 */
export type RoleInClubFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleInClub
   */
  select?: Prisma.RoleInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleInClub
   */
  omit?: Prisma.RoleInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoleInClubInclude<ExtArgs> | null
  /**
   * Filter, which RoleInClubs to fetch.
   */
  where?: Prisma.RoleInClubWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RoleInClubs to fetch.
   */
  orderBy?: Prisma.RoleInClubOrderByWithRelationInput | Prisma.RoleInClubOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RoleInClubs.
   */
  cursor?: Prisma.RoleInClubWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RoleInClubs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RoleInClubs.
   */
  skip?: number
  distinct?: Prisma.RoleInClubScalarFieldEnum | Prisma.RoleInClubScalarFieldEnum[]
}

/**
 * RoleInClub create
 */
export type RoleInClubCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleInClub
   */
  select?: Prisma.RoleInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleInClub
   */
  omit?: Prisma.RoleInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoleInClubInclude<ExtArgs> | null
  /**
   * The data needed to create a RoleInClub.
   */
  data: Prisma.XOR<Prisma.RoleInClubCreateInput, Prisma.RoleInClubUncheckedCreateInput>
}

/**
 * RoleInClub createMany
 */
export type RoleInClubCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RoleInClubs.
   */
  data: Prisma.RoleInClubCreateManyInput | Prisma.RoleInClubCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RoleInClub createManyAndReturn
 */
export type RoleInClubCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleInClub
   */
  select?: Prisma.RoleInClubSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RoleInClub
   */
  omit?: Prisma.RoleInClubOmit<ExtArgs> | null
  /**
   * The data used to create many RoleInClubs.
   */
  data: Prisma.RoleInClubCreateManyInput | Prisma.RoleInClubCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoleInClubIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RoleInClub update
 */
export type RoleInClubUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleInClub
   */
  select?: Prisma.RoleInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleInClub
   */
  omit?: Prisma.RoleInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoleInClubInclude<ExtArgs> | null
  /**
   * The data needed to update a RoleInClub.
   */
  data: Prisma.XOR<Prisma.RoleInClubUpdateInput, Prisma.RoleInClubUncheckedUpdateInput>
  /**
   * Choose, which RoleInClub to update.
   */
  where: Prisma.RoleInClubWhereUniqueInput
}

/**
 * RoleInClub updateMany
 */
export type RoleInClubUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RoleInClubs.
   */
  data: Prisma.XOR<Prisma.RoleInClubUpdateManyMutationInput, Prisma.RoleInClubUncheckedUpdateManyInput>
  /**
   * Filter which RoleInClubs to update
   */
  where?: Prisma.RoleInClubWhereInput
  /**
   * Limit how many RoleInClubs to update.
   */
  limit?: number
}

/**
 * RoleInClub updateManyAndReturn
 */
export type RoleInClubUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleInClub
   */
  select?: Prisma.RoleInClubSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RoleInClub
   */
  omit?: Prisma.RoleInClubOmit<ExtArgs> | null
  /**
   * The data used to update RoleInClubs.
   */
  data: Prisma.XOR<Prisma.RoleInClubUpdateManyMutationInput, Prisma.RoleInClubUncheckedUpdateManyInput>
  /**
   * Filter which RoleInClubs to update
   */
  where?: Prisma.RoleInClubWhereInput
  /**
   * Limit how many RoleInClubs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoleInClubIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RoleInClub upsert
 */
export type RoleInClubUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleInClub
   */
  select?: Prisma.RoleInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleInClub
   */
  omit?: Prisma.RoleInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoleInClubInclude<ExtArgs> | null
  /**
   * The filter to search for the RoleInClub to update in case it exists.
   */
  where: Prisma.RoleInClubWhereUniqueInput
  /**
   * In case the RoleInClub found by the `where` argument doesn't exist, create a new RoleInClub with this data.
   */
  create: Prisma.XOR<Prisma.RoleInClubCreateInput, Prisma.RoleInClubUncheckedCreateInput>
  /**
   * In case the RoleInClub was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RoleInClubUpdateInput, Prisma.RoleInClubUncheckedUpdateInput>
}

/**
 * RoleInClub delete
 */
export type RoleInClubDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleInClub
   */
  select?: Prisma.RoleInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleInClub
   */
  omit?: Prisma.RoleInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoleInClubInclude<ExtArgs> | null
  /**
   * Filter which RoleInClub to delete.
   */
  where: Prisma.RoleInClubWhereUniqueInput
}

/**
 * RoleInClub deleteMany
 */
export type RoleInClubDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RoleInClubs to delete
   */
  where?: Prisma.RoleInClubWhereInput
  /**
   * Limit how many RoleInClubs to delete.
   */
  limit?: number
}

/**
 * RoleInClub.members
 */
export type RoleInClub$membersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentInClub
   */
  select?: Prisma.StudentInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentInClub
   */
  omit?: Prisma.StudentInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInClubInclude<ExtArgs> | null
  where?: Prisma.StudentInClubWhereInput
  orderBy?: Prisma.StudentInClubOrderByWithRelationInput | Prisma.StudentInClubOrderByWithRelationInput[]
  cursor?: Prisma.StudentInClubWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.StudentInClubScalarFieldEnum | Prisma.StudentInClubScalarFieldEnum[]
}

/**
 * RoleInClub without action
 */
export type RoleInClubDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleInClub
   */
  select?: Prisma.RoleInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleInClub
   */
  omit?: Prisma.RoleInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoleInClubInclude<ExtArgs> | null
}
