
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StudentInClub` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model StudentInClub
 * 
 */
export type StudentInClubModel = runtime.Types.Result.DefaultSelection<Prisma.$StudentInClubPayload>

export type AggregateStudentInClub = {
  _count: StudentInClubCountAggregateOutputType | null
  _min: StudentInClubMinAggregateOutputType | null
  _max: StudentInClubMaxAggregateOutputType | null
}

export type StudentInClubMinAggregateOutputType = {
  id: string | null
  clubId: string | null
  studentId: string | null
  roleId: string | null
  status: $Enums.status | null
}

export type StudentInClubMaxAggregateOutputType = {
  id: string | null
  clubId: string | null
  studentId: string | null
  roleId: string | null
  status: $Enums.status | null
}

export type StudentInClubCountAggregateOutputType = {
  id: number
  clubId: number
  studentId: number
  roleId: number
  status: number
  _all: number
}


export type StudentInClubMinAggregateInputType = {
  id?: true
  clubId?: true
  studentId?: true
  roleId?: true
  status?: true
}

export type StudentInClubMaxAggregateInputType = {
  id?: true
  clubId?: true
  studentId?: true
  roleId?: true
  status?: true
}

export type StudentInClubCountAggregateInputType = {
  id?: true
  clubId?: true
  studentId?: true
  roleId?: true
  status?: true
  _all?: true
}

export type StudentInClubAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StudentInClub to aggregate.
   */
  where?: Prisma.StudentInClubWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudentInClubs to fetch.
   */
  orderBy?: Prisma.StudentInClubOrderByWithRelationInput | Prisma.StudentInClubOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StudentInClubWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudentInClubs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudentInClubs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StudentInClubs
  **/
  _count?: true | StudentInClubCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StudentInClubMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StudentInClubMaxAggregateInputType
}

export type GetStudentInClubAggregateType<T extends StudentInClubAggregateArgs> = {
      [P in keyof T & keyof AggregateStudentInClub]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStudentInClub[P]>
    : Prisma.GetScalarType<T[P], AggregateStudentInClub[P]>
}




export type StudentInClubGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StudentInClubWhereInput
  orderBy?: Prisma.StudentInClubOrderByWithAggregationInput | Prisma.StudentInClubOrderByWithAggregationInput[]
  by: Prisma.StudentInClubScalarFieldEnum[] | Prisma.StudentInClubScalarFieldEnum
  having?: Prisma.StudentInClubScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StudentInClubCountAggregateInputType | true
  _min?: StudentInClubMinAggregateInputType
  _max?: StudentInClubMaxAggregateInputType
}

export type StudentInClubGroupByOutputType = {
  id: string
  clubId: string
  studentId: string
  roleId: string
  status: $Enums.status
  _count: StudentInClubCountAggregateOutputType | null
  _min: StudentInClubMinAggregateOutputType | null
  _max: StudentInClubMaxAggregateOutputType | null
}

type GetStudentInClubGroupByPayload<T extends StudentInClubGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StudentInClubGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StudentInClubGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StudentInClubGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StudentInClubGroupByOutputType[P]>
      }
    >
  >



export type StudentInClubWhereInput = {
  AND?: Prisma.StudentInClubWhereInput | Prisma.StudentInClubWhereInput[]
  OR?: Prisma.StudentInClubWhereInput[]
  NOT?: Prisma.StudentInClubWhereInput | Prisma.StudentInClubWhereInput[]
  id?: Prisma.StringFilter<"StudentInClub"> | string
  clubId?: Prisma.StringFilter<"StudentInClub"> | string
  studentId?: Prisma.StringFilter<"StudentInClub"> | string
  roleId?: Prisma.StringFilter<"StudentInClub"> | string
  status?: Prisma.EnumstatusFilter<"StudentInClub"> | $Enums.status
  student?: Prisma.XOR<Prisma.StudentScalarRelationFilter, Prisma.StudentWhereInput>
  club?: Prisma.XOR<Prisma.ClubScalarRelationFilter, Prisma.ClubWhereInput>
  role?: Prisma.XOR<Prisma.RoleInClubScalarRelationFilter, Prisma.RoleInClubWhereInput>
}

export type StudentInClubOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  clubId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  student?: Prisma.StudentOrderByWithRelationInput
  club?: Prisma.ClubOrderByWithRelationInput
  role?: Prisma.RoleInClubOrderByWithRelationInput
}

export type StudentInClubWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  clubId_studentId?: Prisma.StudentInClubClubIdStudentIdCompoundUniqueInput
  AND?: Prisma.StudentInClubWhereInput | Prisma.StudentInClubWhereInput[]
  OR?: Prisma.StudentInClubWhereInput[]
  NOT?: Prisma.StudentInClubWhereInput | Prisma.StudentInClubWhereInput[]
  clubId?: Prisma.StringFilter<"StudentInClub"> | string
  studentId?: Prisma.StringFilter<"StudentInClub"> | string
  roleId?: Prisma.StringFilter<"StudentInClub"> | string
  status?: Prisma.EnumstatusFilter<"StudentInClub"> | $Enums.status
  student?: Prisma.XOR<Prisma.StudentScalarRelationFilter, Prisma.StudentWhereInput>
  club?: Prisma.XOR<Prisma.ClubScalarRelationFilter, Prisma.ClubWhereInput>
  role?: Prisma.XOR<Prisma.RoleInClubScalarRelationFilter, Prisma.RoleInClubWhereInput>
}, "id" | "clubId_studentId">

export type StudentInClubOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  clubId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  _count?: Prisma.StudentInClubCountOrderByAggregateInput
  _max?: Prisma.StudentInClubMaxOrderByAggregateInput
  _min?: Prisma.StudentInClubMinOrderByAggregateInput
}

export type StudentInClubScalarWhereWithAggregatesInput = {
  AND?: Prisma.StudentInClubScalarWhereWithAggregatesInput | Prisma.StudentInClubScalarWhereWithAggregatesInput[]
  OR?: Prisma.StudentInClubScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StudentInClubScalarWhereWithAggregatesInput | Prisma.StudentInClubScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"StudentInClub"> | string
  clubId?: Prisma.StringWithAggregatesFilter<"StudentInClub"> | string
  studentId?: Prisma.StringWithAggregatesFilter<"StudentInClub"> | string
  roleId?: Prisma.StringWithAggregatesFilter<"StudentInClub"> | string
  status?: Prisma.EnumstatusWithAggregatesFilter<"StudentInClub"> | $Enums.status
}

export type StudentInClubCreateInput = {
  id?: string
  status?: $Enums.status
  student: Prisma.StudentCreateNestedOneWithoutClubsInput
  club: Prisma.ClubCreateNestedOneWithoutStudentsInput
  role: Prisma.RoleInClubCreateNestedOneWithoutMembersInput
}

export type StudentInClubUncheckedCreateInput = {
  id?: string
  clubId: string
  studentId: string
  roleId: string
  status?: $Enums.status
}

export type StudentInClubUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumstatusFieldUpdateOperationsInput | $Enums.status
  student?: Prisma.StudentUpdateOneRequiredWithoutClubsNestedInput
  club?: Prisma.ClubUpdateOneRequiredWithoutStudentsNestedInput
  role?: Prisma.RoleInClubUpdateOneRequiredWithoutMembersNestedInput
}

export type StudentInClubUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clubId?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumstatusFieldUpdateOperationsInput | $Enums.status
}

export type StudentInClubCreateManyInput = {
  id?: string
  clubId: string
  studentId: string
  roleId: string
  status?: $Enums.status
}

export type StudentInClubUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumstatusFieldUpdateOperationsInput | $Enums.status
}

export type StudentInClubUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clubId?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumstatusFieldUpdateOperationsInput | $Enums.status
}

export type StudentInClubListRelationFilter = {
  every?: Prisma.StudentInClubWhereInput
  some?: Prisma.StudentInClubWhereInput
  none?: Prisma.StudentInClubWhereInput
}

export type StudentInClubOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StudentInClubClubIdStudentIdCompoundUniqueInput = {
  clubId: string
  studentId: string
}

export type StudentInClubCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clubId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type StudentInClubMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clubId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type StudentInClubMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clubId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type StudentInClubCreateNestedManyWithoutClubInput = {
  create?: Prisma.XOR<Prisma.StudentInClubCreateWithoutClubInput, Prisma.StudentInClubUncheckedCreateWithoutClubInput> | Prisma.StudentInClubCreateWithoutClubInput[] | Prisma.StudentInClubUncheckedCreateWithoutClubInput[]
  connectOrCreate?: Prisma.StudentInClubCreateOrConnectWithoutClubInput | Prisma.StudentInClubCreateOrConnectWithoutClubInput[]
  createMany?: Prisma.StudentInClubCreateManyClubInputEnvelope
  connect?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
}

export type StudentInClubUncheckedCreateNestedManyWithoutClubInput = {
  create?: Prisma.XOR<Prisma.StudentInClubCreateWithoutClubInput, Prisma.StudentInClubUncheckedCreateWithoutClubInput> | Prisma.StudentInClubCreateWithoutClubInput[] | Prisma.StudentInClubUncheckedCreateWithoutClubInput[]
  connectOrCreate?: Prisma.StudentInClubCreateOrConnectWithoutClubInput | Prisma.StudentInClubCreateOrConnectWithoutClubInput[]
  createMany?: Prisma.StudentInClubCreateManyClubInputEnvelope
  connect?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
}

export type StudentInClubUpdateManyWithoutClubNestedInput = {
  create?: Prisma.XOR<Prisma.StudentInClubCreateWithoutClubInput, Prisma.StudentInClubUncheckedCreateWithoutClubInput> | Prisma.StudentInClubCreateWithoutClubInput[] | Prisma.StudentInClubUncheckedCreateWithoutClubInput[]
  connectOrCreate?: Prisma.StudentInClubCreateOrConnectWithoutClubInput | Prisma.StudentInClubCreateOrConnectWithoutClubInput[]
  upsert?: Prisma.StudentInClubUpsertWithWhereUniqueWithoutClubInput | Prisma.StudentInClubUpsertWithWhereUniqueWithoutClubInput[]
  createMany?: Prisma.StudentInClubCreateManyClubInputEnvelope
  set?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  disconnect?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  delete?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  connect?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  update?: Prisma.StudentInClubUpdateWithWhereUniqueWithoutClubInput | Prisma.StudentInClubUpdateWithWhereUniqueWithoutClubInput[]
  updateMany?: Prisma.StudentInClubUpdateManyWithWhereWithoutClubInput | Prisma.StudentInClubUpdateManyWithWhereWithoutClubInput[]
  deleteMany?: Prisma.StudentInClubScalarWhereInput | Prisma.StudentInClubScalarWhereInput[]
}

export type StudentInClubUncheckedUpdateManyWithoutClubNestedInput = {
  create?: Prisma.XOR<Prisma.StudentInClubCreateWithoutClubInput, Prisma.StudentInClubUncheckedCreateWithoutClubInput> | Prisma.StudentInClubCreateWithoutClubInput[] | Prisma.StudentInClubUncheckedCreateWithoutClubInput[]
  connectOrCreate?: Prisma.StudentInClubCreateOrConnectWithoutClubInput | Prisma.StudentInClubCreateOrConnectWithoutClubInput[]
  upsert?: Prisma.StudentInClubUpsertWithWhereUniqueWithoutClubInput | Prisma.StudentInClubUpsertWithWhereUniqueWithoutClubInput[]
  createMany?: Prisma.StudentInClubCreateManyClubInputEnvelope
  set?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  disconnect?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  delete?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  connect?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  update?: Prisma.StudentInClubUpdateWithWhereUniqueWithoutClubInput | Prisma.StudentInClubUpdateWithWhereUniqueWithoutClubInput[]
  updateMany?: Prisma.StudentInClubUpdateManyWithWhereWithoutClubInput | Prisma.StudentInClubUpdateManyWithWhereWithoutClubInput[]
  deleteMany?: Prisma.StudentInClubScalarWhereInput | Prisma.StudentInClubScalarWhereInput[]
}

export type StudentInClubCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.StudentInClubCreateWithoutStudentInput, Prisma.StudentInClubUncheckedCreateWithoutStudentInput> | Prisma.StudentInClubCreateWithoutStudentInput[] | Prisma.StudentInClubUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.StudentInClubCreateOrConnectWithoutStudentInput | Prisma.StudentInClubCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.StudentInClubCreateManyStudentInputEnvelope
  connect?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
}

export type StudentInClubUncheckedCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.StudentInClubCreateWithoutStudentInput, Prisma.StudentInClubUncheckedCreateWithoutStudentInput> | Prisma.StudentInClubCreateWithoutStudentInput[] | Prisma.StudentInClubUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.StudentInClubCreateOrConnectWithoutStudentInput | Prisma.StudentInClubCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.StudentInClubCreateManyStudentInputEnvelope
  connect?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
}

export type StudentInClubUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.StudentInClubCreateWithoutStudentInput, Prisma.StudentInClubUncheckedCreateWithoutStudentInput> | Prisma.StudentInClubCreateWithoutStudentInput[] | Prisma.StudentInClubUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.StudentInClubCreateOrConnectWithoutStudentInput | Prisma.StudentInClubCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.StudentInClubUpsertWithWhereUniqueWithoutStudentInput | Prisma.StudentInClubUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.StudentInClubCreateManyStudentInputEnvelope
  set?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  disconnect?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  delete?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  connect?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  update?: Prisma.StudentInClubUpdateWithWhereUniqueWithoutStudentInput | Prisma.StudentInClubUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.StudentInClubUpdateManyWithWhereWithoutStudentInput | Prisma.StudentInClubUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.StudentInClubScalarWhereInput | Prisma.StudentInClubScalarWhereInput[]
}

export type StudentInClubUncheckedUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.StudentInClubCreateWithoutStudentInput, Prisma.StudentInClubUncheckedCreateWithoutStudentInput> | Prisma.StudentInClubCreateWithoutStudentInput[] | Prisma.StudentInClubUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.StudentInClubCreateOrConnectWithoutStudentInput | Prisma.StudentInClubCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.StudentInClubUpsertWithWhereUniqueWithoutStudentInput | Prisma.StudentInClubUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.StudentInClubCreateManyStudentInputEnvelope
  set?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  disconnect?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  delete?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  connect?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  update?: Prisma.StudentInClubUpdateWithWhereUniqueWithoutStudentInput | Prisma.StudentInClubUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.StudentInClubUpdateManyWithWhereWithoutStudentInput | Prisma.StudentInClubUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.StudentInClubScalarWhereInput | Prisma.StudentInClubScalarWhereInput[]
}

export type EnumstatusFieldUpdateOperationsInput = {
  set?: $Enums.status
}

export type StudentInClubCreateNestedManyWithoutRoleInput = {
  create?: Prisma.XOR<Prisma.StudentInClubCreateWithoutRoleInput, Prisma.StudentInClubUncheckedCreateWithoutRoleInput> | Prisma.StudentInClubCreateWithoutRoleInput[] | Prisma.StudentInClubUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.StudentInClubCreateOrConnectWithoutRoleInput | Prisma.StudentInClubCreateOrConnectWithoutRoleInput[]
  createMany?: Prisma.StudentInClubCreateManyRoleInputEnvelope
  connect?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
}

export type StudentInClubUncheckedCreateNestedManyWithoutRoleInput = {
  create?: Prisma.XOR<Prisma.StudentInClubCreateWithoutRoleInput, Prisma.StudentInClubUncheckedCreateWithoutRoleInput> | Prisma.StudentInClubCreateWithoutRoleInput[] | Prisma.StudentInClubUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.StudentInClubCreateOrConnectWithoutRoleInput | Prisma.StudentInClubCreateOrConnectWithoutRoleInput[]
  createMany?: Prisma.StudentInClubCreateManyRoleInputEnvelope
  connect?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
}

export type StudentInClubUpdateManyWithoutRoleNestedInput = {
  create?: Prisma.XOR<Prisma.StudentInClubCreateWithoutRoleInput, Prisma.StudentInClubUncheckedCreateWithoutRoleInput> | Prisma.StudentInClubCreateWithoutRoleInput[] | Prisma.StudentInClubUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.StudentInClubCreateOrConnectWithoutRoleInput | Prisma.StudentInClubCreateOrConnectWithoutRoleInput[]
  upsert?: Prisma.StudentInClubUpsertWithWhereUniqueWithoutRoleInput | Prisma.StudentInClubUpsertWithWhereUniqueWithoutRoleInput[]
  createMany?: Prisma.StudentInClubCreateManyRoleInputEnvelope
  set?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  disconnect?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  delete?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  connect?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  update?: Prisma.StudentInClubUpdateWithWhereUniqueWithoutRoleInput | Prisma.StudentInClubUpdateWithWhereUniqueWithoutRoleInput[]
  updateMany?: Prisma.StudentInClubUpdateManyWithWhereWithoutRoleInput | Prisma.StudentInClubUpdateManyWithWhereWithoutRoleInput[]
  deleteMany?: Prisma.StudentInClubScalarWhereInput | Prisma.StudentInClubScalarWhereInput[]
}

export type StudentInClubUncheckedUpdateManyWithoutRoleNestedInput = {
  create?: Prisma.XOR<Prisma.StudentInClubCreateWithoutRoleInput, Prisma.StudentInClubUncheckedCreateWithoutRoleInput> | Prisma.StudentInClubCreateWithoutRoleInput[] | Prisma.StudentInClubUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.StudentInClubCreateOrConnectWithoutRoleInput | Prisma.StudentInClubCreateOrConnectWithoutRoleInput[]
  upsert?: Prisma.StudentInClubUpsertWithWhereUniqueWithoutRoleInput | Prisma.StudentInClubUpsertWithWhereUniqueWithoutRoleInput[]
  createMany?: Prisma.StudentInClubCreateManyRoleInputEnvelope
  set?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  disconnect?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  delete?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  connect?: Prisma.StudentInClubWhereUniqueInput | Prisma.StudentInClubWhereUniqueInput[]
  update?: Prisma.StudentInClubUpdateWithWhereUniqueWithoutRoleInput | Prisma.StudentInClubUpdateWithWhereUniqueWithoutRoleInput[]
  updateMany?: Prisma.StudentInClubUpdateManyWithWhereWithoutRoleInput | Prisma.StudentInClubUpdateManyWithWhereWithoutRoleInput[]
  deleteMany?: Prisma.StudentInClubScalarWhereInput | Prisma.StudentInClubScalarWhereInput[]
}

export type StudentInClubCreateWithoutClubInput = {
  id?: string
  status?: $Enums.status
  student: Prisma.StudentCreateNestedOneWithoutClubsInput
  role: Prisma.RoleInClubCreateNestedOneWithoutMembersInput
}

export type StudentInClubUncheckedCreateWithoutClubInput = {
  id?: string
  studentId: string
  roleId: string
  status?: $Enums.status
}

export type StudentInClubCreateOrConnectWithoutClubInput = {
  where: Prisma.StudentInClubWhereUniqueInput
  create: Prisma.XOR<Prisma.StudentInClubCreateWithoutClubInput, Prisma.StudentInClubUncheckedCreateWithoutClubInput>
}

export type StudentInClubCreateManyClubInputEnvelope = {
  data: Prisma.StudentInClubCreateManyClubInput | Prisma.StudentInClubCreateManyClubInput[]
  skipDuplicates?: boolean
}

export type StudentInClubUpsertWithWhereUniqueWithoutClubInput = {
  where: Prisma.StudentInClubWhereUniqueInput
  update: Prisma.XOR<Prisma.StudentInClubUpdateWithoutClubInput, Prisma.StudentInClubUncheckedUpdateWithoutClubInput>
  create: Prisma.XOR<Prisma.StudentInClubCreateWithoutClubInput, Prisma.StudentInClubUncheckedCreateWithoutClubInput>
}

export type StudentInClubUpdateWithWhereUniqueWithoutClubInput = {
  where: Prisma.StudentInClubWhereUniqueInput
  data: Prisma.XOR<Prisma.StudentInClubUpdateWithoutClubInput, Prisma.StudentInClubUncheckedUpdateWithoutClubInput>
}

export type StudentInClubUpdateManyWithWhereWithoutClubInput = {
  where: Prisma.StudentInClubScalarWhereInput
  data: Prisma.XOR<Prisma.StudentInClubUpdateManyMutationInput, Prisma.StudentInClubUncheckedUpdateManyWithoutClubInput>
}

export type StudentInClubScalarWhereInput = {
  AND?: Prisma.StudentInClubScalarWhereInput | Prisma.StudentInClubScalarWhereInput[]
  OR?: Prisma.StudentInClubScalarWhereInput[]
  NOT?: Prisma.StudentInClubScalarWhereInput | Prisma.StudentInClubScalarWhereInput[]
  id?: Prisma.StringFilter<"StudentInClub"> | string
  clubId?: Prisma.StringFilter<"StudentInClub"> | string
  studentId?: Prisma.StringFilter<"StudentInClub"> | string
  roleId?: Prisma.StringFilter<"StudentInClub"> | string
  status?: Prisma.EnumstatusFilter<"StudentInClub"> | $Enums.status
}

export type StudentInClubCreateWithoutStudentInput = {
  id?: string
  status?: $Enums.status
  club: Prisma.ClubCreateNestedOneWithoutStudentsInput
  role: Prisma.RoleInClubCreateNestedOneWithoutMembersInput
}

export type StudentInClubUncheckedCreateWithoutStudentInput = {
  id?: string
  clubId: string
  roleId: string
  status?: $Enums.status
}

export type StudentInClubCreateOrConnectWithoutStudentInput = {
  where: Prisma.StudentInClubWhereUniqueInput
  create: Prisma.XOR<Prisma.StudentInClubCreateWithoutStudentInput, Prisma.StudentInClubUncheckedCreateWithoutStudentInput>
}

export type StudentInClubCreateManyStudentInputEnvelope = {
  data: Prisma.StudentInClubCreateManyStudentInput | Prisma.StudentInClubCreateManyStudentInput[]
  skipDuplicates?: boolean
}

export type StudentInClubUpsertWithWhereUniqueWithoutStudentInput = {
  where: Prisma.StudentInClubWhereUniqueInput
  update: Prisma.XOR<Prisma.StudentInClubUpdateWithoutStudentInput, Prisma.StudentInClubUncheckedUpdateWithoutStudentInput>
  create: Prisma.XOR<Prisma.StudentInClubCreateWithoutStudentInput, Prisma.StudentInClubUncheckedCreateWithoutStudentInput>
}

export type StudentInClubUpdateWithWhereUniqueWithoutStudentInput = {
  where: Prisma.StudentInClubWhereUniqueInput
  data: Prisma.XOR<Prisma.StudentInClubUpdateWithoutStudentInput, Prisma.StudentInClubUncheckedUpdateWithoutStudentInput>
}

export type StudentInClubUpdateManyWithWhereWithoutStudentInput = {
  where: Prisma.StudentInClubScalarWhereInput
  data: Prisma.XOR<Prisma.StudentInClubUpdateManyMutationInput, Prisma.StudentInClubUncheckedUpdateManyWithoutStudentInput>
}

export type StudentInClubCreateWithoutRoleInput = {
  id?: string
  status?: $Enums.status
  student: Prisma.StudentCreateNestedOneWithoutClubsInput
  club: Prisma.ClubCreateNestedOneWithoutStudentsInput
}

export type StudentInClubUncheckedCreateWithoutRoleInput = {
  id?: string
  clubId: string
  studentId: string
  status?: $Enums.status
}

export type StudentInClubCreateOrConnectWithoutRoleInput = {
  where: Prisma.StudentInClubWhereUniqueInput
  create: Prisma.XOR<Prisma.StudentInClubCreateWithoutRoleInput, Prisma.StudentInClubUncheckedCreateWithoutRoleInput>
}

export type StudentInClubCreateManyRoleInputEnvelope = {
  data: Prisma.StudentInClubCreateManyRoleInput | Prisma.StudentInClubCreateManyRoleInput[]
  skipDuplicates?: boolean
}

export type StudentInClubUpsertWithWhereUniqueWithoutRoleInput = {
  where: Prisma.StudentInClubWhereUniqueInput
  update: Prisma.XOR<Prisma.StudentInClubUpdateWithoutRoleInput, Prisma.StudentInClubUncheckedUpdateWithoutRoleInput>
  create: Prisma.XOR<Prisma.StudentInClubCreateWithoutRoleInput, Prisma.StudentInClubUncheckedCreateWithoutRoleInput>
}

export type StudentInClubUpdateWithWhereUniqueWithoutRoleInput = {
  where: Prisma.StudentInClubWhereUniqueInput
  data: Prisma.XOR<Prisma.StudentInClubUpdateWithoutRoleInput, Prisma.StudentInClubUncheckedUpdateWithoutRoleInput>
}

export type StudentInClubUpdateManyWithWhereWithoutRoleInput = {
  where: Prisma.StudentInClubScalarWhereInput
  data: Prisma.XOR<Prisma.StudentInClubUpdateManyMutationInput, Prisma.StudentInClubUncheckedUpdateManyWithoutRoleInput>
}

export type StudentInClubCreateManyClubInput = {
  id?: string
  studentId: string
  roleId: string
  status?: $Enums.status
}

export type StudentInClubUpdateWithoutClubInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumstatusFieldUpdateOperationsInput | $Enums.status
  student?: Prisma.StudentUpdateOneRequiredWithoutClubsNestedInput
  role?: Prisma.RoleInClubUpdateOneRequiredWithoutMembersNestedInput
}

export type StudentInClubUncheckedUpdateWithoutClubInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumstatusFieldUpdateOperationsInput | $Enums.status
}

export type StudentInClubUncheckedUpdateManyWithoutClubInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumstatusFieldUpdateOperationsInput | $Enums.status
}

export type StudentInClubCreateManyStudentInput = {
  id?: string
  clubId: string
  roleId: string
  status?: $Enums.status
}

export type StudentInClubUpdateWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumstatusFieldUpdateOperationsInput | $Enums.status
  club?: Prisma.ClubUpdateOneRequiredWithoutStudentsNestedInput
  role?: Prisma.RoleInClubUpdateOneRequiredWithoutMembersNestedInput
}

export type StudentInClubUncheckedUpdateWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clubId?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumstatusFieldUpdateOperationsInput | $Enums.status
}

export type StudentInClubUncheckedUpdateManyWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clubId?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumstatusFieldUpdateOperationsInput | $Enums.status
}

export type StudentInClubCreateManyRoleInput = {
  id?: string
  clubId: string
  studentId: string
  status?: $Enums.status
}

export type StudentInClubUpdateWithoutRoleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumstatusFieldUpdateOperationsInput | $Enums.status
  student?: Prisma.StudentUpdateOneRequiredWithoutClubsNestedInput
  club?: Prisma.ClubUpdateOneRequiredWithoutStudentsNestedInput
}

export type StudentInClubUncheckedUpdateWithoutRoleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clubId?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumstatusFieldUpdateOperationsInput | $Enums.status
}

export type StudentInClubUncheckedUpdateManyWithoutRoleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clubId?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumstatusFieldUpdateOperationsInput | $Enums.status
}



export type StudentInClubSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clubId?: boolean
  studentId?: boolean
  roleId?: boolean
  status?: boolean
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  club?: boolean | Prisma.ClubDefaultArgs<ExtArgs>
  role?: boolean | Prisma.RoleInClubDefaultArgs<ExtArgs>
}, ExtArgs["result"]["studentInClub"]>

export type StudentInClubSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clubId?: boolean
  studentId?: boolean
  roleId?: boolean
  status?: boolean
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  club?: boolean | Prisma.ClubDefaultArgs<ExtArgs>
  role?: boolean | Prisma.RoleInClubDefaultArgs<ExtArgs>
}, ExtArgs["result"]["studentInClub"]>

export type StudentInClubSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clubId?: boolean
  studentId?: boolean
  roleId?: boolean
  status?: boolean
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  club?: boolean | Prisma.ClubDefaultArgs<ExtArgs>
  role?: boolean | Prisma.RoleInClubDefaultArgs<ExtArgs>
}, ExtArgs["result"]["studentInClub"]>

export type StudentInClubSelectScalar = {
  id?: boolean
  clubId?: boolean
  studentId?: boolean
  roleId?: boolean
  status?: boolean
}

export type StudentInClubOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "clubId" | "studentId" | "roleId" | "status", ExtArgs["result"]["studentInClub"]>
export type StudentInClubInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  club?: boolean | Prisma.ClubDefaultArgs<ExtArgs>
  role?: boolean | Prisma.RoleInClubDefaultArgs<ExtArgs>
}
export type StudentInClubIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  club?: boolean | Prisma.ClubDefaultArgs<ExtArgs>
  role?: boolean | Prisma.RoleInClubDefaultArgs<ExtArgs>
}
export type StudentInClubIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  club?: boolean | Prisma.ClubDefaultArgs<ExtArgs>
  role?: boolean | Prisma.RoleInClubDefaultArgs<ExtArgs>
}

export type $StudentInClubPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StudentInClub"
  objects: {
    student: Prisma.$StudentPayload<ExtArgs>
    club: Prisma.$ClubPayload<ExtArgs>
    role: Prisma.$RoleInClubPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    clubId: string
    studentId: string
    roleId: string
    status: $Enums.status
  }, ExtArgs["result"]["studentInClub"]>
  composites: {}
}

export type StudentInClubGetPayload<S extends boolean | null | undefined | StudentInClubDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StudentInClubPayload, S>

export type StudentInClubCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StudentInClubFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StudentInClubCountAggregateInputType | true
  }

export interface StudentInClubDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StudentInClub'], meta: { name: 'StudentInClub' } }
  /**
   * Find zero or one StudentInClub that matches the filter.
   * @param {StudentInClubFindUniqueArgs} args - Arguments to find a StudentInClub
   * @example
   * // Get one StudentInClub
   * const studentInClub = await prisma.studentInClub.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StudentInClubFindUniqueArgs>(args: Prisma.SelectSubset<T, StudentInClubFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StudentInClubClient<runtime.Types.Result.GetResult<Prisma.$StudentInClubPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StudentInClub that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StudentInClubFindUniqueOrThrowArgs} args - Arguments to find a StudentInClub
   * @example
   * // Get one StudentInClub
   * const studentInClub = await prisma.studentInClub.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StudentInClubFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StudentInClubFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StudentInClubClient<runtime.Types.Result.GetResult<Prisma.$StudentInClubPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StudentInClub that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentInClubFindFirstArgs} args - Arguments to find a StudentInClub
   * @example
   * // Get one StudentInClub
   * const studentInClub = await prisma.studentInClub.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StudentInClubFindFirstArgs>(args?: Prisma.SelectSubset<T, StudentInClubFindFirstArgs<ExtArgs>>): Prisma.Prisma__StudentInClubClient<runtime.Types.Result.GetResult<Prisma.$StudentInClubPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StudentInClub that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentInClubFindFirstOrThrowArgs} args - Arguments to find a StudentInClub
   * @example
   * // Get one StudentInClub
   * const studentInClub = await prisma.studentInClub.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StudentInClubFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StudentInClubFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StudentInClubClient<runtime.Types.Result.GetResult<Prisma.$StudentInClubPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StudentInClubs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentInClubFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StudentInClubs
   * const studentInClubs = await prisma.studentInClub.findMany()
   * 
   * // Get first 10 StudentInClubs
   * const studentInClubs = await prisma.studentInClub.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const studentInClubWithIdOnly = await prisma.studentInClub.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StudentInClubFindManyArgs>(args?: Prisma.SelectSubset<T, StudentInClubFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudentInClubPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StudentInClub.
   * @param {StudentInClubCreateArgs} args - Arguments to create a StudentInClub.
   * @example
   * // Create one StudentInClub
   * const StudentInClub = await prisma.studentInClub.create({
   *   data: {
   *     // ... data to create a StudentInClub
   *   }
   * })
   * 
   */
  create<T extends StudentInClubCreateArgs>(args: Prisma.SelectSubset<T, StudentInClubCreateArgs<ExtArgs>>): Prisma.Prisma__StudentInClubClient<runtime.Types.Result.GetResult<Prisma.$StudentInClubPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StudentInClubs.
   * @param {StudentInClubCreateManyArgs} args - Arguments to create many StudentInClubs.
   * @example
   * // Create many StudentInClubs
   * const studentInClub = await prisma.studentInClub.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StudentInClubCreateManyArgs>(args?: Prisma.SelectSubset<T, StudentInClubCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StudentInClubs and returns the data saved in the database.
   * @param {StudentInClubCreateManyAndReturnArgs} args - Arguments to create many StudentInClubs.
   * @example
   * // Create many StudentInClubs
   * const studentInClub = await prisma.studentInClub.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StudentInClubs and only return the `id`
   * const studentInClubWithIdOnly = await prisma.studentInClub.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StudentInClubCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StudentInClubCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudentInClubPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StudentInClub.
   * @param {StudentInClubDeleteArgs} args - Arguments to delete one StudentInClub.
   * @example
   * // Delete one StudentInClub
   * const StudentInClub = await prisma.studentInClub.delete({
   *   where: {
   *     // ... filter to delete one StudentInClub
   *   }
   * })
   * 
   */
  delete<T extends StudentInClubDeleteArgs>(args: Prisma.SelectSubset<T, StudentInClubDeleteArgs<ExtArgs>>): Prisma.Prisma__StudentInClubClient<runtime.Types.Result.GetResult<Prisma.$StudentInClubPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StudentInClub.
   * @param {StudentInClubUpdateArgs} args - Arguments to update one StudentInClub.
   * @example
   * // Update one StudentInClub
   * const studentInClub = await prisma.studentInClub.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StudentInClubUpdateArgs>(args: Prisma.SelectSubset<T, StudentInClubUpdateArgs<ExtArgs>>): Prisma.Prisma__StudentInClubClient<runtime.Types.Result.GetResult<Prisma.$StudentInClubPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StudentInClubs.
   * @param {StudentInClubDeleteManyArgs} args - Arguments to filter StudentInClubs to delete.
   * @example
   * // Delete a few StudentInClubs
   * const { count } = await prisma.studentInClub.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StudentInClubDeleteManyArgs>(args?: Prisma.SelectSubset<T, StudentInClubDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StudentInClubs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentInClubUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StudentInClubs
   * const studentInClub = await prisma.studentInClub.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StudentInClubUpdateManyArgs>(args: Prisma.SelectSubset<T, StudentInClubUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StudentInClubs and returns the data updated in the database.
   * @param {StudentInClubUpdateManyAndReturnArgs} args - Arguments to update many StudentInClubs.
   * @example
   * // Update many StudentInClubs
   * const studentInClub = await prisma.studentInClub.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StudentInClubs and only return the `id`
   * const studentInClubWithIdOnly = await prisma.studentInClub.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StudentInClubUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StudentInClubUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudentInClubPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StudentInClub.
   * @param {StudentInClubUpsertArgs} args - Arguments to update or create a StudentInClub.
   * @example
   * // Update or create a StudentInClub
   * const studentInClub = await prisma.studentInClub.upsert({
   *   create: {
   *     // ... data to create a StudentInClub
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StudentInClub we want to update
   *   }
   * })
   */
  upsert<T extends StudentInClubUpsertArgs>(args: Prisma.SelectSubset<T, StudentInClubUpsertArgs<ExtArgs>>): Prisma.Prisma__StudentInClubClient<runtime.Types.Result.GetResult<Prisma.$StudentInClubPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StudentInClubs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentInClubCountArgs} args - Arguments to filter StudentInClubs to count.
   * @example
   * // Count the number of StudentInClubs
   * const count = await prisma.studentInClub.count({
   *   where: {
   *     // ... the filter for the StudentInClubs we want to count
   *   }
   * })
  **/
  count<T extends StudentInClubCountArgs>(
    args?: Prisma.Subset<T, StudentInClubCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StudentInClubCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StudentInClub.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentInClubAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StudentInClubAggregateArgs>(args: Prisma.Subset<T, StudentInClubAggregateArgs>): Prisma.PrismaPromise<GetStudentInClubAggregateType<T>>

  /**
   * Group by StudentInClub.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentInClubGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StudentInClubGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StudentInClubGroupByArgs['orderBy'] }
      : { orderBy?: StudentInClubGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StudentInClubGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStudentInClubGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StudentInClub model
 */
readonly fields: StudentInClubFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StudentInClub.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StudentInClubClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  student<T extends Prisma.StudentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StudentDefaultArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  club<T extends Prisma.ClubDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ClubDefaultArgs<ExtArgs>>): Prisma.Prisma__ClubClient<runtime.Types.Result.GetResult<Prisma.$ClubPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  role<T extends Prisma.RoleInClubDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RoleInClubDefaultArgs<ExtArgs>>): Prisma.Prisma__RoleInClubClient<runtime.Types.Result.GetResult<Prisma.$RoleInClubPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StudentInClub model
 */
export interface StudentInClubFieldRefs {
  readonly id: Prisma.FieldRef<"StudentInClub", 'String'>
  readonly clubId: Prisma.FieldRef<"StudentInClub", 'String'>
  readonly studentId: Prisma.FieldRef<"StudentInClub", 'String'>
  readonly roleId: Prisma.FieldRef<"StudentInClub", 'String'>
  readonly status: Prisma.FieldRef<"StudentInClub", 'status'>
}
    

// Custom InputTypes
/**
 * StudentInClub findUnique
 */
export type StudentInClubFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentInClub
   */
  select?: Prisma.StudentInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentInClub
   */
  omit?: Prisma.StudentInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInClubInclude<ExtArgs> | null
  /**
   * Filter, which StudentInClub to fetch.
   */
  where: Prisma.StudentInClubWhereUniqueInput
}

/**
 * StudentInClub findUniqueOrThrow
 */
export type StudentInClubFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentInClub
   */
  select?: Prisma.StudentInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentInClub
   */
  omit?: Prisma.StudentInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInClubInclude<ExtArgs> | null
  /**
   * Filter, which StudentInClub to fetch.
   */
  where: Prisma.StudentInClubWhereUniqueInput
}

/**
 * StudentInClub findFirst
 */
export type StudentInClubFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentInClub
   */
  select?: Prisma.StudentInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentInClub
   */
  omit?: Prisma.StudentInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInClubInclude<ExtArgs> | null
  /**
   * Filter, which StudentInClub to fetch.
   */
  where?: Prisma.StudentInClubWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudentInClubs to fetch.
   */
  orderBy?: Prisma.StudentInClubOrderByWithRelationInput | Prisma.StudentInClubOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StudentInClubs.
   */
  cursor?: Prisma.StudentInClubWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudentInClubs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudentInClubs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StudentInClubs.
   */
  distinct?: Prisma.StudentInClubScalarFieldEnum | Prisma.StudentInClubScalarFieldEnum[]
}

/**
 * StudentInClub findFirstOrThrow
 */
export type StudentInClubFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentInClub
   */
  select?: Prisma.StudentInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentInClub
   */
  omit?: Prisma.StudentInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInClubInclude<ExtArgs> | null
  /**
   * Filter, which StudentInClub to fetch.
   */
  where?: Prisma.StudentInClubWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudentInClubs to fetch.
   */
  orderBy?: Prisma.StudentInClubOrderByWithRelationInput | Prisma.StudentInClubOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StudentInClubs.
   */
  cursor?: Prisma.StudentInClubWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudentInClubs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudentInClubs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StudentInClubs.
   */
  distinct?: Prisma.StudentInClubScalarFieldEnum | Prisma.StudentInClubScalarFieldEnum[]
}

/**
 * StudentInClub findMany
 */
export type StudentInClubFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentInClub
   */
  select?: Prisma.StudentInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentInClub
   */
  omit?: Prisma.StudentInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInClubInclude<ExtArgs> | null
  /**
   * Filter, which StudentInClubs to fetch.
   */
  where?: Prisma.StudentInClubWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudentInClubs to fetch.
   */
  orderBy?: Prisma.StudentInClubOrderByWithRelationInput | Prisma.StudentInClubOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StudentInClubs.
   */
  cursor?: Prisma.StudentInClubWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudentInClubs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudentInClubs.
   */
  skip?: number
  distinct?: Prisma.StudentInClubScalarFieldEnum | Prisma.StudentInClubScalarFieldEnum[]
}

/**
 * StudentInClub create
 */
export type StudentInClubCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentInClub
   */
  select?: Prisma.StudentInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentInClub
   */
  omit?: Prisma.StudentInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInClubInclude<ExtArgs> | null
  /**
   * The data needed to create a StudentInClub.
   */
  data: Prisma.XOR<Prisma.StudentInClubCreateInput, Prisma.StudentInClubUncheckedCreateInput>
}

/**
 * StudentInClub createMany
 */
export type StudentInClubCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StudentInClubs.
   */
  data: Prisma.StudentInClubCreateManyInput | Prisma.StudentInClubCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StudentInClub createManyAndReturn
 */
export type StudentInClubCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentInClub
   */
  select?: Prisma.StudentInClubSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StudentInClub
   */
  omit?: Prisma.StudentInClubOmit<ExtArgs> | null
  /**
   * The data used to create many StudentInClubs.
   */
  data: Prisma.StudentInClubCreateManyInput | Prisma.StudentInClubCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInClubIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * StudentInClub update
 */
export type StudentInClubUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentInClub
   */
  select?: Prisma.StudentInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentInClub
   */
  omit?: Prisma.StudentInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInClubInclude<ExtArgs> | null
  /**
   * The data needed to update a StudentInClub.
   */
  data: Prisma.XOR<Prisma.StudentInClubUpdateInput, Prisma.StudentInClubUncheckedUpdateInput>
  /**
   * Choose, which StudentInClub to update.
   */
  where: Prisma.StudentInClubWhereUniqueInput
}

/**
 * StudentInClub updateMany
 */
export type StudentInClubUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StudentInClubs.
   */
  data: Prisma.XOR<Prisma.StudentInClubUpdateManyMutationInput, Prisma.StudentInClubUncheckedUpdateManyInput>
  /**
   * Filter which StudentInClubs to update
   */
  where?: Prisma.StudentInClubWhereInput
  /**
   * Limit how many StudentInClubs to update.
   */
  limit?: number
}

/**
 * StudentInClub updateManyAndReturn
 */
export type StudentInClubUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentInClub
   */
  select?: Prisma.StudentInClubSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StudentInClub
   */
  omit?: Prisma.StudentInClubOmit<ExtArgs> | null
  /**
   * The data used to update StudentInClubs.
   */
  data: Prisma.XOR<Prisma.StudentInClubUpdateManyMutationInput, Prisma.StudentInClubUncheckedUpdateManyInput>
  /**
   * Filter which StudentInClubs to update
   */
  where?: Prisma.StudentInClubWhereInput
  /**
   * Limit how many StudentInClubs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInClubIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * StudentInClub upsert
 */
export type StudentInClubUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentInClub
   */
  select?: Prisma.StudentInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentInClub
   */
  omit?: Prisma.StudentInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInClubInclude<ExtArgs> | null
  /**
   * The filter to search for the StudentInClub to update in case it exists.
   */
  where: Prisma.StudentInClubWhereUniqueInput
  /**
   * In case the StudentInClub found by the `where` argument doesn't exist, create a new StudentInClub with this data.
   */
  create: Prisma.XOR<Prisma.StudentInClubCreateInput, Prisma.StudentInClubUncheckedCreateInput>
  /**
   * In case the StudentInClub was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StudentInClubUpdateInput, Prisma.StudentInClubUncheckedUpdateInput>
}

/**
 * StudentInClub delete
 */
export type StudentInClubDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentInClub
   */
  select?: Prisma.StudentInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentInClub
   */
  omit?: Prisma.StudentInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInClubInclude<ExtArgs> | null
  /**
   * Filter which StudentInClub to delete.
   */
  where: Prisma.StudentInClubWhereUniqueInput
}

/**
 * StudentInClub deleteMany
 */
export type StudentInClubDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StudentInClubs to delete
   */
  where?: Prisma.StudentInClubWhereInput
  /**
   * Limit how many StudentInClubs to delete.
   */
  limit?: number
}

/**
 * StudentInClub without action
 */
export type StudentInClubDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentInClub
   */
  select?: Prisma.StudentInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentInClub
   */
  omit?: Prisma.StudentInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInClubInclude<ExtArgs> | null
}
