
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Student` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Student
 * 
 */
export type StudentModel = runtime.Types.Result.DefaultSelection<Prisma.$StudentPayload>

export type AggregateStudent = {
  _count: StudentCountAggregateOutputType | null
  _min: StudentMinAggregateOutputType | null
  _max: StudentMaxAggregateOutputType | null
}

export type StudentMinAggregateOutputType = {
  id: string | null
  firstName: string | null
  lastName: string | null
  email: string | null
  password: string | null
  rollnumber: string | null
  collegeId: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
  otp: string | null
  otpExpiry: Date | null
  verified: boolean | null
}

export type StudentMaxAggregateOutputType = {
  id: string | null
  firstName: string | null
  lastName: string | null
  email: string | null
  password: string | null
  rollnumber: string | null
  collegeId: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
  otp: string | null
  otpExpiry: Date | null
  verified: boolean | null
}

export type StudentCountAggregateOutputType = {
  id: number
  firstName: number
  lastName: number
  email: number
  password: number
  rollnumber: number
  collegeId: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  otp: number
  otpExpiry: number
  verified: number
  _all: number
}


export type StudentMinAggregateInputType = {
  id?: true
  firstName?: true
  lastName?: true
  email?: true
  password?: true
  rollnumber?: true
  collegeId?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  otp?: true
  otpExpiry?: true
  verified?: true
}

export type StudentMaxAggregateInputType = {
  id?: true
  firstName?: true
  lastName?: true
  email?: true
  password?: true
  rollnumber?: true
  collegeId?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  otp?: true
  otpExpiry?: true
  verified?: true
}

export type StudentCountAggregateInputType = {
  id?: true
  firstName?: true
  lastName?: true
  email?: true
  password?: true
  rollnumber?: true
  collegeId?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  otp?: true
  otpExpiry?: true
  verified?: true
  _all?: true
}

export type StudentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Student to aggregate.
   */
  where?: Prisma.StudentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Students to fetch.
   */
  orderBy?: Prisma.StudentOrderByWithRelationInput | Prisma.StudentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StudentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Students from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Students.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Students
  **/
  _count?: true | StudentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StudentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StudentMaxAggregateInputType
}

export type GetStudentAggregateType<T extends StudentAggregateArgs> = {
      [P in keyof T & keyof AggregateStudent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStudent[P]>
    : Prisma.GetScalarType<T[P], AggregateStudent[P]>
}




export type StudentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StudentWhereInput
  orderBy?: Prisma.StudentOrderByWithAggregationInput | Prisma.StudentOrderByWithAggregationInput[]
  by: Prisma.StudentScalarFieldEnum[] | Prisma.StudentScalarFieldEnum
  having?: Prisma.StudentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StudentCountAggregateInputType | true
  _min?: StudentMinAggregateInputType
  _max?: StudentMaxAggregateInputType
}

export type StudentGroupByOutputType = {
  id: string
  firstName: string
  lastName: string
  email: string
  password: string
  rollnumber: string | null
  collegeId: string | null
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  otp: string | null
  otpExpiry: Date | null
  verified: boolean
  _count: StudentCountAggregateOutputType | null
  _min: StudentMinAggregateOutputType | null
  _max: StudentMaxAggregateOutputType | null
}

type GetStudentGroupByPayload<T extends StudentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StudentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StudentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StudentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StudentGroupByOutputType[P]>
      }
    >
  >



export type StudentWhereInput = {
  AND?: Prisma.StudentWhereInput | Prisma.StudentWhereInput[]
  OR?: Prisma.StudentWhereInput[]
  NOT?: Prisma.StudentWhereInput | Prisma.StudentWhereInput[]
  id?: Prisma.StringFilter<"Student"> | string
  firstName?: Prisma.StringFilter<"Student"> | string
  lastName?: Prisma.StringFilter<"Student"> | string
  email?: Prisma.StringFilter<"Student"> | string
  password?: Prisma.StringFilter<"Student"> | string
  rollnumber?: Prisma.StringNullableFilter<"Student"> | string | null
  collegeId?: Prisma.StringNullableFilter<"Student"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Student"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Student"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Student"> | Date | string | null
  otp?: Prisma.StringNullableFilter<"Student"> | string | null
  otpExpiry?: Prisma.DateTimeNullableFilter<"Student"> | Date | string | null
  verified?: Prisma.BoolFilter<"Student"> | boolean
  registrations?: Prisma.RegistrationsListRelationFilter
  college?: Prisma.XOR<Prisma.CollegeNullableScalarRelationFilter, Prisma.CollegeWhereInput> | null
  clubs?: Prisma.StudentInClubListRelationFilter
  follows?: Prisma.CollegeListRelationFilter
  followsClub?: Prisma.ClubListRelationFilter
}

export type StudentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  rollnumber?: Prisma.SortOrderInput | Prisma.SortOrder
  collegeId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  otp?: Prisma.SortOrderInput | Prisma.SortOrder
  otpExpiry?: Prisma.SortOrderInput | Prisma.SortOrder
  verified?: Prisma.SortOrder
  registrations?: Prisma.RegistrationsOrderByRelationAggregateInput
  college?: Prisma.CollegeOrderByWithRelationInput
  clubs?: Prisma.StudentInClubOrderByRelationAggregateInput
  follows?: Prisma.CollegeOrderByRelationAggregateInput
  followsClub?: Prisma.ClubOrderByRelationAggregateInput
}

export type StudentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  rollnumber?: string
  AND?: Prisma.StudentWhereInput | Prisma.StudentWhereInput[]
  OR?: Prisma.StudentWhereInput[]
  NOT?: Prisma.StudentWhereInput | Prisma.StudentWhereInput[]
  firstName?: Prisma.StringFilter<"Student"> | string
  lastName?: Prisma.StringFilter<"Student"> | string
  password?: Prisma.StringFilter<"Student"> | string
  collegeId?: Prisma.StringNullableFilter<"Student"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Student"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Student"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Student"> | Date | string | null
  otp?: Prisma.StringNullableFilter<"Student"> | string | null
  otpExpiry?: Prisma.DateTimeNullableFilter<"Student"> | Date | string | null
  verified?: Prisma.BoolFilter<"Student"> | boolean
  registrations?: Prisma.RegistrationsListRelationFilter
  college?: Prisma.XOR<Prisma.CollegeNullableScalarRelationFilter, Prisma.CollegeWhereInput> | null
  clubs?: Prisma.StudentInClubListRelationFilter
  follows?: Prisma.CollegeListRelationFilter
  followsClub?: Prisma.ClubListRelationFilter
}, "id" | "email" | "rollnumber">

export type StudentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  rollnumber?: Prisma.SortOrderInput | Prisma.SortOrder
  collegeId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  otp?: Prisma.SortOrderInput | Prisma.SortOrder
  otpExpiry?: Prisma.SortOrderInput | Prisma.SortOrder
  verified?: Prisma.SortOrder
  _count?: Prisma.StudentCountOrderByAggregateInput
  _max?: Prisma.StudentMaxOrderByAggregateInput
  _min?: Prisma.StudentMinOrderByAggregateInput
}

export type StudentScalarWhereWithAggregatesInput = {
  AND?: Prisma.StudentScalarWhereWithAggregatesInput | Prisma.StudentScalarWhereWithAggregatesInput[]
  OR?: Prisma.StudentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StudentScalarWhereWithAggregatesInput | Prisma.StudentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Student"> | string
  firstName?: Prisma.StringWithAggregatesFilter<"Student"> | string
  lastName?: Prisma.StringWithAggregatesFilter<"Student"> | string
  email?: Prisma.StringWithAggregatesFilter<"Student"> | string
  password?: Prisma.StringWithAggregatesFilter<"Student"> | string
  rollnumber?: Prisma.StringNullableWithAggregatesFilter<"Student"> | string | null
  collegeId?: Prisma.StringNullableWithAggregatesFilter<"Student"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Student"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Student"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Student"> | Date | string | null
  otp?: Prisma.StringNullableWithAggregatesFilter<"Student"> | string | null
  otpExpiry?: Prisma.DateTimeNullableWithAggregatesFilter<"Student"> | Date | string | null
  verified?: Prisma.BoolWithAggregatesFilter<"Student"> | boolean
}

export type StudentCreateInput = {
  id?: string
  firstName: string
  lastName: string
  email: string
  password: string
  rollnumber?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  otp?: string | null
  otpExpiry?: Date | string | null
  verified?: boolean
  registrations?: Prisma.RegistrationsCreateNestedManyWithoutStudentInput
  college?: Prisma.CollegeCreateNestedOneWithoutStudentsInput
  clubs?: Prisma.StudentInClubCreateNestedManyWithoutStudentInput
  follows?: Prisma.CollegeCreateNestedManyWithoutFollowersInput
  followsClub?: Prisma.ClubCreateNestedManyWithoutFollowersInput
}

export type StudentUncheckedCreateInput = {
  id?: string
  firstName: string
  lastName: string
  email: string
  password: string
  rollnumber?: string | null
  collegeId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  otp?: string | null
  otpExpiry?: Date | string | null
  verified?: boolean
  registrations?: Prisma.RegistrationsUncheckedCreateNestedManyWithoutStudentInput
  clubs?: Prisma.StudentInClubUncheckedCreateNestedManyWithoutStudentInput
  follows?: Prisma.CollegeUncheckedCreateNestedManyWithoutFollowersInput
  followsClub?: Prisma.ClubUncheckedCreateNestedManyWithoutFollowersInput
}

export type StudentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rollnumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  otp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  otpExpiry?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registrations?: Prisma.RegistrationsUpdateManyWithoutStudentNestedInput
  college?: Prisma.CollegeUpdateOneWithoutStudentsNestedInput
  clubs?: Prisma.StudentInClubUpdateManyWithoutStudentNestedInput
  follows?: Prisma.CollegeUpdateManyWithoutFollowersNestedInput
  followsClub?: Prisma.ClubUpdateManyWithoutFollowersNestedInput
}

export type StudentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rollnumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collegeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  otp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  otpExpiry?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registrations?: Prisma.RegistrationsUncheckedUpdateManyWithoutStudentNestedInput
  clubs?: Prisma.StudentInClubUncheckedUpdateManyWithoutStudentNestedInput
  follows?: Prisma.CollegeUncheckedUpdateManyWithoutFollowersNestedInput
  followsClub?: Prisma.ClubUncheckedUpdateManyWithoutFollowersNestedInput
}

export type StudentCreateManyInput = {
  id?: string
  firstName: string
  lastName: string
  email: string
  password: string
  rollnumber?: string | null
  collegeId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  otp?: string | null
  otpExpiry?: Date | string | null
  verified?: boolean
}

export type StudentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rollnumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  otp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  otpExpiry?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type StudentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rollnumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collegeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  otp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  otpExpiry?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type StudentListRelationFilter = {
  every?: Prisma.StudentWhereInput
  some?: Prisma.StudentWhereInput
  none?: Prisma.StudentWhereInput
}

export type StudentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StudentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  rollnumber?: Prisma.SortOrder
  collegeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  otp?: Prisma.SortOrder
  otpExpiry?: Prisma.SortOrder
  verified?: Prisma.SortOrder
}

export type StudentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  rollnumber?: Prisma.SortOrder
  collegeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  otp?: Prisma.SortOrder
  otpExpiry?: Prisma.SortOrder
  verified?: Prisma.SortOrder
}

export type StudentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  rollnumber?: Prisma.SortOrder
  collegeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  otp?: Prisma.SortOrder
  otpExpiry?: Prisma.SortOrder
  verified?: Prisma.SortOrder
}

export type StudentScalarRelationFilter = {
  is?: Prisma.StudentWhereInput
  isNot?: Prisma.StudentWhereInput
}

export type StudentCreateNestedManyWithoutCollegeInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutCollegeInput, Prisma.StudentUncheckedCreateWithoutCollegeInput> | Prisma.StudentCreateWithoutCollegeInput[] | Prisma.StudentUncheckedCreateWithoutCollegeInput[]
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutCollegeInput | Prisma.StudentCreateOrConnectWithoutCollegeInput[]
  createMany?: Prisma.StudentCreateManyCollegeInputEnvelope
  connect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
}

export type StudentCreateNestedManyWithoutFollowsInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutFollowsInput, Prisma.StudentUncheckedCreateWithoutFollowsInput> | Prisma.StudentCreateWithoutFollowsInput[] | Prisma.StudentUncheckedCreateWithoutFollowsInput[]
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutFollowsInput | Prisma.StudentCreateOrConnectWithoutFollowsInput[]
  connect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
}

export type StudentUncheckedCreateNestedManyWithoutCollegeInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutCollegeInput, Prisma.StudentUncheckedCreateWithoutCollegeInput> | Prisma.StudentCreateWithoutCollegeInput[] | Prisma.StudentUncheckedCreateWithoutCollegeInput[]
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutCollegeInput | Prisma.StudentCreateOrConnectWithoutCollegeInput[]
  createMany?: Prisma.StudentCreateManyCollegeInputEnvelope
  connect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
}

export type StudentUncheckedCreateNestedManyWithoutFollowsInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutFollowsInput, Prisma.StudentUncheckedCreateWithoutFollowsInput> | Prisma.StudentCreateWithoutFollowsInput[] | Prisma.StudentUncheckedCreateWithoutFollowsInput[]
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutFollowsInput | Prisma.StudentCreateOrConnectWithoutFollowsInput[]
  connect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
}

export type StudentUpdateManyWithoutCollegeNestedInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutCollegeInput, Prisma.StudentUncheckedCreateWithoutCollegeInput> | Prisma.StudentCreateWithoutCollegeInput[] | Prisma.StudentUncheckedCreateWithoutCollegeInput[]
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutCollegeInput | Prisma.StudentCreateOrConnectWithoutCollegeInput[]
  upsert?: Prisma.StudentUpsertWithWhereUniqueWithoutCollegeInput | Prisma.StudentUpsertWithWhereUniqueWithoutCollegeInput[]
  createMany?: Prisma.StudentCreateManyCollegeInputEnvelope
  set?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  disconnect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  delete?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  connect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  update?: Prisma.StudentUpdateWithWhereUniqueWithoutCollegeInput | Prisma.StudentUpdateWithWhereUniqueWithoutCollegeInput[]
  updateMany?: Prisma.StudentUpdateManyWithWhereWithoutCollegeInput | Prisma.StudentUpdateManyWithWhereWithoutCollegeInput[]
  deleteMany?: Prisma.StudentScalarWhereInput | Prisma.StudentScalarWhereInput[]
}

export type StudentUpdateManyWithoutFollowsNestedInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutFollowsInput, Prisma.StudentUncheckedCreateWithoutFollowsInput> | Prisma.StudentCreateWithoutFollowsInput[] | Prisma.StudentUncheckedCreateWithoutFollowsInput[]
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutFollowsInput | Prisma.StudentCreateOrConnectWithoutFollowsInput[]
  upsert?: Prisma.StudentUpsertWithWhereUniqueWithoutFollowsInput | Prisma.StudentUpsertWithWhereUniqueWithoutFollowsInput[]
  set?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  disconnect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  delete?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  connect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  update?: Prisma.StudentUpdateWithWhereUniqueWithoutFollowsInput | Prisma.StudentUpdateWithWhereUniqueWithoutFollowsInput[]
  updateMany?: Prisma.StudentUpdateManyWithWhereWithoutFollowsInput | Prisma.StudentUpdateManyWithWhereWithoutFollowsInput[]
  deleteMany?: Prisma.StudentScalarWhereInput | Prisma.StudentScalarWhereInput[]
}

export type StudentUncheckedUpdateManyWithoutCollegeNestedInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutCollegeInput, Prisma.StudentUncheckedCreateWithoutCollegeInput> | Prisma.StudentCreateWithoutCollegeInput[] | Prisma.StudentUncheckedCreateWithoutCollegeInput[]
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutCollegeInput | Prisma.StudentCreateOrConnectWithoutCollegeInput[]
  upsert?: Prisma.StudentUpsertWithWhereUniqueWithoutCollegeInput | Prisma.StudentUpsertWithWhereUniqueWithoutCollegeInput[]
  createMany?: Prisma.StudentCreateManyCollegeInputEnvelope
  set?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  disconnect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  delete?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  connect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  update?: Prisma.StudentUpdateWithWhereUniqueWithoutCollegeInput | Prisma.StudentUpdateWithWhereUniqueWithoutCollegeInput[]
  updateMany?: Prisma.StudentUpdateManyWithWhereWithoutCollegeInput | Prisma.StudentUpdateManyWithWhereWithoutCollegeInput[]
  deleteMany?: Prisma.StudentScalarWhereInput | Prisma.StudentScalarWhereInput[]
}

export type StudentUncheckedUpdateManyWithoutFollowsNestedInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutFollowsInput, Prisma.StudentUncheckedCreateWithoutFollowsInput> | Prisma.StudentCreateWithoutFollowsInput[] | Prisma.StudentUncheckedCreateWithoutFollowsInput[]
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutFollowsInput | Prisma.StudentCreateOrConnectWithoutFollowsInput[]
  upsert?: Prisma.StudentUpsertWithWhereUniqueWithoutFollowsInput | Prisma.StudentUpsertWithWhereUniqueWithoutFollowsInput[]
  set?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  disconnect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  delete?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  connect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  update?: Prisma.StudentUpdateWithWhereUniqueWithoutFollowsInput | Prisma.StudentUpdateWithWhereUniqueWithoutFollowsInput[]
  updateMany?: Prisma.StudentUpdateManyWithWhereWithoutFollowsInput | Prisma.StudentUpdateManyWithWhereWithoutFollowsInput[]
  deleteMany?: Prisma.StudentScalarWhereInput | Prisma.StudentScalarWhereInput[]
}

export type StudentCreateNestedManyWithoutFollowsClubInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutFollowsClubInput, Prisma.StudentUncheckedCreateWithoutFollowsClubInput> | Prisma.StudentCreateWithoutFollowsClubInput[] | Prisma.StudentUncheckedCreateWithoutFollowsClubInput[]
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutFollowsClubInput | Prisma.StudentCreateOrConnectWithoutFollowsClubInput[]
  connect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
}

export type StudentUncheckedCreateNestedManyWithoutFollowsClubInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutFollowsClubInput, Prisma.StudentUncheckedCreateWithoutFollowsClubInput> | Prisma.StudentCreateWithoutFollowsClubInput[] | Prisma.StudentUncheckedCreateWithoutFollowsClubInput[]
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutFollowsClubInput | Prisma.StudentCreateOrConnectWithoutFollowsClubInput[]
  connect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
}

export type StudentUpdateManyWithoutFollowsClubNestedInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutFollowsClubInput, Prisma.StudentUncheckedCreateWithoutFollowsClubInput> | Prisma.StudentCreateWithoutFollowsClubInput[] | Prisma.StudentUncheckedCreateWithoutFollowsClubInput[]
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutFollowsClubInput | Prisma.StudentCreateOrConnectWithoutFollowsClubInput[]
  upsert?: Prisma.StudentUpsertWithWhereUniqueWithoutFollowsClubInput | Prisma.StudentUpsertWithWhereUniqueWithoutFollowsClubInput[]
  set?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  disconnect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  delete?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  connect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  update?: Prisma.StudentUpdateWithWhereUniqueWithoutFollowsClubInput | Prisma.StudentUpdateWithWhereUniqueWithoutFollowsClubInput[]
  updateMany?: Prisma.StudentUpdateManyWithWhereWithoutFollowsClubInput | Prisma.StudentUpdateManyWithWhereWithoutFollowsClubInput[]
  deleteMany?: Prisma.StudentScalarWhereInput | Prisma.StudentScalarWhereInput[]
}

export type StudentUncheckedUpdateManyWithoutFollowsClubNestedInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutFollowsClubInput, Prisma.StudentUncheckedCreateWithoutFollowsClubInput> | Prisma.StudentCreateWithoutFollowsClubInput[] | Prisma.StudentUncheckedCreateWithoutFollowsClubInput[]
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutFollowsClubInput | Prisma.StudentCreateOrConnectWithoutFollowsClubInput[]
  upsert?: Prisma.StudentUpsertWithWhereUniqueWithoutFollowsClubInput | Prisma.StudentUpsertWithWhereUniqueWithoutFollowsClubInput[]
  set?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  disconnect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  delete?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  connect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  update?: Prisma.StudentUpdateWithWhereUniqueWithoutFollowsClubInput | Prisma.StudentUpdateWithWhereUniqueWithoutFollowsClubInput[]
  updateMany?: Prisma.StudentUpdateManyWithWhereWithoutFollowsClubInput | Prisma.StudentUpdateManyWithWhereWithoutFollowsClubInput[]
  deleteMany?: Prisma.StudentScalarWhereInput | Prisma.StudentScalarWhereInput[]
}

export type StudentCreateNestedOneWithoutClubsInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutClubsInput, Prisma.StudentUncheckedCreateWithoutClubsInput>
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutClubsInput
  connect?: Prisma.StudentWhereUniqueInput
}

export type StudentUpdateOneRequiredWithoutClubsNestedInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutClubsInput, Prisma.StudentUncheckedCreateWithoutClubsInput>
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutClubsInput
  upsert?: Prisma.StudentUpsertWithoutClubsInput
  connect?: Prisma.StudentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StudentUpdateToOneWithWhereWithoutClubsInput, Prisma.StudentUpdateWithoutClubsInput>, Prisma.StudentUncheckedUpdateWithoutClubsInput>
}

export type StudentCreateNestedOneWithoutRegistrationsInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutRegistrationsInput, Prisma.StudentUncheckedCreateWithoutRegistrationsInput>
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutRegistrationsInput
  connect?: Prisma.StudentWhereUniqueInput
}

export type StudentUpdateOneRequiredWithoutRegistrationsNestedInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutRegistrationsInput, Prisma.StudentUncheckedCreateWithoutRegistrationsInput>
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutRegistrationsInput
  upsert?: Prisma.StudentUpsertWithoutRegistrationsInput
  connect?: Prisma.StudentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StudentUpdateToOneWithWhereWithoutRegistrationsInput, Prisma.StudentUpdateWithoutRegistrationsInput>, Prisma.StudentUncheckedUpdateWithoutRegistrationsInput>
}

export type StudentCreateWithoutCollegeInput = {
  id?: string
  firstName: string
  lastName: string
  email: string
  password: string
  rollnumber?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  otp?: string | null
  otpExpiry?: Date | string | null
  verified?: boolean
  registrations?: Prisma.RegistrationsCreateNestedManyWithoutStudentInput
  clubs?: Prisma.StudentInClubCreateNestedManyWithoutStudentInput
  follows?: Prisma.CollegeCreateNestedManyWithoutFollowersInput
  followsClub?: Prisma.ClubCreateNestedManyWithoutFollowersInput
}

export type StudentUncheckedCreateWithoutCollegeInput = {
  id?: string
  firstName: string
  lastName: string
  email: string
  password: string
  rollnumber?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  otp?: string | null
  otpExpiry?: Date | string | null
  verified?: boolean
  registrations?: Prisma.RegistrationsUncheckedCreateNestedManyWithoutStudentInput
  clubs?: Prisma.StudentInClubUncheckedCreateNestedManyWithoutStudentInput
  follows?: Prisma.CollegeUncheckedCreateNestedManyWithoutFollowersInput
  followsClub?: Prisma.ClubUncheckedCreateNestedManyWithoutFollowersInput
}

export type StudentCreateOrConnectWithoutCollegeInput = {
  where: Prisma.StudentWhereUniqueInput
  create: Prisma.XOR<Prisma.StudentCreateWithoutCollegeInput, Prisma.StudentUncheckedCreateWithoutCollegeInput>
}

export type StudentCreateManyCollegeInputEnvelope = {
  data: Prisma.StudentCreateManyCollegeInput | Prisma.StudentCreateManyCollegeInput[]
  skipDuplicates?: boolean
}

export type StudentCreateWithoutFollowsInput = {
  id?: string
  firstName: string
  lastName: string
  email: string
  password: string
  rollnumber?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  otp?: string | null
  otpExpiry?: Date | string | null
  verified?: boolean
  registrations?: Prisma.RegistrationsCreateNestedManyWithoutStudentInput
  college?: Prisma.CollegeCreateNestedOneWithoutStudentsInput
  clubs?: Prisma.StudentInClubCreateNestedManyWithoutStudentInput
  followsClub?: Prisma.ClubCreateNestedManyWithoutFollowersInput
}

export type StudentUncheckedCreateWithoutFollowsInput = {
  id?: string
  firstName: string
  lastName: string
  email: string
  password: string
  rollnumber?: string | null
  collegeId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  otp?: string | null
  otpExpiry?: Date | string | null
  verified?: boolean
  registrations?: Prisma.RegistrationsUncheckedCreateNestedManyWithoutStudentInput
  clubs?: Prisma.StudentInClubUncheckedCreateNestedManyWithoutStudentInput
  followsClub?: Prisma.ClubUncheckedCreateNestedManyWithoutFollowersInput
}

export type StudentCreateOrConnectWithoutFollowsInput = {
  where: Prisma.StudentWhereUniqueInput
  create: Prisma.XOR<Prisma.StudentCreateWithoutFollowsInput, Prisma.StudentUncheckedCreateWithoutFollowsInput>
}

export type StudentUpsertWithWhereUniqueWithoutCollegeInput = {
  where: Prisma.StudentWhereUniqueInput
  update: Prisma.XOR<Prisma.StudentUpdateWithoutCollegeInput, Prisma.StudentUncheckedUpdateWithoutCollegeInput>
  create: Prisma.XOR<Prisma.StudentCreateWithoutCollegeInput, Prisma.StudentUncheckedCreateWithoutCollegeInput>
}

export type StudentUpdateWithWhereUniqueWithoutCollegeInput = {
  where: Prisma.StudentWhereUniqueInput
  data: Prisma.XOR<Prisma.StudentUpdateWithoutCollegeInput, Prisma.StudentUncheckedUpdateWithoutCollegeInput>
}

export type StudentUpdateManyWithWhereWithoutCollegeInput = {
  where: Prisma.StudentScalarWhereInput
  data: Prisma.XOR<Prisma.StudentUpdateManyMutationInput, Prisma.StudentUncheckedUpdateManyWithoutCollegeInput>
}

export type StudentScalarWhereInput = {
  AND?: Prisma.StudentScalarWhereInput | Prisma.StudentScalarWhereInput[]
  OR?: Prisma.StudentScalarWhereInput[]
  NOT?: Prisma.StudentScalarWhereInput | Prisma.StudentScalarWhereInput[]
  id?: Prisma.StringFilter<"Student"> | string
  firstName?: Prisma.StringFilter<"Student"> | string
  lastName?: Prisma.StringFilter<"Student"> | string
  email?: Prisma.StringFilter<"Student"> | string
  password?: Prisma.StringFilter<"Student"> | string
  rollnumber?: Prisma.StringNullableFilter<"Student"> | string | null
  collegeId?: Prisma.StringNullableFilter<"Student"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Student"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Student"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Student"> | Date | string | null
  otp?: Prisma.StringNullableFilter<"Student"> | string | null
  otpExpiry?: Prisma.DateTimeNullableFilter<"Student"> | Date | string | null
  verified?: Prisma.BoolFilter<"Student"> | boolean
}

export type StudentUpsertWithWhereUniqueWithoutFollowsInput = {
  where: Prisma.StudentWhereUniqueInput
  update: Prisma.XOR<Prisma.StudentUpdateWithoutFollowsInput, Prisma.StudentUncheckedUpdateWithoutFollowsInput>
  create: Prisma.XOR<Prisma.StudentCreateWithoutFollowsInput, Prisma.StudentUncheckedCreateWithoutFollowsInput>
}

export type StudentUpdateWithWhereUniqueWithoutFollowsInput = {
  where: Prisma.StudentWhereUniqueInput
  data: Prisma.XOR<Prisma.StudentUpdateWithoutFollowsInput, Prisma.StudentUncheckedUpdateWithoutFollowsInput>
}

export type StudentUpdateManyWithWhereWithoutFollowsInput = {
  where: Prisma.StudentScalarWhereInput
  data: Prisma.XOR<Prisma.StudentUpdateManyMutationInput, Prisma.StudentUncheckedUpdateManyWithoutFollowsInput>
}

export type StudentCreateWithoutFollowsClubInput = {
  id?: string
  firstName: string
  lastName: string
  email: string
  password: string
  rollnumber?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  otp?: string | null
  otpExpiry?: Date | string | null
  verified?: boolean
  registrations?: Prisma.RegistrationsCreateNestedManyWithoutStudentInput
  college?: Prisma.CollegeCreateNestedOneWithoutStudentsInput
  clubs?: Prisma.StudentInClubCreateNestedManyWithoutStudentInput
  follows?: Prisma.CollegeCreateNestedManyWithoutFollowersInput
}

export type StudentUncheckedCreateWithoutFollowsClubInput = {
  id?: string
  firstName: string
  lastName: string
  email: string
  password: string
  rollnumber?: string | null
  collegeId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  otp?: string | null
  otpExpiry?: Date | string | null
  verified?: boolean
  registrations?: Prisma.RegistrationsUncheckedCreateNestedManyWithoutStudentInput
  clubs?: Prisma.StudentInClubUncheckedCreateNestedManyWithoutStudentInput
  follows?: Prisma.CollegeUncheckedCreateNestedManyWithoutFollowersInput
}

export type StudentCreateOrConnectWithoutFollowsClubInput = {
  where: Prisma.StudentWhereUniqueInput
  create: Prisma.XOR<Prisma.StudentCreateWithoutFollowsClubInput, Prisma.StudentUncheckedCreateWithoutFollowsClubInput>
}

export type StudentUpsertWithWhereUniqueWithoutFollowsClubInput = {
  where: Prisma.StudentWhereUniqueInput
  update: Prisma.XOR<Prisma.StudentUpdateWithoutFollowsClubInput, Prisma.StudentUncheckedUpdateWithoutFollowsClubInput>
  create: Prisma.XOR<Prisma.StudentCreateWithoutFollowsClubInput, Prisma.StudentUncheckedCreateWithoutFollowsClubInput>
}

export type StudentUpdateWithWhereUniqueWithoutFollowsClubInput = {
  where: Prisma.StudentWhereUniqueInput
  data: Prisma.XOR<Prisma.StudentUpdateWithoutFollowsClubInput, Prisma.StudentUncheckedUpdateWithoutFollowsClubInput>
}

export type StudentUpdateManyWithWhereWithoutFollowsClubInput = {
  where: Prisma.StudentScalarWhereInput
  data: Prisma.XOR<Prisma.StudentUpdateManyMutationInput, Prisma.StudentUncheckedUpdateManyWithoutFollowsClubInput>
}

export type StudentCreateWithoutClubsInput = {
  id?: string
  firstName: string
  lastName: string
  email: string
  password: string
  rollnumber?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  otp?: string | null
  otpExpiry?: Date | string | null
  verified?: boolean
  registrations?: Prisma.RegistrationsCreateNestedManyWithoutStudentInput
  college?: Prisma.CollegeCreateNestedOneWithoutStudentsInput
  follows?: Prisma.CollegeCreateNestedManyWithoutFollowersInput
  followsClub?: Prisma.ClubCreateNestedManyWithoutFollowersInput
}

export type StudentUncheckedCreateWithoutClubsInput = {
  id?: string
  firstName: string
  lastName: string
  email: string
  password: string
  rollnumber?: string | null
  collegeId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  otp?: string | null
  otpExpiry?: Date | string | null
  verified?: boolean
  registrations?: Prisma.RegistrationsUncheckedCreateNestedManyWithoutStudentInput
  follows?: Prisma.CollegeUncheckedCreateNestedManyWithoutFollowersInput
  followsClub?: Prisma.ClubUncheckedCreateNestedManyWithoutFollowersInput
}

export type StudentCreateOrConnectWithoutClubsInput = {
  where: Prisma.StudentWhereUniqueInput
  create: Prisma.XOR<Prisma.StudentCreateWithoutClubsInput, Prisma.StudentUncheckedCreateWithoutClubsInput>
}

export type StudentUpsertWithoutClubsInput = {
  update: Prisma.XOR<Prisma.StudentUpdateWithoutClubsInput, Prisma.StudentUncheckedUpdateWithoutClubsInput>
  create: Prisma.XOR<Prisma.StudentCreateWithoutClubsInput, Prisma.StudentUncheckedCreateWithoutClubsInput>
  where?: Prisma.StudentWhereInput
}

export type StudentUpdateToOneWithWhereWithoutClubsInput = {
  where?: Prisma.StudentWhereInput
  data: Prisma.XOR<Prisma.StudentUpdateWithoutClubsInput, Prisma.StudentUncheckedUpdateWithoutClubsInput>
}

export type StudentUpdateWithoutClubsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rollnumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  otp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  otpExpiry?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registrations?: Prisma.RegistrationsUpdateManyWithoutStudentNestedInput
  college?: Prisma.CollegeUpdateOneWithoutStudentsNestedInput
  follows?: Prisma.CollegeUpdateManyWithoutFollowersNestedInput
  followsClub?: Prisma.ClubUpdateManyWithoutFollowersNestedInput
}

export type StudentUncheckedUpdateWithoutClubsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rollnumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collegeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  otp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  otpExpiry?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registrations?: Prisma.RegistrationsUncheckedUpdateManyWithoutStudentNestedInput
  follows?: Prisma.CollegeUncheckedUpdateManyWithoutFollowersNestedInput
  followsClub?: Prisma.ClubUncheckedUpdateManyWithoutFollowersNestedInput
}

export type StudentCreateWithoutRegistrationsInput = {
  id?: string
  firstName: string
  lastName: string
  email: string
  password: string
  rollnumber?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  otp?: string | null
  otpExpiry?: Date | string | null
  verified?: boolean
  college?: Prisma.CollegeCreateNestedOneWithoutStudentsInput
  clubs?: Prisma.StudentInClubCreateNestedManyWithoutStudentInput
  follows?: Prisma.CollegeCreateNestedManyWithoutFollowersInput
  followsClub?: Prisma.ClubCreateNestedManyWithoutFollowersInput
}

export type StudentUncheckedCreateWithoutRegistrationsInput = {
  id?: string
  firstName: string
  lastName: string
  email: string
  password: string
  rollnumber?: string | null
  collegeId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  otp?: string | null
  otpExpiry?: Date | string | null
  verified?: boolean
  clubs?: Prisma.StudentInClubUncheckedCreateNestedManyWithoutStudentInput
  follows?: Prisma.CollegeUncheckedCreateNestedManyWithoutFollowersInput
  followsClub?: Prisma.ClubUncheckedCreateNestedManyWithoutFollowersInput
}

export type StudentCreateOrConnectWithoutRegistrationsInput = {
  where: Prisma.StudentWhereUniqueInput
  create: Prisma.XOR<Prisma.StudentCreateWithoutRegistrationsInput, Prisma.StudentUncheckedCreateWithoutRegistrationsInput>
}

export type StudentUpsertWithoutRegistrationsInput = {
  update: Prisma.XOR<Prisma.StudentUpdateWithoutRegistrationsInput, Prisma.StudentUncheckedUpdateWithoutRegistrationsInput>
  create: Prisma.XOR<Prisma.StudentCreateWithoutRegistrationsInput, Prisma.StudentUncheckedCreateWithoutRegistrationsInput>
  where?: Prisma.StudentWhereInput
}

export type StudentUpdateToOneWithWhereWithoutRegistrationsInput = {
  where?: Prisma.StudentWhereInput
  data: Prisma.XOR<Prisma.StudentUpdateWithoutRegistrationsInput, Prisma.StudentUncheckedUpdateWithoutRegistrationsInput>
}

export type StudentUpdateWithoutRegistrationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rollnumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  otp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  otpExpiry?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  college?: Prisma.CollegeUpdateOneWithoutStudentsNestedInput
  clubs?: Prisma.StudentInClubUpdateManyWithoutStudentNestedInput
  follows?: Prisma.CollegeUpdateManyWithoutFollowersNestedInput
  followsClub?: Prisma.ClubUpdateManyWithoutFollowersNestedInput
}

export type StudentUncheckedUpdateWithoutRegistrationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rollnumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collegeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  otp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  otpExpiry?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  clubs?: Prisma.StudentInClubUncheckedUpdateManyWithoutStudentNestedInput
  follows?: Prisma.CollegeUncheckedUpdateManyWithoutFollowersNestedInput
  followsClub?: Prisma.ClubUncheckedUpdateManyWithoutFollowersNestedInput
}

export type StudentCreateManyCollegeInput = {
  id?: string
  firstName: string
  lastName: string
  email: string
  password: string
  rollnumber?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  otp?: string | null
  otpExpiry?: Date | string | null
  verified?: boolean
}

export type StudentUpdateWithoutCollegeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rollnumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  otp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  otpExpiry?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registrations?: Prisma.RegistrationsUpdateManyWithoutStudentNestedInput
  clubs?: Prisma.StudentInClubUpdateManyWithoutStudentNestedInput
  follows?: Prisma.CollegeUpdateManyWithoutFollowersNestedInput
  followsClub?: Prisma.ClubUpdateManyWithoutFollowersNestedInput
}

export type StudentUncheckedUpdateWithoutCollegeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rollnumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  otp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  otpExpiry?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registrations?: Prisma.RegistrationsUncheckedUpdateManyWithoutStudentNestedInput
  clubs?: Prisma.StudentInClubUncheckedUpdateManyWithoutStudentNestedInput
  follows?: Prisma.CollegeUncheckedUpdateManyWithoutFollowersNestedInput
  followsClub?: Prisma.ClubUncheckedUpdateManyWithoutFollowersNestedInput
}

export type StudentUncheckedUpdateManyWithoutCollegeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rollnumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  otp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  otpExpiry?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type StudentUpdateWithoutFollowsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rollnumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  otp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  otpExpiry?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registrations?: Prisma.RegistrationsUpdateManyWithoutStudentNestedInput
  college?: Prisma.CollegeUpdateOneWithoutStudentsNestedInput
  clubs?: Prisma.StudentInClubUpdateManyWithoutStudentNestedInput
  followsClub?: Prisma.ClubUpdateManyWithoutFollowersNestedInput
}

export type StudentUncheckedUpdateWithoutFollowsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rollnumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collegeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  otp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  otpExpiry?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registrations?: Prisma.RegistrationsUncheckedUpdateManyWithoutStudentNestedInput
  clubs?: Prisma.StudentInClubUncheckedUpdateManyWithoutStudentNestedInput
  followsClub?: Prisma.ClubUncheckedUpdateManyWithoutFollowersNestedInput
}

export type StudentUncheckedUpdateManyWithoutFollowsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rollnumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collegeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  otp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  otpExpiry?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type StudentUpdateWithoutFollowsClubInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rollnumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  otp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  otpExpiry?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registrations?: Prisma.RegistrationsUpdateManyWithoutStudentNestedInput
  college?: Prisma.CollegeUpdateOneWithoutStudentsNestedInput
  clubs?: Prisma.StudentInClubUpdateManyWithoutStudentNestedInput
  follows?: Prisma.CollegeUpdateManyWithoutFollowersNestedInput
}

export type StudentUncheckedUpdateWithoutFollowsClubInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rollnumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collegeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  otp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  otpExpiry?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registrations?: Prisma.RegistrationsUncheckedUpdateManyWithoutStudentNestedInput
  clubs?: Prisma.StudentInClubUncheckedUpdateManyWithoutStudentNestedInput
  follows?: Prisma.CollegeUncheckedUpdateManyWithoutFollowersNestedInput
}

export type StudentUncheckedUpdateManyWithoutFollowsClubInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  rollnumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collegeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  otp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  otpExpiry?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
}


/**
 * Count Type StudentCountOutputType
 */

export type StudentCountOutputType = {
  registrations: number
  clubs: number
  follows: number
  followsClub: number
}

export type StudentCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  registrations?: boolean | StudentCountOutputTypeCountRegistrationsArgs
  clubs?: boolean | StudentCountOutputTypeCountClubsArgs
  follows?: boolean | StudentCountOutputTypeCountFollowsArgs
  followsClub?: boolean | StudentCountOutputTypeCountFollowsClubArgs
}

/**
 * StudentCountOutputType without action
 */
export type StudentCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentCountOutputType
   */
  select?: Prisma.StudentCountOutputTypeSelect<ExtArgs> | null
}

/**
 * StudentCountOutputType without action
 */
export type StudentCountOutputTypeCountRegistrationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RegistrationsWhereInput
}

/**
 * StudentCountOutputType without action
 */
export type StudentCountOutputTypeCountClubsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StudentInClubWhereInput
}

/**
 * StudentCountOutputType without action
 */
export type StudentCountOutputTypeCountFollowsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CollegeWhereInput
}

/**
 * StudentCountOutputType without action
 */
export type StudentCountOutputTypeCountFollowsClubArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ClubWhereInput
}


export type StudentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  firstName?: boolean
  lastName?: boolean
  email?: boolean
  password?: boolean
  rollnumber?: boolean
  collegeId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  otp?: boolean
  otpExpiry?: boolean
  verified?: boolean
  registrations?: boolean | Prisma.Student$registrationsArgs<ExtArgs>
  college?: boolean | Prisma.Student$collegeArgs<ExtArgs>
  clubs?: boolean | Prisma.Student$clubsArgs<ExtArgs>
  follows?: boolean | Prisma.Student$followsArgs<ExtArgs>
  followsClub?: boolean | Prisma.Student$followsClubArgs<ExtArgs>
  _count?: boolean | Prisma.StudentCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["student"]>

export type StudentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  firstName?: boolean
  lastName?: boolean
  email?: boolean
  password?: boolean
  rollnumber?: boolean
  collegeId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  otp?: boolean
  otpExpiry?: boolean
  verified?: boolean
  college?: boolean | Prisma.Student$collegeArgs<ExtArgs>
}, ExtArgs["result"]["student"]>

export type StudentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  firstName?: boolean
  lastName?: boolean
  email?: boolean
  password?: boolean
  rollnumber?: boolean
  collegeId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  otp?: boolean
  otpExpiry?: boolean
  verified?: boolean
  college?: boolean | Prisma.Student$collegeArgs<ExtArgs>
}, ExtArgs["result"]["student"]>

export type StudentSelectScalar = {
  id?: boolean
  firstName?: boolean
  lastName?: boolean
  email?: boolean
  password?: boolean
  rollnumber?: boolean
  collegeId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  otp?: boolean
  otpExpiry?: boolean
  verified?: boolean
}

export type StudentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "firstName" | "lastName" | "email" | "password" | "rollnumber" | "collegeId" | "createdAt" | "updatedAt" | "deletedAt" | "otp" | "otpExpiry" | "verified", ExtArgs["result"]["student"]>
export type StudentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  registrations?: boolean | Prisma.Student$registrationsArgs<ExtArgs>
  college?: boolean | Prisma.Student$collegeArgs<ExtArgs>
  clubs?: boolean | Prisma.Student$clubsArgs<ExtArgs>
  follows?: boolean | Prisma.Student$followsArgs<ExtArgs>
  followsClub?: boolean | Prisma.Student$followsClubArgs<ExtArgs>
  _count?: boolean | Prisma.StudentCountOutputTypeDefaultArgs<ExtArgs>
}
export type StudentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  college?: boolean | Prisma.Student$collegeArgs<ExtArgs>
}
export type StudentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  college?: boolean | Prisma.Student$collegeArgs<ExtArgs>
}

export type $StudentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Student"
  objects: {
    registrations: Prisma.$RegistrationsPayload<ExtArgs>[]
    college: Prisma.$CollegePayload<ExtArgs> | null
    clubs: Prisma.$StudentInClubPayload<ExtArgs>[]
    follows: Prisma.$CollegePayload<ExtArgs>[]
    followsClub: Prisma.$ClubPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    firstName: string
    lastName: string
    email: string
    password: string
    rollnumber: string | null
    collegeId: string | null
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
    otp: string | null
    otpExpiry: Date | null
    verified: boolean
  }, ExtArgs["result"]["student"]>
  composites: {}
}

export type StudentGetPayload<S extends boolean | null | undefined | StudentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StudentPayload, S>

export type StudentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StudentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StudentCountAggregateInputType | true
  }

export interface StudentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Student'], meta: { name: 'Student' } }
  /**
   * Find zero or one Student that matches the filter.
   * @param {StudentFindUniqueArgs} args - Arguments to find a Student
   * @example
   * // Get one Student
   * const student = await prisma.student.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StudentFindUniqueArgs>(args: Prisma.SelectSubset<T, StudentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Student that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StudentFindUniqueOrThrowArgs} args - Arguments to find a Student
   * @example
   * // Get one Student
   * const student = await prisma.student.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StudentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StudentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Student that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentFindFirstArgs} args - Arguments to find a Student
   * @example
   * // Get one Student
   * const student = await prisma.student.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StudentFindFirstArgs>(args?: Prisma.SelectSubset<T, StudentFindFirstArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Student that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentFindFirstOrThrowArgs} args - Arguments to find a Student
   * @example
   * // Get one Student
   * const student = await prisma.student.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StudentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StudentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Students that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Students
   * const students = await prisma.student.findMany()
   * 
   * // Get first 10 Students
   * const students = await prisma.student.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const studentWithIdOnly = await prisma.student.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StudentFindManyArgs>(args?: Prisma.SelectSubset<T, StudentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Student.
   * @param {StudentCreateArgs} args - Arguments to create a Student.
   * @example
   * // Create one Student
   * const Student = await prisma.student.create({
   *   data: {
   *     // ... data to create a Student
   *   }
   * })
   * 
   */
  create<T extends StudentCreateArgs>(args: Prisma.SelectSubset<T, StudentCreateArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Students.
   * @param {StudentCreateManyArgs} args - Arguments to create many Students.
   * @example
   * // Create many Students
   * const student = await prisma.student.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StudentCreateManyArgs>(args?: Prisma.SelectSubset<T, StudentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Students and returns the data saved in the database.
   * @param {StudentCreateManyAndReturnArgs} args - Arguments to create many Students.
   * @example
   * // Create many Students
   * const student = await prisma.student.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Students and only return the `id`
   * const studentWithIdOnly = await prisma.student.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StudentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StudentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Student.
   * @param {StudentDeleteArgs} args - Arguments to delete one Student.
   * @example
   * // Delete one Student
   * const Student = await prisma.student.delete({
   *   where: {
   *     // ... filter to delete one Student
   *   }
   * })
   * 
   */
  delete<T extends StudentDeleteArgs>(args: Prisma.SelectSubset<T, StudentDeleteArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Student.
   * @param {StudentUpdateArgs} args - Arguments to update one Student.
   * @example
   * // Update one Student
   * const student = await prisma.student.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StudentUpdateArgs>(args: Prisma.SelectSubset<T, StudentUpdateArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Students.
   * @param {StudentDeleteManyArgs} args - Arguments to filter Students to delete.
   * @example
   * // Delete a few Students
   * const { count } = await prisma.student.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StudentDeleteManyArgs>(args?: Prisma.SelectSubset<T, StudentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Students.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Students
   * const student = await prisma.student.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StudentUpdateManyArgs>(args: Prisma.SelectSubset<T, StudentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Students and returns the data updated in the database.
   * @param {StudentUpdateManyAndReturnArgs} args - Arguments to update many Students.
   * @example
   * // Update many Students
   * const student = await prisma.student.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Students and only return the `id`
   * const studentWithIdOnly = await prisma.student.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StudentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StudentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Student.
   * @param {StudentUpsertArgs} args - Arguments to update or create a Student.
   * @example
   * // Update or create a Student
   * const student = await prisma.student.upsert({
   *   create: {
   *     // ... data to create a Student
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Student we want to update
   *   }
   * })
   */
  upsert<T extends StudentUpsertArgs>(args: Prisma.SelectSubset<T, StudentUpsertArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Students.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentCountArgs} args - Arguments to filter Students to count.
   * @example
   * // Count the number of Students
   * const count = await prisma.student.count({
   *   where: {
   *     // ... the filter for the Students we want to count
   *   }
   * })
  **/
  count<T extends StudentCountArgs>(
    args?: Prisma.Subset<T, StudentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StudentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Student.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StudentAggregateArgs>(args: Prisma.Subset<T, StudentAggregateArgs>): Prisma.PrismaPromise<GetStudentAggregateType<T>>

  /**
   * Group by Student.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StudentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StudentGroupByArgs['orderBy'] }
      : { orderBy?: StudentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StudentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStudentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Student model
 */
readonly fields: StudentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Student.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StudentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  registrations<T extends Prisma.Student$registrationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Student$registrationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RegistrationsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  college<T extends Prisma.Student$collegeArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Student$collegeArgs<ExtArgs>>): Prisma.Prisma__CollegeClient<runtime.Types.Result.GetResult<Prisma.$CollegePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  clubs<T extends Prisma.Student$clubsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Student$clubsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudentInClubPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  follows<T extends Prisma.Student$followsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Student$followsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CollegePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  followsClub<T extends Prisma.Student$followsClubArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Student$followsClubArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClubPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Student model
 */
export interface StudentFieldRefs {
  readonly id: Prisma.FieldRef<"Student", 'String'>
  readonly firstName: Prisma.FieldRef<"Student", 'String'>
  readonly lastName: Prisma.FieldRef<"Student", 'String'>
  readonly email: Prisma.FieldRef<"Student", 'String'>
  readonly password: Prisma.FieldRef<"Student", 'String'>
  readonly rollnumber: Prisma.FieldRef<"Student", 'String'>
  readonly collegeId: Prisma.FieldRef<"Student", 'String'>
  readonly createdAt: Prisma.FieldRef<"Student", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Student", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"Student", 'DateTime'>
  readonly otp: Prisma.FieldRef<"Student", 'String'>
  readonly otpExpiry: Prisma.FieldRef<"Student", 'DateTime'>
  readonly verified: Prisma.FieldRef<"Student", 'Boolean'>
}
    

// Custom InputTypes
/**
 * Student findUnique
 */
export type StudentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  /**
   * Filter, which Student to fetch.
   */
  where: Prisma.StudentWhereUniqueInput
}

/**
 * Student findUniqueOrThrow
 */
export type StudentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  /**
   * Filter, which Student to fetch.
   */
  where: Prisma.StudentWhereUniqueInput
}

/**
 * Student findFirst
 */
export type StudentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  /**
   * Filter, which Student to fetch.
   */
  where?: Prisma.StudentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Students to fetch.
   */
  orderBy?: Prisma.StudentOrderByWithRelationInput | Prisma.StudentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Students.
   */
  cursor?: Prisma.StudentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Students from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Students.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Students.
   */
  distinct?: Prisma.StudentScalarFieldEnum | Prisma.StudentScalarFieldEnum[]
}

/**
 * Student findFirstOrThrow
 */
export type StudentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  /**
   * Filter, which Student to fetch.
   */
  where?: Prisma.StudentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Students to fetch.
   */
  orderBy?: Prisma.StudentOrderByWithRelationInput | Prisma.StudentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Students.
   */
  cursor?: Prisma.StudentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Students from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Students.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Students.
   */
  distinct?: Prisma.StudentScalarFieldEnum | Prisma.StudentScalarFieldEnum[]
}

/**
 * Student findMany
 */
export type StudentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  /**
   * Filter, which Students to fetch.
   */
  where?: Prisma.StudentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Students to fetch.
   */
  orderBy?: Prisma.StudentOrderByWithRelationInput | Prisma.StudentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Students.
   */
  cursor?: Prisma.StudentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Students from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Students.
   */
  skip?: number
  distinct?: Prisma.StudentScalarFieldEnum | Prisma.StudentScalarFieldEnum[]
}

/**
 * Student create
 */
export type StudentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  /**
   * The data needed to create a Student.
   */
  data: Prisma.XOR<Prisma.StudentCreateInput, Prisma.StudentUncheckedCreateInput>
}

/**
 * Student createMany
 */
export type StudentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Students.
   */
  data: Prisma.StudentCreateManyInput | Prisma.StudentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Student createManyAndReturn
 */
export type StudentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * The data used to create many Students.
   */
  data: Prisma.StudentCreateManyInput | Prisma.StudentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Student update
 */
export type StudentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  /**
   * The data needed to update a Student.
   */
  data: Prisma.XOR<Prisma.StudentUpdateInput, Prisma.StudentUncheckedUpdateInput>
  /**
   * Choose, which Student to update.
   */
  where: Prisma.StudentWhereUniqueInput
}

/**
 * Student updateMany
 */
export type StudentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Students.
   */
  data: Prisma.XOR<Prisma.StudentUpdateManyMutationInput, Prisma.StudentUncheckedUpdateManyInput>
  /**
   * Filter which Students to update
   */
  where?: Prisma.StudentWhereInput
  /**
   * Limit how many Students to update.
   */
  limit?: number
}

/**
 * Student updateManyAndReturn
 */
export type StudentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * The data used to update Students.
   */
  data: Prisma.XOR<Prisma.StudentUpdateManyMutationInput, Prisma.StudentUncheckedUpdateManyInput>
  /**
   * Filter which Students to update
   */
  where?: Prisma.StudentWhereInput
  /**
   * Limit how many Students to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Student upsert
 */
export type StudentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  /**
   * The filter to search for the Student to update in case it exists.
   */
  where: Prisma.StudentWhereUniqueInput
  /**
   * In case the Student found by the `where` argument doesn't exist, create a new Student with this data.
   */
  create: Prisma.XOR<Prisma.StudentCreateInput, Prisma.StudentUncheckedCreateInput>
  /**
   * In case the Student was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StudentUpdateInput, Prisma.StudentUncheckedUpdateInput>
}

/**
 * Student delete
 */
export type StudentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  /**
   * Filter which Student to delete.
   */
  where: Prisma.StudentWhereUniqueInput
}

/**
 * Student deleteMany
 */
export type StudentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Students to delete
   */
  where?: Prisma.StudentWhereInput
  /**
   * Limit how many Students to delete.
   */
  limit?: number
}

/**
 * Student.registrations
 */
export type Student$registrationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Registrations
   */
  select?: Prisma.RegistrationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Registrations
   */
  omit?: Prisma.RegistrationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationsInclude<ExtArgs> | null
  where?: Prisma.RegistrationsWhereInput
  orderBy?: Prisma.RegistrationsOrderByWithRelationInput | Prisma.RegistrationsOrderByWithRelationInput[]
  cursor?: Prisma.RegistrationsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RegistrationsScalarFieldEnum | Prisma.RegistrationsScalarFieldEnum[]
}

/**
 * Student.college
 */
export type Student$collegeArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the College
   */
  select?: Prisma.CollegeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the College
   */
  omit?: Prisma.CollegeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CollegeInclude<ExtArgs> | null
  where?: Prisma.CollegeWhereInput
}

/**
 * Student.clubs
 */
export type Student$clubsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentInClub
   */
  select?: Prisma.StudentInClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentInClub
   */
  omit?: Prisma.StudentInClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInClubInclude<ExtArgs> | null
  where?: Prisma.StudentInClubWhereInput
  orderBy?: Prisma.StudentInClubOrderByWithRelationInput | Prisma.StudentInClubOrderByWithRelationInput[]
  cursor?: Prisma.StudentInClubWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.StudentInClubScalarFieldEnum | Prisma.StudentInClubScalarFieldEnum[]
}

/**
 * Student.follows
 */
export type Student$followsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the College
   */
  select?: Prisma.CollegeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the College
   */
  omit?: Prisma.CollegeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CollegeInclude<ExtArgs> | null
  where?: Prisma.CollegeWhereInput
  orderBy?: Prisma.CollegeOrderByWithRelationInput | Prisma.CollegeOrderByWithRelationInput[]
  cursor?: Prisma.CollegeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CollegeScalarFieldEnum | Prisma.CollegeScalarFieldEnum[]
}

/**
 * Student.followsClub
 */
export type Student$followsClubArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Club
   */
  select?: Prisma.ClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Club
   */
  omit?: Prisma.ClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubInclude<ExtArgs> | null
  where?: Prisma.ClubWhereInput
  orderBy?: Prisma.ClubOrderByWithRelationInput | Prisma.ClubOrderByWithRelationInput[]
  cursor?: Prisma.ClubWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ClubScalarFieldEnum | Prisma.ClubScalarFieldEnum[]
}

/**
 * Student without action
 */
export type StudentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
}
